### ISSUE TITLE
Macfuse macOS Sonoma

### ISSUE THREAD

**Issue by canutodev** [osxfuse/osxfuse#1005]
After installing macFuse you must necessarily select the "Reduced Security" option in "Security Utility". After doing this, the extensions are authorized. I wonder, but after this operation and therefore the authorization of the extensions, is it possible to return the Mac's security option to its initial state, i.e. "Full Security"? 

Another question. After mounting a remote resource, why is the mount point not mounted with the name I assigned but is mounted with the name "macFUSE Volume ........." ?

**Comment by bfleischer** [comment]
> I wonder, but after this operation and therefore the authorization of the extensions, is it possible to return the Mac's security option to its initial state, i.e. "Full Security"

If you return to the "Full Security" setting, you will no longer be able to load third-party extensions. This includes macFUSE.

> After mounting a remote resource, why is the mount point not mounted with the name I assigned but is mounted with the name "macFUSE Volume ........." ?

macOS displays the volume name instead of the folder name. Unless you specify a volume name, macFUSE will fall back to the default volume name. You can specify the volume name (when mounting the volume) by using the mount option `volname`. See https://github.com/macfuse/macfuse/wiki/Mount-Options#volname for details.
