### ISSUE TITLE
doc: about how to mount fuse directory in C ABI?

### ISSUE THREAD

**Issue by oowl** [osxfuse/osxfuse#1007]
Hi team ,I am trying to support our storage service read and write in MacOS by `macosfuse`, But I have to counter some problems.
1. in existing open source code search, `osxfuse` has been exposed `/dev/fuse` to user space to communication to other service. But I noticed `macosfuse` using `/dev/macfuseX` for these purposes, Can I get some documents for this behavior?
2. I do not know how to mount fuse filesystem to macos, I just try to use  `mount("/dev/fuse", "./example", flags, "fd=9,user_id=0,group_id=0,rootmode=40000")` syscall to mount it, but it did not work in my MacOS machine, it return `Error: Operation not supported by device (os error 19)`, Can I get some documents for this behavior too?

I know these behaviors have been hiding in https://github.com/macfuse/library, but we really want to know this behavior for dev purposes, Can I get help?

**Comment by bfleischer** [comment]
> in existing open source code search, osxfuse has been exposed /dev/fuse to user space to communication to other service. But I noticed macosfuse using /dev/macfuseX for these purposes, Can I get some documents for this behavior?

osxfuse exposed `/dev/osxfuseX` devices and macFUSE exposes `/dev/macfuseX` device. Different name, same devices. As far as I know, there was never a `/dev/fuse` device on macOS.

On macOS it is not possible to have a single `/dev/fuse` device since file descriptors work differently on macOS than on Linux. On macOS the character device switch table functions (cdevsw) are not invoked with a file descriptor, therefore it is impossible to use a single device for all virtual volumes.

> I do not know how to mount fuse filesystem to macos, I just try to use  mount("/dev/fuse", "./example", flags, "fd=9,user_id=0,group_id=0,rootmode=40000") syscall to mount it, but it did not work in my MacOS machine, it return Error: Operation not supported by device (os error 19), Can I get some documents for this behavior too?

You should never interact with the `/dev/macfuseX` devices directly or call `mount(2)` in your code. Instead you should call `/Library/Filesystems/macfuse.fs/Contents/Resources/mount_macfuse` just like libfuse does. `mount_macfuse` will return a file descriptor that you can use to communicate with the kernel. 

See https://github.com/macfuse/library/blob/master/lib/mount_darwin.c#L407 for details. It's the same mechanism used on Linux.

**Comment by oowl** [comment]
@bfleischer Hi, Thank you for your clear and kind response, I have let my program work fine in MacOS. It will be better if you can write these descriptions in the development doc. https://github.com/macfuse/macfuse/wiki/Getting-Started-(Developer)
