### ISSUE TITLE
MacFuse 4.8.0 won't load on MacOS 14.5

### ISSUE THREAD

**Issue by andreagrandi** [osxfuse/osxfuse#1028]
Hi,

I just updated MacFuse from 4.6.0 to 4.8.0 (long story short: I updated pCloud and it stopped working, complaining about this extension not loading, so I uninstalled pCloud, uninstalled MacFuse and reinstalled the latest version), but despite me enabling it in the Privacy settings:

<img width="500" alt="Screenshot 2024-06-26 at 21 45 34" src="https://github.com/osxfuse/osxfuse/assets/636391/6f3eabdd-c3ec-4450-bddd-c2b7aa3a7561">

I click the toggle, enter my password and reboot etc....

After the system reboots, I check this setting again and the extension is still **disabled**.

How can I make this work? Thanks

p.s: I've tried to completely uninstall MacFuse, reboot, reinstall again etc... but it just doesn't work. The extension is always unloaded. As soon as I enable, it asks me the password, I reboot etc... and it's still disabled. It's like a dead loop

p.p.s: I tried this workaround too https://github.com/osxfuse/osxfuse/issues/1013#issuecomment-2120182364 but it didn't help

I've also tried to load the extension manually, but no success:

```shell
~ sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
Password:
Error Domain=KMErrorDomain Code=27 "Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Preferences.}
```

**Comment by TruffelNL** [comment]
Same here. Tried #1013 and your suggestion but it won't load.

**Comment by latent-capital** [comment]
<img width="484" alt="image" src="https://github.com/user-attachments/assets/692780a1-8120-46e0-886a-1a25549f2944">

It is working here on macos 15.0 Beta (24A5309e).

After the message "not approved to load. Please approve using System Settings" you mention, the corresponding framework should pop-up the attached system settings dialogue.

I can confirm that the GUI installer failed to display the correct system settings pane, but it worked via the command line you mention.

**Comment by reetp** [comment]
+1 

Macbook Pro M1
Sonoma 14.6.1
MacFuse 4.8.0

Removed other versions. Still has the permissions restart loop :-(

**Comment by highnrg-duplicate** [comment]
not working for me on 14.6 so mounty stoped working any one knows what to do about it ??

**Comment by MartinAntiphonMU** [comment]
Same here... 
Macbook Pro M2
Sonoma 14.6.1
MacFuse 4.8.0

**Comment by nelimitat** [comment]
I also tried to install Mounty yesterday (I upgraded to macOS 14.6.1 and Tuxera NTFS stopped working) and indeed I am stuck in the restart/reboot extension loop, thus Mounty is not working.

**Comment by mdolce8** [comment]
Similar problem for me. 

MacBook Air M3
Sonoma 14.7
MacFUSE 4.8.0. 

I don't get the System Extensions window in System Preferences. I tried what was suggested in the "Getting Started" instructions and running the kernel manually via the command provided.
`/usr/bin/sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext` 

I get the same error:
```
Error Domain=KMErrorDomain Code=27 "Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Preferences.}
```

**Comment by m23x2** [comment]
On Sequoia latest beta: permissions restart loop :(

Any ETA when the new Apple API will be used?

**Comment by bfleischer** [comment]
> Any ETA when the new Apple API will be used?

Apple has not released the new API (FSKit), yet. In recent beta release the API has not been in a working state.

**Comment by bfleischer** [comment]
In order to look into issues preventing the kernel extension from loading, kmutil logs are needed. Update to the latest minor (preferably major) version of macOS and the latest version of macFUSE. Then try to load the kernel extension, follow the steps to allow loading the kernel extension, reboot your Mac and try to load the kernel extension. In case you are prompted to allow loading the kernel extension again, run the following command in Terminal.

```
kmutil log show
```

The logs usually contain clues as to why the kernel extension could not be loaded. In almost all cases I have looked into so far, a macOS issue/bug or an isolated issue on the particular Mac prevented the macFUSE kernel extension from loading. In case you need help interpreting the logs, post them here and I will try to have a look.

**Comment by zcutlip** [comment]
I'm getting this problem as well

This is in a macOS 14.6 VM running in VirtualBuddy. macFuse version is 4.8.2.

Here's a screenshot
![Screenshot 2024-10-29 at 2 36 36 PM](https://github.com/user-attachments/assets/ee29eb21-edbb-4e2c-b1ff-6424a2afda75)

I've also attached the output of `kmutil log show` as requested above.
[kmutil.log.gz](https://github.com/user-attachments/files/17563446/kmutil.log.gz)

**Comment by bfleischer** [comment]
@zcutlip Kernel extensions are not supported in virtual machines. This is a macOS limitation, not a macFUSE limitation.

**Comment by zcutlip** [comment]
@bfleischer ahhhh, too bad. Okay thanks for the quick response

**Comment by nephthys** [comment]
I can't install macFuse 4.8.2 & 4.8.3 on macOS Sequoia 15.1 (24B2083).

I keep getting this message: "_Error with system extensions_"

<img width="539" alt="macfuse1" src="https://github.com/user-attachments/assets/de6a632d-23b0-44c1-8b87-ea269dd00a86">

<img width="377" alt="macfuse2" src="https://github.com/user-attachments/assets/208a2cdf-2ae1-4332-a074-5f2619280187">

I don't know if this helps but macOS is installed on a (Thunderbolt) external drive. I wanted to install pCloud and enable the pCloud Drive but I had the same issues (kernel extension stuck in loop).

Here is the output of `kmutil log show` : [kmutil.log.gz](https://github.com/user-attachments/files/17834365/kmutil.log.gz)

Thanks in advance for your help

**Comment by bfleischer** [comment]
@nephthys macOS does not support loading third party kernel extensions when installed on an eternal volume. This is a macOS limitation.

**Comment by nephthys** [comment]
@bfleischer Hmm ok, I didn't know. Sorry for reporting that... I usually install macOS on the internal drive, maybe it would be relevant to indicate this detail when installing macFuse no?

**Comment by sylvank** [comment]
In case this helps anyone: I was having an identical issue with **jmPeripheralDevice.kext** which is distributed with QNAP External RAID Manager. While not MacFuse related, the problem is similar as users have described here (which is why I am posting this).

The solution, found here: https://forums.macrumors.com/threads/installing-kexts-allow-button-not-working-final-solution.2372899/

> On later macOS versions, running kmutil trigger-panic-medic from Terminal in Recovery resets the allow status and the user has to re-allow each kext.

I confirm that in my case, booting into recovery, running:
**`kmutil trigger-panic-medic --volume-root /Volumes/Macintosh\ HD`**

then restarting, then forcing the kernel extension to load:

`sudo kmutil load -p /Library/Extensions/jmPeripheralDevice.kext`

Now prompted to approve the extension in Security & Privacy, which worked this time (and continued to work following multiple reboots). 

Note that kernel extensions were already permitted in Startup Security Utility, which is a necessary step to enabling third party kernel extensions, as described here: https://github.com/macfuse/macfuse/wiki/Getting-Started

**Comment by fredericgermain** [comment]
Thank you for pointing out the article @sylvank 

I'm on Sequoia 15.7.2 (24G325), I think my Mac is quite restricted by policies.
The `trigger-panic-medic` didn't seem to work for me.

What I did to make it work is to run in recovery `spctl kext-consent add 3T5GSNBU6W`. Then restart twice...

That's the teamId that we could find with `codesign -dv --verbose=4 /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext`

==> Authority=Developer ID Application: Benjamin Fleischer (3T5GSNBU6W)
