### ISSUE TITLE
The "volname" option is missing from the sshfs help text and the man page.

### ISSUE THREAD

**Issue by KeveNagy** [osxfuse/osxfuse#111]
I often use the -ovolname=MyPreferredVolumeNameHere sshfs option, but I don't see it listed in the text shown by "sshfs -h" or in the manual page shown by "man sshfs". This option is useful enough to deserve to be shown.

**Comment by chrisRidgers** [comment]
second this.  Second mac I've installed this on in the last year, and both times I've had to trawl the internet looking for this setting.

Really should be in the man pages and in the help text.

Is it not included because it's experimental (along with perhaps potentially some other features) Or has it been forgotten about (again, maybe with some other features?)

Great software, but definitely something that needs adding to the documentation.

**Comment by mralexgray** [comment]
+1 `-o volname=whatever` ___FTW___

**Comment by Nemant** [comment]
+1
