### ISSUE TITLE
ntfs-3g 2014.2.15 doesn't remove folder in Volumes after unmount

### ISSUE THREAD

**Issue by linkit87** [osxfuse/osxfuse#119]
I've upgraded to the new ntfs-3g 2014.2.15 version, but now when I unmount a drive I still have the folder in /Volumes

**Comment by sir-brickalot** [comment]
I'm still suffering from the issue, installed Version is 2.7.5 installed v2.7.4 via pkg, updated via app and tried to compile master branch like hallelujah described (but couldn't finish last step: open /tmp/osxfuse/distribution/Distribution.pkg, because it wasn't available). So still on 2.7.5.

**Comment by wodim** [comment]
Bug still there.

**Comment by justinkb** [comment]
Damn. No offense. But not having released any signed binaries with this fix in it after well over a year of this bug being reported is pretty pathetic.

Guess I was right about a) this being an osxfuse issue, not an ntfs-3g issue as bfleischer kept insisting
and b) this not gonna be fixed properly as a result.

What a shame

**Comment by LongLVNH** [comment]
I share your opinion Justinkb, that was one reason I was pretty disappointed at first and posted a solution using Fuse4x in the best way I was able to write it so that maybe it would be of any use to the people who are having this issue.

Just to back you up, you are right about a) and I guess about b) as well.

**Comment by fernandofig** [comment]
About b), I'd say for you guys to just chill - the fix has been merged for awhile, so it *will* make into a release, eventually. Unfortunately, bfleischer only knows when.

I agree that this bug has received less attention / priority than it deserves. I've ranted about it myself before, so I'll not bore you repeating myself again. I'll repeat this though: complaining here will not change anything. This is a governance problem, the only way to get around that is by either changing the governance (not happening for obvious reasons), or forking the project (not happening because of lack of talent able to work on it - and it's not guaranteed to improve things anyway).

So, that's life folks. We just have to chuck it and make the best of it.

**Comment by anacrolix** [comment]
This is very disappointing. It stinks like the Python 3 port. Maybe the plan is to pile enough features and bug fixes onto the next version (which I believe is some kind of major rewrite) that people will be forced to upgrade. Has anyone isolated the fix for this so that they can release a pkg with just that change?

**Comment by wodim** [comment]
@bfleischer dolan pls. My disk is called Windows and I'm already at "Windows 1488".

**Comment by benwilson** [comment]
Script to keep Volumes directory clean. Will fail to delete if it results in data loss. 
Change `rmdir` to `rm -rf` at your own risk.
```bash
#!/bin/bash
#
# osxfuse-dirfix.sh 
#
# Iterate /Volumes/* and remove any directory that isn't in `mount`
# (ignores all symlinks, OSX creates one for root fs)
#
for f in /Volumes/*; do
	if [[ -d "$f" && ! -L "$f" ]]; then
        mount | grep "on $f" > /dev/null
        if [ $? -ne 0 ]; then
    		rmdir "$f/.Spotlight-V100" &> /dev/null
    		rmdir "$f/.Trashes" &> /dev/null
    		rmdir "$f" &> /dev/null
		fi
    fi
done
```

I run it in root crontab every 5 minutes.
```
*/5 * * * * /path/to/osxfuse-dirfix.sh
```

It's an ugly bandaid, but if you have applications or scripts that depend on specific locations, it helps.

**Comment by muellermartin** [comment]
I've just installed the latest release (3.0.4) via the provided DMG installer and the issue seems to be resolved.

The extension is even signed by @bfleischer so there is no need for disabling the signature checks (`nvram boot-args=kext-dev-mode=1`). Sadly, I couldn't update the Homebrew Formula to provide an updated package, because I don't know how Homebrew handles the codesigning stuff and building it from source would require a valid certificate…

Anyway, thank you very much for finally fixing this! Is there are way to donate?

**Comment by I02RUBERDUCKS** [comment]
I've just noticed this issue on my MacBook Pro. OSXFuse Version 2.8 and NTFS-3G 2015.3.14 (built from home-brew as per the wiki). I have the lingering entries in /Volumes and also the mounted volumes don't appear in finder, I have to go into /Volumes to access them. OS X 10.11 Build 15A262e

**Comment by paaguti** [comment]
Same here with 10.10.5. Reinstalled with "brew cask" as per WIKI.

**Comment by paaguti** [comment]
Wasn't able to build OSXFUSE from github:
`paag:osxfuse paag$ ./build.sh -t distribution
Falling back to OS X 10.11 SDK as default SDK
T:distribution       | Clean target
T:distribution       | Build target for OS X 10.11
T:fsbundle           | Clean target
T:fsbundle           | Build target for OS X 10.11
T:kext               | Clean target
T:kext               | Build target for OS X 10.11
T:kext               | Install target
T:fsbundle           | Install target
T:library            | Clean target
T:library            | Build target for OS X 10.11
T:library            | Failed to configure target
Terminated: 15`
Anyone can point me to an official 3.0.x distribution I can use?

**Comment by jamestwotree** [comment]
@paaguti You can find the OSX FUSE Github release page: https://github.com/osxfuse/osxfuse/releases

**Comment by capthy** [comment]
jamestwotree  this works for me

**Comment by paaguti** [comment]
I'm using OSXFuse 3.0.3 and it seems to work on Yosemite

**Comment by stechico** [comment]
OSXFuse 3.0.6 on 10.11. Not working.

**Comment by paaguti** [comment]
Good to know. I'll stay Yosemite for some time I guess

**Comment by jamestwotree** [comment]
OSXFuse 3.0.6 works just fine for me on 10.11

**Comment by stechico** [comment]
Hmm... I did the DMG install of OSXFuse. Did you use the brew version install of it? @jamestwotree

**Comment by jamestwotree** [comment]
@stechico Yep I used the DMG install.  Did you make sure to safely eject your external hard drive first, delete all mounts, reboot, then reconnect it?

**Comment by stechico** [comment]
@jamestwotree Can you quickly run me through those steps please



On Saturday, October 17, 2015, jamestwotree <notifications@github.com>
wrote:

> @stechico <https://github.com/stechico> Yep I used the DMG install. Did
> you make sure to safely eject your external hard drive first, delete all
> mounts, reboot, then reconnect it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osxfuse/osxfuse/issues/119#issuecomment-148901692>.
>


-- 
Sent from Mobile--please excuse terseness and typos.

**Comment by stechico** [comment]
This seems to have helped me, https://support.apple.com/en-us/HT203258

Thanks

**Comment by jamestwotree** [comment]
@stechico Yep that's the same guide I followed.  Glad it worked.

**Comment by viniciusuriel** [comment]
+1 Version 3.0.4 works correctly with ntfs-3g regards the folder names and additionally the volume icon now appears in finder too.

**Comment by saaqibz** [comment]
Thanks +1 that upgrading from stable to version 3.0.9 fixed this problem for me on Yosemite.

**Comment by bfleischer** [comment]
osxfuse 3.2.0 has been released, so I'm closing this ticket.

**Comment by ptoche** [comment]
Why is 2.8.3 listed as a 'stable' release when it's clearly not quite so?

https://osxfuse.github.io/

**Comment by elmosgot** [comment]
The solution for me was to install the beta version:

1. Go to 'System preferences'
2. Click on 'FUSE for macOS'
3. Select the option 'Show beta versions'
4. Click 'check for updates'
5. Install the update
6. Unmount drive/partition
7. Remove /Volume duplicate folders
8. Mount drive and all works fine also with permissions

**Comment by sir-brickalot** [comment]
I didn't see this issue with latest versions at all.

**Comment by wodim** [comment]
This still happens with 2.8.3.
