### ISSUE TITLE
osxfuse malfunction under larger io

### ISSUE THREAD

**Issue by sexywsky** [osxfuse/osxfuse#181]
Hardware: Mac Mini late 2012 with the default 5400RPM HDD
Software: OSX Mavericks 10.9.5, OSXFUSE 2.7.2 (installed with macports)

I notice that my encfs/osxfuse container mulfunctions under larager inner I/O on my system, the symptoms are data corruption or the container stops being writabe and the os writes data to the container's mount point instead the sub-filesystem.

**Comment by bfleischer** [comment]
@megabrein Judging from your description VeraCrypt does not seem to handle unmounts correctly. When unmounting a FUSE volume osxfuse needs to be able to flush unwritten changes. VeraCrypt not responding to those requests might explain the long waits you are seeing. Anyway, this is something the VeraCrypt team needs to take a look at.

Since there has not been any further feedback from @sexywsky I'm assuming the original issue has been fixed.
