### ISSUE TITLE
cannot mount with fstab

### ISSUE THREAD

**Issue by johntrandall** [osxfuse/osxfuse#194]
Hello. 

I'm trying to mount a drive pool with the following fstab entry: 

    mhddfs#/Volumes/D01,/Volumes/D12/,/Volumes/D103/,/Volumes/D110 /mnt/DrivePoolB osxfuse nonempty,allow_other 0 0

I reload the fstab by running:

     $ sudo mount -a

This returns the following error:

     mount: exec /System/Library/Filesystems/osxfuse.fs/Contents/Resources/mount_fuse for /mnt/DrivePoolB: No such file or directory

However, the osxfuse installer doesn't ever write anything to /System/Library/Filesystems... it writes to /Library/Filesystems. So fstab can't find the .fs file where it is looking for it. 

Should the osxFuse installer put symlinks in /System/Library?  Or, more cleanly, can fstab be pointed at /Library Filesystems instead? Any suggestions on how to resolve this?

**Comment by bfleischer** [comment]
The `/System` directory is reserved for Apple. Custom file systems need to be installed in `/Library/Filesystems`. Please see https://code.google.com/p/macfuse/wiki/AUTOMOUNTING for details on how to create an fstab entry for FUSE file systems on OS X.

**Comment by pasnox** [comment]
I'm do have a similar error with el Capitan and EncFS driver.
All works fine by hands but fails from fs tab with:
mount: exec /Library/Filesystems/fuse.fs/Contents/Resources/mount_fuse for /Volumes/Shared/EncFS: No such file or directory

Note though that the directory do exists but the filesystems fuse.fs is not, it does exists an osxfuse.fs, but it does not contains the mount_fuse binary.

I tried to create a /sbin/mount_encfs symlink to /usr/local/bin/encfs but that's still failing: El Capitan does not allow to write in due to rootless new feature.

Can you try to explain me how i can auto mount at start up an encfs partition using stab ?
I do use that on inure and it does works just fine.

Thanks,

**Comment by hbast** [comment]
I add this information because I is not that obvious.

The error messages means that mount_fuse is in the correct path. You can therefore generate a symbolic link like:

`sudo ln -s /usr/local/bin/mount_fuse /sbin/mount_fuse`

or for bindfs

`sudo ln -s /usr/local/bin/bindfs /sbin/mount_fuse.bindfs`

**Comment by x4base** [comment]
＠pasnox, I use LaunchDaemons instead of fstab to mount at boot and it works. See my comment in mpartel/bindfs#87
