### ISSUE TITLE
Modifications via mmap not available when closing/unmapping

### ISSUE THREAD

**Issue by jacobsa** [osxfuse/osxfuse#202]
I have a test that does the following:

1. Open a file on a fuse file system.
2. Write some contents into the file.
3. mmap the file into memory.
4. Modify the mapped memory.
5. Close the file.

On Linux, the fuse write request for the modifications in step (4) happens before the flush request for the file close in step (5), which is what I hope for. On OS X, I find the following sequence of fuse requests:

1. When the user opens the file, fuse sends an open request.
2. When the user writes to the file, fuse sends a write request.
3. When the user writes to memory, fuse sends no requests.
4. When the user calls munmap, fuse sends a bunch of getattr requests.
5. When the user closes the file, fuse sends a flush request.
6. When the file system is unmounted, fuse sends the following requests:
   * Open
   * Write
   * Fsync
   * Release

So the content from writing to the mapping is not available until unmount time, after munmap has returned. This is true even if I mount with `nolocalcaches`. This is unfortunate because in my file system flush/fsync may fail, and I want the user to be able to receive any write errors when cliosing and/or unmapping.

Like #199, this may be a case of "OS X is not Linux". @bfleischer: Could you shed some light?

**Comment by bfleischer** [comment]
Yes, this is another case of "OS X is not Linux".

OS X completely ignores the return value of vnode operation mnomap (i.e. munmap). mnomap only serves as a hint. This means it cannot be used to write back the changes.

munmap(2) states:

    If the mapping maps data from a file (MAP_SHARED), then the memory
    will eventually be written back to disk if it's dirty.  This will
    happen automatically at some point in the future (implementation
    dependent).  Note: to force the memory to be written back to the
    disk, use msync(2).

So there are pretty much no guaranties when the data will be written back. Have you tried running `msync(2)` to see if it triggers a write back?

This would leave the close vnode operation to perform the actual write back. To be honest I am not sure why it is not done this way. I will need to do some research. The whole design dates back to the MacFUSE days.

mmap requires kernel-side caching. This is the reason why `nolocalcaches` has no effect for mmap.

**Comment by jacobsa** [comment]
Thanks for the note about msync(2). I added that, so that the sequence is now:

1. Open a file on a fuse file system.
2. Write some contents into the file.
3. mmap the file into memory.
4. Modify the mapped memory.
5. msync the mapping (with no flags or with `MS_SYNC`, no difference in behavior).
6. Unmap (I forgot to mention this one in the original comment).
7. Close the file.

Now the behavior looks like:

1. When the user modifies, fuse sends nothing.
2. When msync is called, fuse sends a write.
3. When munmap is called, fuse sends a bunch of getattrs and lookups.
4. When close is called, fuse sends a flush.

This is much more sane; if I tell my users to be sure they do msync then munmap
then close, they get durable data.

It's worth nothing explicitly that on Linux `msync(MS_SYNC)` results in an fsync, while on OS X it results in a writeback. But the OS X man page for msync says:

>  The msync() system call writes modified whole pages back to the filesystem and updates the file modification time.

which does sound like a write.

So, working as intended maybe? Sorry, I hope this doesn't feel like a waste of your time.

**Comment by bfleischer** [comment]
Sorry for the late reply.

> So, working as intended maybe?

Yes, I think it is working within the bounds defined in `munmap(2)`:

    If the mapping maps data from a file (MAP_SHARED), then the memory
    will eventually be written back to disk if it's dirty.  This will
    happen automatically at some point in the future (implementation
    dependent).

But, at least in my opinion, this is not ideal, especially when dealing with distributed file systems. Therefore I added a call to msync  when a file is being unmapped. Although, this call may fail without the error being propagated back to user space, as outlined above. There does not seem to be a better way of ensuring data consistency. Apple's NFS client implementation handles this the same way.

A few things i noticed researching this:

fuse_vnop_mnomap (unmap handler in kernel extension) is called when there are no more references to the file's mapped data. In other words, we have no way of knowing when a particular process unmaps a file since the file's data might still be referenced by other processes (MAP_SHARED).

File handles used to create mappings can be closed before unmapping the file, i.e. calling ubc_msync in fuse_vnop_close is not going to help here. mmap(2) states:

     The close(2) system call does not unmap pages, see munmap(2) for
     further information.

All in all, calling `msync(2)` after altering a memory mapped file is the only way to make sure the file's contents is written back promptly.

**Comment by jacobsa** [comment]
Great, thanks so much for the careful write-up.

**Comment by jacobsa** [comment]
@bfleischer: has this changed with osxfuse 3?

I wrote [a test](https://github.com/jacobsa/fuse/blob/eaa0177b80daf4c82ffae826983c5d3d245f6c5b/samples/flushfs/flush_fs_test.go#L586-L620) for this behavior that was passing with osxfuse 2 and now fails in osxfuse 3. It appears the behavior now matches Linux–closing the file causes a flush with up to date contents, even if `msync(2)` hasn't been called.
