### ISSUE TITLE
Why is `open` not issued prior to `read`/`write` operation sometimes?

### ISSUE THREAD

**Issue by netheril96** [osxfuse/osxfuse#203]
In my implementation of a FUSE system, I log all the calls to operations defined in `struct fuse_operations`. I find it odd that many times the `read` and `write` calls are not preceded by `open`. In fact, there are many times that `release` gets called before any `open` and `read`, sometimes multiple calls. Sometimes `open` do gets called, but I cannot figure out any pattern when.

Currently, I do an `open` inside `read` or `write` if the file handle is zero. This temporarily solves the problem of reading and writing, but it fails to properly deallocate resources except on unmount.

Is there any reason for this behavior?

**Comment by bfleischer** [comment]
Open FUSE file handles are being reused on OS X. This is a technical necessity due to differences of the OS X and Linux VFS layers. On OS X file handles do not make their way to the VFS layer. This means on OS X VFS plugins like osxfuse have no way of knowing which file handle was used to perform a particular read, write, or close operation. This is means the kernel extension does not know which file handle to pass along to the user space file system implementation.

We deal with this by "multiplexing" FUSE file handles. osxfuse will reuse existing open FUSE file handles provided that they are compatible, i.e. the read/write open mode matches. As a result you will see only one open callback when opening the same file twice (with the same mode) without closing the first handle before the second open.

This means FUSE file handles may be kept open for a long time and might even be shared by multiple processes. But you will never receive a read or write callback for a closed file.

**Comment by netheril96** [comment]
@bfleischer 

Thanks for the clarification. But my problem is different. In my case, I freshly mount my little filesystem, single-threaded, and start reading files out of it. According to the log, the call order is first many `getattr`, then `release`, then `read`, without `open` anywhere.

**Comment by bfleischer** [comment]
Technically it should not even be possible for the kernel extension to send out read or write requests without opening the file first.

Please see the loopback reference file system at https://github.com/osxfuse/filesystems/blob/master/filesystems-c/loopback/loopback.c. It would certainly crash if there were any read/write requests on non-open files. Therefore I think this might be a bug in your file system implementation rather than in osxfuse.

If you are convinced there is a bug in osxfuse, please provide a simple demo.

**Comment by netheril96** [comment]
@bfleischer 

In what ways will the call order be affected by my own code? I initially believed that my own code only supplied the callbacks, but had no control of when they were being called.

**Comment by bfleischer** [comment]
> I initially believed that my own code only supplied the callbacks, but had no control of when they were being called.

This is correct. You provide the callbacks, osxfuse calls them. You cannot control when your callbacks will be called.

I'm sorry but without some demo code there is not much I can do. The loopback reference file system works as expected and I do not see how read or write might be called for non-open files. To be honest, besides yours there has not been a single bug report suggesting such a behavior since I started working on osxfuse four years ago. Can you provide some demo code?

**Comment by netheril96** [comment]
@bfleischer 

I am refactoring my existing code. If I am able to reproduce this behavior after the refactor, I will try reduce it to a minimum demo and submit a bug report.

**Comment by netheril96** [comment]
@bfleischer 

Just so you know, after the refactoring the `osxfuse` behavior restores to normal. Perhaps my previous code has undefined behavior that interacts strangely with libraries.

**Comment by bfleischer** [comment]
Great, thanks for the feedback.
