### ISSUE TITLE
Do I need to check permissions in my own code?

### ISSUE THREAD

**Issue by netheril96** [osxfuse/osxfuse#204]
I am writing my own filesystem. In the callbacks I supply in `struct fuse_operations`, such as `open`, `read`, `getattr`, do I need to check file permissions myself or does the `FUSE` kernel extension already handle it?

If I have to handle it in my own code, is there any platform independent way to check if a user belongs to certain group? That is essential to correct filesystem permissions.

**Comment by fhgwright** [comment]
This isn't authoritative, but empirically, with the low-level interface, it appears that the usual permission checks are applied if:

1) No .access function is provided.
2) A provided .access function returns ENOTSUP.
or
3) A provided .access function returns ENOSYS.

The difference between option 2 and option 3 is that returning ENOSYS is remembered and disables all future calls to the .access function.  I'm not sure why that's more useful than option 1.

Option 2 is useful if you want to track .access calls for debugging.

Checking group access yourself is a PITA, since fuse_ctx doesn't provide any information about supplemental groups.

**Comment by netheril96** [comment]
@fhgwright 

So do you mean that if I leave `access` unimplemented, I can count on `FUSE` kernel to do the permission test for me? Given the absurd amount of `getattr` calls, I believe that is not improbable.

**Comment by fhgwright** [comment]
I believe that's correct, and it's consistent with cases I've tested, though I don't claim to have tested it exhaustively.

I made some attempt to find the relevant code, but it appears that that behavior is part of the general vfs mechanism, and not specific to fuse filesystems at all.

**Comment by netheril96** [comment]
@fhgwright 

> but it appears that that behavior is part of the general vfs mechanism

Is this specific to the OS X VFS, or is it the same in Linux as well? A reasonable guess is welcome.

I am already leaning towards skipping the check myself, given that most of the time FUSE does not allow any one other than the mounting user to access the filesystem at all.

**Comment by fhgwright** [comment]
I only looked at OSX, and only briefly at that.  It's all open source. :-)

**Comment by jacobsa** [comment]
On Linux at least you want to mount with `default_permissions` (see [here](https://github.com/torvalds/linux/blob/a33f32244d8550da8b4a26e277ce07d5c6d158b5/Documentation/filesystems/fuse.txt#L91-L98)) in order to have the kernel deal with permissions for you. osxfuse appears to behave the same way as Linux if you do.

Note that if you use `default_permissions`, you'll want to make sure you return sane values for the uid and gid of inodes, otherwise you won't be able to access anything. A reasonable choice is the uid and gid with which your file system daemon was run.
