### ISSUE TITLE
Sourceforge site is offline

### ISSUE THREAD

**Issue by TopazA** [osxfuse/osxfuse#221]
Sourceforge site has been offline for more than 9 hours now and is redirecting to http://sourceforge.net/error-404.html?project=osxfuse

When attempting to install via brew hashcheck fails. 

Is it possible to get a mirror up or hosted on github?

**Comment by ShadowLNC** [comment]
I would like to second this. SourceForge has been doing some shady things lately, and I don't trust their download hosting any more: http://www.reddit.com/r/linux/comments/37h4x5/sourceforge_hijacking_project_accounts_gimp/

**Comment by bfleischer** [comment]
Sourceforge is back online.

> I would like to second this. SourceForge has been doing some shady things lately, and I don't trust their download hosting any more:
 
I agree with you. That's why osxfuse 3 will be back on GitHub. The first two pre-release versions can be found on https://github.com/osxfuse/osxfuse/releases. Hosting was only moved to SourceForge because GitHub killed the "Downloads" section.

Please note that the osxfuse updater (preference pane) checks the integrity of downloaded installer packages. There is no way the updater would install an altered version of osxfuse.
