### ISSUE TITLE
If getattr triggered by invalidation gets ESTALE, the mountpoint hangs

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#233]
Running a 3.0.5+0d78120c5e1ed4a3aebab8e8f084d145515a2d5b from https://github.com/osxfuse/osxfuse/issues/232#issuecomment-138386381

Since #229, an invalidation triggers a synchronous getattr request. If this getattr happens to get an `ESTALE` error, the mount hangs right there, the userspace process serving it becomes unkillable, the fs becomes unmountable, and a shutdown hangs.

I wrote a simple fuse filesystem to demonstrate this, with a single file `demo` in it; reading the file causes an invalidation, and makes future getattr calls return `ESTALE`. The supporting files are at https://gist.github.com/tv42/3dcb6704f8cddd6e1c33 , and `estale` is the prebuilt OSX binary for the filesystem.

To trigger the bug, run

```console
# in one terminal
$ ./estale mnt

# in another terminal
$ cat mnt/demo
```

As a reference for what is the expected behavior, here's what happens on Linux:

```console
$ cat mnt/demo
hello, world
cat: mnt/demo: Stale file handle
$ cat mnt/demo
cat: mnt/demo: Stale file handle
$
```

On OSX, the first `cat` makes things hang.

The [gist](https://gist.github.com/tv42/3dcb6704f8cddd6e1c33) has request-response logs etc detail.

**Comment by bfleischer** [comment]
Thanks @tv42, the hang should be fixed in the following build (3.0.5_2):

https://www.dropbox.com/s/o5ojz9pz22o7bj3/osxfuse-3.0.5_2.dmg?dl=0

But the behavior differs slightly between OS X and Linux. In Linux `getattr` is called before the next read. Thats why `cat` returns `Stale file handle`. On OS X we do not call `getattr` before the actual read. Since the demo file systems keeps returning valid data for read requests the result looks like this:

```
$ cat mnt/demo
hello, world
$ cat mnt/demo
hello, world
$ cat mnt/demo
hello, world
...
```

**Comment by tv42** [comment]
Thanks, testing now. Different behavior itself is fine, the hang was what had me worried.

**Comment by tv42** [comment]
I can confirm this fixes the hang.

**Comment by bfleischer** [comment]
Great!
