### ISSUE TITLE
Integer Type Inconsistencies

### ISSUE THREAD

**Issue by Asher-** [osxfuse/osxfuse#251]
I am looking at the LoopbackFS filesystem-objc example and noticing what appear to be inconsistencies in integer type usage in the OSXFuse interfaces (at least as far as Mac OS X 10.11, or presumably any 64 bit version, is concerned). 

For example:

* pread and pwrite return long but are assigned to int because readFileAtPath:userData:buffer:size:offset:error: and writeFileAtPath:userData:buffer:size:offset:error: return int.
* position parameter in OSXFuse interfaces consistently use off_t (long long on OS X 10.11) but then valueOfExtendedAttribute:ofItemAtPath:position:error: passes position to getxattr, which expects uint32_t, and setExtendedAttribute:ofItemAtPath:value:position:options:error: does the same with setxattr.

Please correct me if I'm wrong, but wouldn't it be most appropriate for OSXFuse to provide consistency here rather than assuming the implicit conversion works properly (when obviously there are theoretical cases that will fail, even if they may never occur)?

**Comment by Asher-** [comment]
I believe the proper return value for readFileAtPath:userData:buffer:size:offset:error: and writeFileAtPath:userData:buffer:size:offset:error: should be ssize_t rather than long.

Not sure what the most appropriate resolution is for off_t, which getxattr/setattr expect to be u_int32_t. Perhaps simply changing the parameter for position in valueOfExtendedAttribute:ofItemAtPath:position:error: and setExtendedAttribute:ofItemAtPath:value:position:options:error: to u_int32_t, which off_t should implicitly convert to without issue.

**Comment by bfleischer** [comment]
OSXFUSE.framework is based on libosxfuse which in turn is a patched version of the Linux libfuse library. libfuse expects the read and write callbacks to return `ints`. That is why `readFileAtPath:userData:buffer:size:offset:error:` and `writeFileAtPath:userData:buffer:size:offset:error:` should return ints as well.

As for `valueOfExtendedAttribute:ofItemAtPath:position:error:` and `setExtendedAttribute:ofItemAtPath:value:position:options:error:` libosxfuse passes the position parameter as `uint32_t` but OSXFUSE.frameworks converts it to `off_t` before calling the file system delegate. You are absolutely right, this makes no sense.

Fixing this without loosing binary compatibility with existing i386 file systems is not possible, though. On i386 the size of each argument is a multiple of 4 bytes. See https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/LowLevelABI/130-IA-32_Function_Calling_Conventions/IA32.html#//apple_ref/doc/uid/TP40002492-DontLinkElementID_228 for details. Existing i386 file system binaries expect a 8-byte value. Replacing `off_t ` (8 bytes) with `uint32_t` (4 bytes) in OSXFUSE.framework would result in existing i386 file systems crashing due to a segmentation fault.

For x86_64 file systems replacing `off_t` with `uint32_t` would work fine because the size of integer arguments is a multiple of 8 bytes. See section 3.2.3 of http://people.freebsd.org/~obrien/amd64-elf-abi.pdf for details.

**Comment by Asher-** [comment]
Am I correct i understanding the issue as: existing binaries relying on the Fuse kext will lose ABI compatibility? 

Which i386 systems are relevant here? Perhaps I am misunderstanding, but it sounds to me like this only implicates OS X versions of Fuse. Does that mean the concern is supporting Macs from 2006 and earlier?

**Comment by bfleischer** [comment]
> Am I correct i understanding the issue as: existing i386 binaries relying on the Fuse kext will lose ABI compatibility?

Its not about the kernel extension or whether the Mac has a 32 or 64 bit Intel CPU. All that really matters is whether the i386 section of the file system binary is being executed or not. This can even be the case on 64-bit Intel CPUs.

Existing i386 file systems that were built with an older version of OSXFUSE.framework would stop working. They would crash with a segmentation fault as soon as  `valueOfExtendedAttribute:ofItemAtPath:position:error:` or `setExtendedAttribute:ofItemAtPath:value:position:options:error:` are being called.

It all comes down to how the position parameter is passed from OSXFUSE.framework to the file system binary on the CPU call stack. After replacing `off_t` with `uint32_t` OSXFUSE.framework would put a 4-byte value on the call stack. But the file system binary expects to find a 8-byte value on the call stack. This results in a segmentation fault.

**Comment by Asher-** [comment]
Right. I wasn't thinking about how 64-bit machines can still end up with i386 binaries. 

Thanks for the explanation!
