### ISSUE TITLE
[3.1.0] Kernel Panic after reenabling SPI

### ISSUE THREAD

**Issue by omegadreizehn** [osxfuse/osxfuse#262]
Using osxfuse 3.1.0 with ntfs-3g on OSX 10.11.2
After reenabling system protection (csrutil enable) on OSX 10.11.2 I get the following kernel panic at startup:
![img_0164_2](https://cloud.githubusercontent.com/assets/17028550/12755310/2b9299a0-c9cf-11e5-933c-cfcc42a023e9.jpg)
Disabling the system protection again (csrutil disable) didn't change anything. 
System went fine with SPI disabled before. Clearing PRAM didn't help either.
Any help would be greatly appreciated!

**Comment by bfleischer** [comment]
The panic is caused by a kernel extension named `ts.uds.netusb.controller`, which looks like a third-party driver for accessing USB devices over a network. There is no indication osxfuse might be involved or responsible for the panic.

I recommend uninstalling the netusb driver.

As a side note, osxfuse is fully compatible with El Capitan's system integrity protection (SIP) feature. There is no need to disable it. I can't speak for NTFS-3G, though.
