### ISSUE TITLE
Add mount parameter to support more than 24 mount points

### ISSUE THREAD

**Issue by ratson** [osxfuse/osxfuse#277]
As discussed in https://github.com/osxfuse/osxfuse/issues/152, `OSXFUSE_NDEVICES` has limited at most 24 mount points.

It should be configurable, not be a hard limit, as it is not imposed by any system constraints.

**Comment by bfleischer** [comment]
The available RAM is a constraining factor. Depending on the file system and the used iossize a single FUSE volume requires roughly 32 MB of RAM. 64 mounted FUSE volumes require 2 GB or RAM which is half of the available RAM of the current entry level MacBook Air and Mac Mini.

I'm not set on keeping the 24 devices limit but I do not want to raise it too much. How are you using osxfuse and how many simultaneous mounts do you need?

**Comment by ratson** [comment]
Did not know that cost so much memory for each mount, then over a hundred mount points is not realistic for my use case.

In fact, I turned myself to https://github.com/openzfsonosx/zfs and having >80 mount points without problem.

However, a user configurable value may still valuable as some powerful machines therefore won't be restricted.

**Comment by bfleischer** [comment]
In osxfuse 3.3 the number of `/dev/osxfuse` devices has been bumped to 64.

**Comment by z3thon** [comment]
@ratson are the mount points in your system similar to symbolic links in a file system? I know it's been a while since you worked on whatever project it was, but I'm running into the same problem and looking for some solutions. I'm essentially making symbolic links for users and being limited to 64 symbolic links makes scalability difficult.

Was your implementation and use of zfs similar to this? Making symbolic links for users on a system?
