### ISSUE TITLE
Opening volume in Finder is very slow

### ISSUE THREAD

**Issue by ephisino** [osxfuse/osxfuse#289]
I've mounted a fairly large dir.
ls from command line lags a bit but is perfecty usable.
Opening volume in Finder is very slow. Are there options to make browsing sshfs volumes in Finder faster?

**Comment by bfleischer** [comment]
Please do not double-post questions. For questions like this our Google group is the right place.

Depending on the file types, Finder might be trying to generate previews for some of your files. This can take some time because Finder needs to actually download these files. You can try disabling icon previews in Finder. But this is only a wild guess. Without knowing more about your files there is not much to go on here.
