### ISSUE TITLE
Enforce ordering of requests on the same file

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#299]
Hi. Linux has per-directory or per-dentry locking (depending on version), that prevents it from sending e.g. a lookup and unlink for the same name at the same time. OSXFUSE apparently doesn't. I am here to try to convince you it *must*. But first, the evidence:

(in the following, `<-` is request received from kernel, `->` is response written to kernel)

```
 <- Unlink [ID=0x5 Node=0x3 Uid=501 Gid=20 Pid=3009] "a"
<- Lookup [ID=0x4 Node=0x3 Uid=501 Gid=20 Pid=44] "a"
-> [ID=0x5] Unlink
-> [ID=0x4] Lookup 0x11 gen=0 valid=1m0s attr={valid=1m0s ino=13777391486754153034 size=5 mode=-rw-r--r--}
```

So, what we saw there was a lookup for "a" in node 3 while an unlink was in progress. The lookup request was received before the unlink response was written.

Now, you could argue that the app needs to protect against that. While I don't disagree with that -- the FUSE server business logic needs to guard its own data structures -- that won't help here. The userspace FUSE API is callback based, with the response sent to kernel after the callback returns, and potentially multithreaded. This is true for both my Go library and the C library (see e.g. `unlink` at http://libfuse.github.io/doxygen/structfuse__operations.html). And this means the following can happen:

| thread 1           | thread 2              |
|--------------------|-----------------------|
| <- Unlink          |                       |
|                    | <- Lookup             |
|                    | lookup locks          |
|                    | lookup fills response |
|                    | lookup unlocks        |
|                    | kernel switches tasks |
| unlink locks       |                       |
| unlink mutates dir |                       |
| unlink unlocks     |                       |
| -> Unlink          |                       |
|                    | thread wakes up again |
|                    | -> Lookup             |

Now, as far as the FUSE library using app knows, it processed a lookup and then an unlink, while doing its own locking properly. The only way around this would be to send the kernel response before unlocking, but that's impossible with a simple callback-based API.

Linux does read-write locking, that is multiple read-only users, or one mutator, but no other combinations. I think OSXFUSE must, also.

I am relaying this problem to you from a client, after troubleshooting, and don't currently have an easy way to reproduce this problem. If receiving such a program would help you significantly, let me know and I'll write it.

**Comment by bfleischer** [comment]
osxfuse uses exclusive locking for vnodes. Implementing read-write locking is on my todo list but so far I haven't had the time to work on it. But this shouldn't be an issue here.

Race conditions like the one described here are quite common for file systems. Please note that the kernel VFS API is callback-based, too. This means osxfuse cannot guarantee that the unlink call is processed before the lookup, much like your user space file system cannot. There is no guarantee the unlink call reaches the osxfuse VFS plugin before the lookup call, even though the unlink has been issued first. There is task scheduling and other kernel side locking the can "slow“ down the unlink enough, so that it looses the race.

When processing an unlink request osxfuse used to lock only the vnode that is to be removed, not its parent directory vnode. The locking mechanism was inspired by Apple's fallback locking implementation for non thread-safe 32 bit file systems, which doesn't lock the parent directory, either.

However, HFS and NFS lock the vnode itself and its parent directory vnode. While this is not strictly required, it seems to be good practice to do so. Starting with version 3.4.2 osxfuse will lock both the vnode and its parent directory vnode.

This ensures the FUSE user space server does not receive a lookup while it is processing an unlink in the same directory, but the unlink-lookup race might still happen, on a larger scale.

**Comment by tv42** [comment]
> Please note that the kernel VFS API is callback-based, too. This means osxfuse cannot guarantee that the unlink call is processed before the lookup, much like your user space file system cannot. There is no guarantee the unlink call reaches the osxfuse VFS plugin before the lookup call, even though the unlink has been issued first.

Sure, but locking on that level can guarantee *some* order, not concurrent calls. Which one goes first doesn't really matter, as long as either one does.

Thank you!
