### ISSUE TITLE
Bundling FUSE for macOS

### ISSUE THREAD

**Issue by swt2c** [osxfuse/osxfuse#311]
Do you guys have any official recommendations on how to best bundle FUSE for macOS with another application?  Eg, an application that implements and uses a FUSE filesystem?

It seems like the simplest approach might be to just include the official FUSE installer and run it from the application's installer.  However, there is some risk that the user may have other FUSE applications that might change the FUSE installation.

**Comment by tgragnato** [comment]
**I am not one of the developers**

Because of _SIP_, XNU itself puts checks on kexts, all of them must be _signed_.
It's not a good idea to disable this unless required by very specific needs.

Hence **you are forced** to require your users the usage of the official OS X FUSE,
a check on the fuse version can be done at runtime.

OS X FUSE is very stable, I do not see the need to provide fuse right into your app.

If you have a valid key signature, you can hack the source to **embed everything** in your bundle,
if the user use something like sshfs your custom kext could be replaced or generate conflicts with the official one.
As a user I kindly ask you to avoid this path 🙃

Another alternative is "do not use fuse at all", I know at least one example of this: [mc](https://www.midnight-commander.org)
> Midnight Commander is provided with a code layer to access the file system.
This code layer is also known by the name of the virtual file system switch.

Depending on your app, you may develop something like this 😉
