### ISSUE TITLE
iosize=1048576 option is not apply (3.5.2)

### ISSUE THREAD

**Issue by chorogyi** [osxfuse/osxfuse#325]
Sierra update until I have used osxfuse 2.8.2 version.
After an update to the sierra I was updated to osxfuse 3.5.2 version.
but I was experience lowlevel write, read that the buffersize requests only 4Kbyte~64Kbyte.
2.8.2 version can request 1MB buffersize. I modify the FUSE_DEFAULT_BLOCKSIZE the following fuse_param.h. but it does not work properly.
I need help!!

/ *
 * File system interface
 * /

#define FUSE_MAX_UPL_SIZE 8192
 
/ *
 * This is the default block size of the virtual storage devices that are
 * Implicitly implemented by the FUSE kernel extension. This can be changed
 * On a per-mount basis.
 * /

#define FUSE_DEFAULT_BLOCKSIZE 4096
 
#define FUSE_MIN_BLOCKSIZE 128
#define FUSE_MAX_BLOCKSIZE MAXBSIZE
 
/ *
 * This is the default I / O size used while accessing the virtual storage
 * Devices. It can be changed on a per-mount and per-file basis.
 *
 * Nevertheless, the I / O size must be at least as big as the block size.
 * /

#define FUSE_DEFAULT_IOSIZE (16 * PAGE_SIZE)
 
#define FUSE_MIN_IOSIZE PAGE_SIZE
#define FUSE_MAX_IOSIZE (FUSE_MAX_UPL_SIZE * PAGE_SIZE)

/ * User-Kernel IPC buffer * /

#define FUSE_DEFAULT_USERKERNEL_BUFSIZE FUSE_MAX_IOSIZE
#define FUSE_MIN_USERKERNEL_BUFSIZE (128 * 1024)
#define FUSE_MAX_USERKERNEL_BUFSIZE FUSE_MAX_IOSIZE

**Comment by bfleischer** [comment]
Starting with version 3.x the I/O size can be set globally and on a per-file basis. If you set the optimal I/O size (`st_blksize` in `struct stat`) in the getattr callback, `st_blksize` will be used instead of the global I/O size for this particular file. See stat(2) for details on `struct stat`.

Setting `st_blksize` to zero will cause the kernel extension to fall back on the global I/O size. See https://github.com/osxfuse/filesystems/blob/master/filesystems-c/loopback/loopback.c#L67 for details.
