### ISSUE TITLE
fuse_vnop_readdir failed (err=1)

### ISSUE THREAD

**Issue by soleroitsolutionsltd** [osxfuse/osxfuse#353]
Hi 

Not sure it is a major issue but I see a lot of these in my kernal log:

18.01.17 09:00:50.000 kernel[0]: osxfuse: fuse_vnop_readdir failed (err=1)

No immediate / apparent issue though - just wanted to report it.

Fuse 3.5.4 / OSX 10.10.5

**Comment by bfleischer** [comment]
The error message indicates that the file system you were using at that time returned `EPERM` (Operation not permitted) when `readdir` was called. 

FUSE logs this because `ls` ignores/masks errors returned by the file system. You can find a more detailed description of the `ls` issue here https://github.com/osxfuse/osxfuse/issues/265.

The log line has merely an informative character and exists only to let you know why `ls` failed. If you don't see any other issues, like `ls` not working at all, its safe to ignore the log line.
