### ISSUE TITLE
Is auto_xattr not thread safe?

### ISSUE THREAD

**Issue by songgao** [osxfuse/osxfuse#354]
Hi Ben!

We noticed today that downloading from Chrome to KBFS would occasionally fail. It doesn't always happen so I'm not attaching a "steps to reproduce". However, digging through logs we found that this might be due to a potential race condition in `osxfuse`'s handling of `auto_xattr`.

For some reason, Chrome likes to issue some calls multiple times seemingly at the same time, presumably from multiple threads. This is fine on stuff like LOOKUP calls (which did happen on the file name to be saved as), but seemed to be problematic for SETXATTR. We do not have xattr handlers implemented so they always fall back to `osxfuse`'s. We see multiple SETXATTR requests coming in at virtually the same time, on the file (with `.crdownload` suffix) that is being downloaded, and sometimes the second one results in a "file already exists" error in CREATE on the xattr file (with the `._` prefix), which failed the Chrome download. It seems to me there might be a race condition on `osxfuse`'s SETXATTR handler (in kernel presumably) for `auto_xattr`. 

To reproduce it, one needs to issue multiple SETXATTR calls on a file that doesn't have any xattrs set (i.e. no `._` file for it) in different threads. Here a small Go program that does it:

```go
package main

// #include <sys/xattr.h>
// #include <errno.h>
import "C"
import (
	"fmt"
	"log"
	"os"
	"runtime"
	"sync"
)

func test(wg *sync.WaitGroup, fn string) {
	wg.Add(2)
	t := func(i int) {
		ret, err := C.setxattr(C.CString(fn), C.CString("test"), C.CBytes([]byte{1}), 1, 0, 0)
		log.Printf("%s(%d): %2d, %v", fn, i, ret, err)
		wg.Done()
	}
	go t(1)
	go t(2)
}

func fn(i int) string {
	return fmt.Sprintf("ZZZZ%2d", i)
}

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())
	log.Println("creating files ...")
	for i := 0; i < 50; i++ {
		_, err := os.Stat(fn(i))
		if !os.IsNotExist(err) {
			log.Fatalf("%s already exists", fn(i))
		}
		f, err := os.Create(fn(i))
		if err != nil {
			log.Fatal(err)
		}
		if err = f.Close(); err != nil {
			log.Fatal(err)
		}
	}
	log.Println("testing ...")
	var wg sync.WaitGroup
	for i := 0; i < 50; i++ {
		test(&wg, fn(i))
	}
	wg.Wait()
}
```

**Comment by bfleischer** [comment]
When using `auto_xattr` FUSE lets the kernel know that the file system does not support extended attributes natively. The kernel then falls back to using the `._` files. This is actually a kernel feature not a FUSE feature. Sadly this also means that the `._` files are not created by FUSE and that the FUSE kernel extension's *xattr handlers are not called by the kernel. I'll need to check, but I don't think it is possible to add extra locks when using the kernel's fallback mechanism.

**Comment by bfleischer** [comment]
I looked into the kernel's extended attributes fallback mechanism. As far as I can tell the implementation is bullet proof. The kernel performs a lookup to check if the `._` file exists. If it does not it creates the file. Lookup and create are done while holding the lock to the directory vnode. It should not be possible for thread B to create the file between the lookup and create on thread A.

I've not been able to reproduce the issue with your Go program and the loopback file system. Could it be that there is a race condition in your file system implementation?

On which version of macOS did you see the issue? I've tried to reproduce it on macOS 10.12.

**Comment by songgao** [comment]
Hi Ben, I was testing on the osxfuse's loopback: https://github.com/osxfuse/filesystems/tree/master/filesystems-c/loopback . To make sure of this, I just tried it again. It is indeed not reliably reproducible with just 50 runs. But if you increase 50 to 500, it happens much more often. Here's the command I used to run the loopback:

```
2017/02/06 10:16:25 ZZZZ137(1): -1, operation not permitted
```

An example of failure from the Go program is: `2017/02/06 10:11:40 ZZZZ474(2): -1, operation not permitted`. In the log, I can see the second create for the corresponding `._` file fail on "file exists":

```
create flags: 0xa02 /._ZZZZ137 0100644 umask=0000
   unique: 6, error: -17 (File exists), outsize: 16
```

This was done using macOS 10.12.3 (16D32), with osxfuse 3.5.4. Go's version is "go1.8rc3 darwin/amd64".

Could you please try increasing number of tests from 50 to 500? Also I'm sure you know it, but don't forget to remove the `._` files before trying again :-)

**Comment by bfleischer** [comment]
Thanks Song, for posting the exact loopback command. The debug option seem to be key here. I ran the program multiple times (without `-d`) with up to 1000 files without any issues. `-d` make the file system single-threaded and the logs slow down file system operations. With `-d` I'm able to reproduce the issue quite reliably.

**Comment by songgao** [comment]
You are right! Removing `-d` doesn't expose the issue anymore. Based on this behavior, do you think there might still be a race condition in macOS kernel somewhere? Could it be a regression introduced at some point between the source available and the current latest release?

**Comment by bfleischer** [comment]
Sorry for the long wait but this one proves to be tricky. I'm pretty sure the issue is caused by the extended attributes fallback mechanism of the macOS kernel. Running the test program on a FAT formatted volume results in the same errors.

I'm currently looking into a workaround and will get back to you once I know more.

**Comment by bfleischer** [comment]
Commit https://github.com/osxfuse/kext/commit/957441c3e5065233b2b583f6c44915716553a3ba should fix the issue.

The kernel's extended attributes fallback mechanism checks if the `._` file exists and locks the parent directory by calling `namei()` with the `LOCKPARENT` flag set. If the file does not exist it is created and the directory lock is dropped by calling `nameidone()`. This used to work fine for 32 bit file systems.

For modern 64 bit file systems, on the other hand, `LOCKPARENT` is basically ignored. All it does is returning the directory vnode and making sure it is not recycled until `nameidone()` is called. This allows for the  create race you were seeing when setting extended attributes for the same file from multiple threads at the same time.

As far as I can tell the extended attributes fallback mechanism was never updated for the new `LOCKPARENT` behavior. Apple's FAT implementation is prone to the same issue because it relies on the same fallback mechanism. However, file systems supporting extended attributes natively work fine.

To address the issue FUSE will no longer set the `O_EXCL` flag when creating `._` files. This ensures the create operation is not failing in case another thread wins the race.

**Comment by songgao** [comment]
Whoa that's quite an investigation! Thanks a lot for looking into it and working out a solution on FUSE side!
