### ISSUE TITLE
Media type files getting open callback on just folder browse

### ISSUE THREAD

**Issue by Ajaybh** [osxfuse/osxfuse#367]
Hi,

The items that I'm trying to show via Fuse file system contains a **mix of media and document type** items and for some reason when I browse the folder for contents, besides "contentsOfDirectory" fuse layer also keeps posting open/read callback for all the **"media type"** items . The expected behavior is to "NOT get open/read callback until user clicks on the item". The document type items behave as expected. 

For more clarity, I am attaching the modified version of LoopBackFS project and also a mix set of items(images & doc type). Please try to open the folder "HasTextAndImage" with LoopBackFS app.

I'm not sure if this is an issue or as designed behavior, so just wanted to get a confirmation.

Thanks!,
Ajay

[filesystems-swift.zip](https://github.com/osxfuse/osxfuse/files/868374/filesystems-swift.zip)

**Comment by bfleischer** [comment]
You can find out the PID of the process which performed the open and read file system operations by calling +[GMUserFileSystem currentContext] and logging the value for kGMUserFileSystemContextProcessIDKey in your open handler.

FUSE relays file system operations from other processes to your file system implementation, it does not generate operations on its own. I think Finder might be responsible for the open/read calls you are seeing. In order to generate preview icons Finder needs to open the corresponding files.

**Comment by Ajaybh** [comment]
Thanks Benjamin for your quick response. I couldn't reply earlier because I was out sick. 

Unfortunately, processID is also not sufficient to distinguish between user initiated operation or OS triggered automatic request. I'll keep investigating it further.

Thanks again and really appreciate all the great work done here.
