### ISSUE TITLE
sshfs volname option not working with osxfuse 3.5.4+

### ISSUE THREAD

**Issue by pjv** [osxfuse/osxfuse#375]
I recently upgraded osxfuse from version 3.5.3 to 3.5.8. Since that upgrade, when mounting remote file systems with sshfs (version 2.9), the `-o volname=X` option for sshfs is no longer working. The mounted volume gets the basename of the remote directory.

I finally got around to looking into this and started downloading releases one by one. It turns out that the problem starts in 3.5.4. So `volname` works in 3.5.3 but not in 3.5.4+.

This is with sierra v. 10.12.4.

**Comment by bfleischer** [comment]
The `volname` option works fine for me with FUSE for macOS 3.6.0 and SSHFS 2.5.0 on macOS 10.12.5. Can you still reproduce the issue with the latest version for FUSE?

**Comment by pjv** [comment]
Upgraded to FUSE 3.6.0, same behavior with SSHFS v. 2.9.0. Tried downgrading to SSHFS v. 2.5.0 and still see the same behavior. Rather than mounting the network volume with the `volname` specified in the sshfs command line, it mounts it using the directory name on the remote host.

Are you also using the `local` mount option to get `volname` to work? It works for me with `local` but I'd prefer not using `local` and I didn't used to have to specify that mount option.

**Comment by bfleischer** [comment]
I'm not using the `local` option, `volname` is the only option. Can you post the exact sshfs command you are using?

**Comment by pjv** [comment]
`sshfs pjv@host.example.com:/home "/Users/pjv/sshfs_mounts/host/host_home" -o volname=host_home`

Results in a mounted directory called `home`.

Expecting (and used to get) a mounted directory called `host_home`.

**Comment by bfleischer** [comment]
Can you try mounting the volume in `/Volumes`?

**Comment by pjv** [comment]
Can you show me a sample command line to do that? Do I have to sudo mkdir the `/Volumes/dir` into existence first and then `sudo sshfs ...` or what?

**Comment by bfleischer** [comment]
Using the following commands the SSHFS volume shows up under the name "hello" in Finder. Not sure if it matters but the server is running macOS 10.12.

```
$ sudo mkdir /Volumes/sshfs
$ sudo chown benjamin:staff /Volumes/sshfs/
$ sshfs benjamin@172.16.115.1:/Users/benjamin/Desktop/test /Volumes/sshfs/ -ovolname=hello
```

**Comment by pjv** [comment]
Thanks. 

`➤ sudo mkdir /Volumes/sshfs`
`➤ sudo chown pjv:staff /Volumes/sshfs/`
`➤ sshfs pjv@host.example.com:/home /Volumes/sshfs -ovolname=hello`

For me the volume still mounts as `home` in Finder. In my case the server is a linux VPS but it's hard to imagine that matters.

FWIW, I've been mounting these remote directories on my mac via FUSE and SSHFS for years with no issue. Only after some recent upgrades has the `volname` mount option stopped working for me.

**Comment by bfleischer** [comment]
FUSE 3.x does not contain any code that would allow changing the name of the volume after mounting it. Most importantly between 2.5.3 and 3.5.4 only 6 lines of code have changed in the FUSE kernel extension (above you stated that the issue started with 3.5.4). Those changes have noting to do with the volume name.

You seem to be the only one having this issue. This leads me to believe that it is most likely somehow related to your setup. Can you try mounting a different server directory (e.g. /tmp) or do you have access to another server?

**Comment by pjv** [comment]
Mounting /tmp also shows up in the finder as `tmp`.

I run around a dozen different linux servers for various purposes. They all show the same issue. They are all ubuntu with versions ranging from 12.04 to 17.04.

I'm sure you are right it must be something in my setup. Maybe something else I have installed is having some interaction with FUSE or SSHFS or Finder? I wish I could think of a way to determine what it might be.

**Comment by pjv** [comment]
OK, here's something weird. A second reboot after upgrading FUSE to 3.6.0 and downgrading sshfs to 2.5.0 seems to have solved it. Now `volname` is working properly for me again. How the original reboot didn't do it is hard for me to understand.

I'll close this and hope that it stays closed. Thanks for your help @bfleischer. Is there a reason that you run `sshfs` v. 2.5.0 rather than the newer version (currently @ 2.9.0) maintained at https://github.com/libfuse/sshfs?

**Comment by waxxmaster** [comment]
Hi, i got the same random issue with FUSE 3.7.1 and SSHFS 2.5.0 under macOS 10.13.4 , i'm using sshfs for years, and this is the first time i got this problem (new computer, with fresh macOS 10.13.4)

I'm using the following commands :

umount -f /Volumes/ssh_cesium
sudo mkdir -p /Volumes/ssh_cesium
sudo chown ${USER} /Volumes/ssh_cesium
sshfs -o reconnect -C -o workaround=all -o IdentityFile=~/.ssh/id_rsa -o no_readahead,noappledouble,nolocalcaches mediacell@cesium.mediacell.fr:/home/mediacell/ /Volumes/ssh_cesium/ -o volname=cesium 

Most of the time In the finder it is mounted as "mediacell" , not "cesium", but not always, sometime it works. i've to restart 5 or 6 times the script to obtain the expected behavior.

**Comment by wouthezx** [comment]
I have this same issue where the mounted volume gets thebasename of the remote directory, and the volname is ignored. Very very very rarely it does show the specified volname. I'm on High Sierra 10.13.6 which means i cant go back any further than osxfuse 3.6.0 because lower versions give me a message that the version is too old for the OS. The earlier mentioned 3.6.0 with sshfs 2.5.0 didnt work either, even after several reboots. I tried all versions even the currently latest (3.8.2). I dont use the local option.

I suspect its something on my mac that's causing problems. I tried uninstalling Chrome but that didnt solve it. If someone knows the solution I'd love to hear because this is driving me crazy!
