### ISSUE TITLE
Provide file integrity assurance for releases

### ISSUE THREAD

**Issue by andrewtchin** [osxfuse/osxfuse#376]
Please provide these enhancements to the release process:
- [x] Publish an OpenPGP key used to sign releases 
- [x] Publish an OpenPGP signature with each release
- [x] Publish SHA256 sum of each release file on the Github release page

**Comment by bfleischer** [comment]
Thanks for your suggestion.

Starting with version 3.6.0 official FUSE for macOS releases will be signed with the following OpenPGP key: [0093B21EF45D635284F6A14753C918C1A2818875](https://sks-keyservers.net/pks/lookup?op=vindex&search=0x0093B21EF45D635284F6A14753C918C1A2818875)

You can find the signed sha256sum file on the GitHub release page.

**Comment by andrewtchin** [comment]
Awesome thank you! 👍

**Comment by stysedo** [comment]
Doesn't the current use of an Apple DeveloperID signature of the installer and its components achieve  the same thing?

**Comment by bfleischer** [comment]
> Doesn't the current use of an Apple DeveloperID signature of the installer and its components achieve the same thing?

For previous versions of FUSE you would need to open a potentially malicious disk image to verify the signature of the FUSE installer package. In theory, opening such a disk image could already trigger a zero-day exploit and compromise your Mac. Another problem is that an attacker could add or remove files from the disk image since the disk image as a whole is not signed by the Developer ID certificate.

Signing the release files (disk image and debug symbols archive) adds another layer of security. It is now possible to verify the integrity of new FUSE releases without needing to open them first. In addition to that all commits and tags in the FUSE Git repository will be signed from now on. This makes sure that even if an attacker manages to gain push access to the official repository he won't be able to modify FUSE without being detected.

After what happened to Handbreak a few weeks ago I think it is best to error on the side of caution.

**Comment by andrewtchin** [comment]
@bfleischer Thank you for putting this in - your project is an required for use of Veracrypt on macOS which makes the integrity of this project very important.
