### ISSUE TITLE
Building on macOS 10.12.4 Xcode 8.3.2 with Command Line Tools installed error

### ISSUE THREAD

**Issue by therealjimwolff** [osxfuse/osxfuse#377]
OSXFUSE 3.5.8 - Followed all the instructions, and have all the brew stuff installed...

When I:

./build.sh -t distribution

I get

No version of Xcode found

Any thoughts?

macOS 10.12.4
Xcode 8.3.2 installed with Command Line Tools installed
All the brew stuff installed and built

--Thanks

**Comment by therealjimwolff** [comment]
Never mind lol. Getting farther using 


sudo ./build.sh -t distribution

**Comment by swt2c** [comment]
I have run into this problem a few times recently too.  It seems to happen after an Xcode update.  The root cause appears to be that this command in `build.d/lib/xcode.sh` returns nothing:

```
mdfind -onlyin "/Applications" 'kMDItemCFBundleIdentifier == "com.apple.dt.Xcode"'
```

See also:
```
$ mdls -name kMDItemCFBundleIdentifier /Applications/Xcode.app
kMDItemCFBundleIdentifier = (null)
```

I am not sure what's really at fault here.  I have been working around this by either manually setting the kMDItemCFBundleIdentifier on Xcode, or rebuilding Spotlight indices by `sudo mdutil -E /` and `sudo mdutil -i on /`.
