### ISSUE TITLE
`df` shows incorrect space on osxfuse device

### ISSUE THREAD

**Issue by misku** [osxfuse/osxfuse#396]
Hi Benjamin,
I got into a problem where `df` is showing wrong size/used/avail/capacity for osxfuse volumes. I've used loopback filesystem to reproduce the issue:
```
Filesystem                Size   Used  Avail Capacity      iused        ifree %iused  Mounted on
//myhost/some_vol         639Ti  417Ti  222Ti    66% 448039743486 238580174848   65%   /Volumes/some_vol
loopback@osxfuse0         3.5Ti  1.3Ti  2.2Ti    37%   1363144702   2356973568   37%   /Volumes/loopback
```

The problem is a result of a large volume and Apple's implementation of some types.

`fuse` uses `struct statvfs *` to return stats about the filesystem: [src](https://github.com/osxfuse/fuse/blob/support/osxfuse-3/include/fuse.h#L212) and forces the author of the file system to fill out `struct statvfs` values. This makes sense, because `statvfs` is POSIX compatible and uses [standardized data structure](http://man7.org/linux/man-pages/man3/statvfs.3.html).

Everything is nice on Linux, because `fsblkcnt_t` type (used by  `f_blocks`, `f_bfree`, `f_bavail`) is implemented as `unsigned long` (8 bytes). However on macOS (at least in 10.10 SDK) `fsblkcnt_t` is an `unsigned int` (4 bytes) (because Apple!).

With large volume sizes and not so large block sizes, `f_blocks` is not able to fit the whole value on 4 bytes and I get garbage result. I've seen that fuse moved from `statfs` to `statvfs` since version 2.5 [src](https://github.com/osxfuse/fuse/blob/support/osxfuse-3/include/fuse.h#L210). Unfotunately when I look at commit history, most of the commit messages are "fix". Is it possible for you to point me to this commit? Maybe you already went through them before.

What is interesting `df` is showing proper values for the original volume. I made `statvfs` and `statfs` calls on it and `statvfs` results in the same crappy values, so I'm guessing that `df` uses `statfs` as a fallback.

Do you have any ideas how to approach this problem until Apple gets smarter? For now mine are:
* Change the fuse back to using `satfs` instead of `statvfs` (this is risky, time-consuming, and error-prone as including old headers may break some new fuse code),
* Inside own `filesystem_statfs()` get `statfs` values from the original mount, bump `f_bsize` and recalculate the rest, so that values fit inside 4 bytes (this may have unexpected results in applications that are using the volume).

Thanks for your intput!

**Comment by misku** [comment]
Also checked 10.12 SDK. Still the same: `fsblkcnt_t` is `unsigned int` 😞

**Comment by bfleischer** [comment]
Hi @misku,

Sorry for the late reply. I've busy working on some other stuff.

You are right, Apple's use for 32 bit integers is the limiting factor here. Sadly it's not possible to change the FUSE statfs() callback without breaking backward compatibility (or compatibility with standard Linux FUSE file systems).

It's certainly not ideal but I think the best approach would be to add a statfs_x() callback (similar to the setattr_x() callback) that uses a 64 bit data structure. libfuse would fall back to the standard statfs() callback in case the fie system does not implement statfs_x(). I'll look into this.

PS: Could you please contact me over email? My email address is fleiben@gmail.com. I would like to make a proposition but could not find your email address anywhere. Since we both seem to be from Germany, German would be fine 😀

**Comment by bfleischer** [comment]
Commit https://github.com/osxfuse/fuse/commit/e35c5797224454205fcd97b5c1eeeafffd3ee6f4 adds support for very big low-level file systems. Are you using the low-level API or the high-level API?

**Comment by misku** [comment]
Nice change, yet I'm using high-level API.

**Comment by misku** [comment]
Tested. It works with big ass file systems.

**Comment by bfleischer** [comment]
Thanks. I did a little refactoring (removed the statfs_x_ok flag) and added support for OSXFUSE.framework.

**Comment by misku** [comment]
I've seen the clean up code. Thank you for your help.
