### ISSUE TITLE
Size of filesystem reported with 0 on macOS 10.13 GM and osxfuse 3.7.0

### ISSUE THREAD

**Issue by Bleistein** [osxfuse/osxfuse#414]
On macOS 10.13 Beta (17A362a) bindfs 1.13.7 will report a capacity of 0 of the mounted filesystem when used with osxfuse 3.7.0. The mount point filesystem is APFS.

Rolling back to osxfuse 3.6.3 shows the correct filesystem sizes again.

**Comment by bfleischer** [comment]
Can you reproduce this issue with the loopback file system?

**Comment by paaguti** [comment]
Same here with ntfs-3g on macOS 10.12.6. reverting to 3.6.3 corrects the
issue (at least for me TM)

BR, /Pedro A. Aranda

El 19 sept. 2017 9:13, "Michael Bleistein" <notifications@github.com>
escribió:

On macOS 10.13 Beta (17A362a) bindfs 1.13.7 will report a capacity of 0 of
the mounted filesystem when used with osxfuse 3.7.0. The mount point
filesystem is APFS.

Rolling back to osxfuse 3.6.3 shows the correct filesystem sizes again.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/osxfuse/osxfuse/issues/414>, or mute the thread

**Comment by mpartel** [comment]
bindfs's statfs impl doesn't differ much from the loopback one: https://github.com/mpartel/bindfs/blob/master/src/bindfs.c#L1147 where `process_path` returns a path relative to bindfs's working directory, which is the source directory.

@Bleistein does this also happen when the source and destination directories are different (i.e. `bindfs /foo /bar` instead of `bindfs /foo /foo`)?

**Comment by Bleistein** [comment]
We where testing under our user home with something like "bindfs ~/a ~/b"...

**Comment by Bleistein** [comment]
We compiled the current repository "c" version of the loopback filesystem. It shows exactly the same behaviour as bindfs...

**Comment by Nizarius** [comment]
macOS 10.12.6, osxfuse 3.7.0 - the same problem as described above.

**Comment by dstyp** [comment]
Same here. macOS 10.12.6 after updating to osxfuse 3.7.0

**Comment by bfleischer** [comment]
This issue affects file systems that are using the high-level C API and FUSE modules. I'm currently testing a fix.

**Comment by bfleischer** [comment]
The new 3.7.1 release (https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.7.1) should fix this. Could you give it a try?

**Comment by LRDN** [comment]
Many thanks. Works perfectly with macOS 10.12.6 and SSHFS 2.5.0 now.

**Comment by bfleischer** [comment]
Thanks to everyone who reported the issue and @LRDN for testing the new release.
