### ISSUE TITLE
SpaceMonkey / High Sierra: "Installed version of macOS unsupported"

### ISSUE THREAD

**Issue by oschettler** [osxfuse/osxfuse#422]
FUSE for macOS 3.7.1
Space Monkey 0.7.26

After upgrade to macOS High Sierra (and upgrading osxfuse to 3.7.1), when starting SpaceMonkey, I get a dialog box that says

````
The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.
````

**Comment by swt2c** [comment]
Does Space Monkey use the unmodified osxfuse distribution?  If not, you will have to obtain support from them.

**Comment by IgorNav** [comment]
FUSE for macOS 3.7.1
After upgrade to macOS High Sierra, when the system starting there are 3 messages same like oschettler wrote: The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.

**Comment by bfleischer** [comment]
Official FUSE for macOS releases are compatible with High Sierra since version 3.6.0, which was released on June 13. 

@oschettler Space Monkey probably contains a custom version of FUSE that is not up to date or you are using an unofficial FUSE for macOS build. Can you send me a download link for Space Monkey?

@IgorNav Which FUSE based application are you using?

**Comment by IgorNav** [comment]
For now I just installed MacOS high sierra and when it started there are 3 messages appear with this info: The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS. Version of FUSE is 3.7.1 How can I know which FUSE based application I'm using?

**Comment by IgorNav** [comment]
Also could you tell me please how can I delete FUSE permanently?

**Comment by swt2c** [comment]
@IgorNav you will have to figure out which FUSE-based applications you have installed.  Run
`ls -l /Library/Filesystems` from a terminal and report the results.

**Comment by IgorNav** [comment]
Last login: Wed Sep 27 22:49:04 on console
MacBook-Air-IgorMac:~ igormac$ ls -l /Library/Filesystems
total 0
drwxr-xr-x  2 root  wheel  64 15 июл 23:38 NetFSPlugins
drwxr-xr-x  3 root  wheel  96 19 фев  2016 fusefs_txantfs.fs
drwxr-xr-x  3 root  wheel  96 21 сен 09:11 osxfuse.fs
drwxr-xr-x  3 root  wheel  96  6 июн 07:46 strongfuse.fs

THATS IT

**Comment by bfleischer** [comment]
@IgorNav You have three versions of FUSE:

* osxfuse.fs is FUSE for macOS
* strongfuse.fs is an unofficial FUSE fork maintained by the ExpanDrive team
* fusefs_txantfs.fs is a custom version FUSE that is installed by Tuxera NTFS for Mac

It might be best to start by checking if your versions of Tuxera NTFS for Mac and ExpanDrive are outdated. If so update to the latest version.

If you want to remove the official FUSE release (osxfuse.fs) please follow the instructions in the wiki: https://github.com/osxfuse/osxfuse/wiki/FAQ#23-how-can-i-uninstall-fuse-for-os-x
For the other two FUSE installations you need to get in touch their respective maintainers, ExpanDrive and Tuxera.

**Comment by IgorNav** [comment]
Many thanks!!!

**Comment by inwardgarden** [comment]
Apparently file transfer software Transmit 5 must contain it's own version of FUSE as well. Any time I try to use Transmit Disk I get an incompatibility error, and I have 3.7.1 installed. More than likely will require an update from Panic Software themselves to resolve.

**Comment by bfleischer** [comment]
@bscottx Yes, Panic uses a custom version of FUSE for Transmit Disk. I have not verified this, but judging from the change notes the latest version of Transmit is supposed to work on High Sierra. If you already have the latest version you need to get in touch with Panic. 

It would be so much easier if everyone were using the official FUSE release instead of shipping their own version.

**Comment by btamayo** [comment]
@bscottx @bfleischer Transmit 5 itself does support High Sierra (10.13), but Transmit Disk's kernel extension (MacFUSE) seems to have trouble with it.


> Transmit Disk is not currently compatible with High Sierra. The new OS breaks compatibility, we’ll be working on a fix. ([Source](https://library.panic.com/transmit5/transmit-disk/#is-transmit-disk-supported-in-high-sierra-10-13))

[The technical details](https://library.panic.com/transmit5/transmit-disk/#technical-details-and-the-future-of-transmit-disk) didn't seem clear to me whether MacFUSE works with High Sierra or if they decided not to enable it at all. It does ship with Transmit Disk 4, which probably is what conflicts with osxfuse. This article explains how to download and install osxfuse (perhaps remove their kernel extension first). I'm still on 10.12, so I can't verify. Sorry!

**Comment by pmalhaire** [comment]
@btamayo It seams clear in the link you shared that Transmit itself needs to be remade. It does not seam to be related to Osxfuse at all or their own fork is doomed. 
Osxfuse is used in many projects that require small latency.
This confirms what's bfleicher is saying, you have to contact them.

**Comment by inwardgarden** [comment]
Yeah, I did contact them and got the above response posted by btamayo (and Transmit 5 itself works fine, it's specifically Transmit Disk which I forgot is a separate app that hooks into Transmit 5, not PART of Transmit 5).

They are re-architecting Transmit Disk completely for 10.13 apparently due to some other things they are having to change too. I just happened to notice the error (which I think mentioned OSXFuse by name) whenever attempting to use Transmit Disk and this was a thread that came up in my search after I had tried updating OSXFuse on my machine, which I also use for other purposes.

Thanks for the responses. It's all up to Panic to fix Transmit Disk. Sorry if I was adding noise to the signal here, I should have contacted Panic / searched their KB first.

**Comment by peterbaral** [comment]
This is a fix for Expandrive 5.5.x on Mac OS X 10.13 High Sierra:

0) Quit Expandrive
1) Install current version of OSXFuse from https://osxfuse.github.io
2) Go to /Library/Filesystems on your Mac
3) Rename Expandrives custom version of OSXFuse from strongfuse.js to _strongfuse.js (to save it)
4) Symlink osxfuse.fs to strongfuse.fs
5) Launch Expandrive

**Comment by veloper** [comment]
@peterbaral - This totally works with Transmit 4 as well! 

Edit: Never mind, it sort-of worked but i ran into another issue within transmit 4 itself.

**Comment by bjornbennett** [comment]
@veloper how did you make it work for Transmit 4?

**Comment by veloper** [comment]
@bjornbennett - I'm sorry to say that it did __NOT__ actually work after all. I'll edit my comment, sorry for the false hope :(

**Comment by bjornbennett** [comment]
@veloper haha thanks for at least letting me know!
