### ISSUE TITLE
How can I to format to NTFS?

### ISSUE THREAD

**Issue by aronkihui** [osxfuse/osxfuse#428]
How can I to format to NTFS file system? Is it possible?

**Comment by bfleischer** [comment]
FUSE is basically a library that is used as a building block for many different file systems. NTFS-3G is one of those file systems. It lets you write data to NTFS volumes and it allows you to format a volume to NTFS.

Please note that NTFS-3G and FUSE for macOS are independent projects. For details and instructions on how to use NTFS-3G please refer to the NTFS-3G project. Should you run into NTFS-3G related issues please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.

You can find installation instructions for NTFS-3G on the following wiki page: https://github.com/osxfuse/osxfuse/wiki/NTFS-3G

**Comment by aronkihui** [comment]
O... sorry for duplicate. It was a mistake. Sorry. -_-

**Comment by aronkihui** [comment]
This is my last question, I swear.  "It lets you write data to NTFS volumes and it allows you to **format** a volume to NTFS"  the point is I can't get any info about how to format to NTFS using Fuse. :(. Can it format to NTFS a volume actually?

**Comment by bfleischer** [comment]
Like I wrote before, FUSE is only the building block. It is used for countless third-party file systems. NTFS-3G is one of those third-party file systems. FUSE on its own cannot format volumes to NTFS, but NTFS-3G can.

I haven't used recent versions of NTFS-3G, so I cannot give you a definitive answer. That's why I recommended asking the NTFS-3G team for help. As far as I know you can use the `mkntfs` command line tool (that is part of NTFS-3G) to format a disk to NTFS.

**Comment by jbarros35** [comment]
the easier solution should install windows via bootcamp.
