### ISSUE TITLE
High serria 

### ISSUE THREAD

**Issue by qolson11** [osxfuse/osxfuse#429]
Just upgraded to high sierra version 10.13 (17A365)
and lost my NTFS write support, how do i fix it. is it the same way as pervioues where its fixed thru the recovery terminal.
Sorry if this has been asked b4.

**Comment by bfleischer** [comment]
First of all you should make sure you have the latest versions of FUSE and NTFS-3G. You can find installation instructions for NTFS-3G on the following Wiki page: https://github.com/osxfuse/osxfuse/wiki/NTFS-3G

If it still does not work, please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7. I don't know if there are any NTFS-3G compatibility issues with High Sierra. FUSE supports High Sierra since version 3.6.0.

**Comment by zhudhjen** [comment]
I encountered a problem when installing NTFS-3G 2017.3.23 with HomeBrew on macOS 10.13. Compilation failed due to a change of `struct stat`.

**Comment by qolson11** [comment]
wait is needing nfts-3g a new thing, cause i cant remember needing that in older versions. is it because of the new file system BS the apple is doing with high serria

**Comment by bfleischer** [comment]
@zhudhjen Please report the issue to the Homebrew team. I did not run into any issues installing NTFS-3G on High Sierra.

@qolson11 NTFS-3G has always been required if you want to edit files on or copy files to NTFS volumes. This has nothing to do with Apple's new default file system APFS. FUSE is a building block that is used by third-party file systems like NTFS-3G.

**Comment by qolson11** [comment]
@bfleischer oh, i guess iv just forgotten that i havent needed to modify anything since the original serria beta last year
