### ISSUE TITLE
Notify osxfuse for external change, using the high-level API

### ISSUE THREAD

**Issue by kiril-kirov** [osxfuse/osxfuse#441]
Hello, 

We have implemented a distributed file system, using the high-level API of osxfuse. But now we have a situation. Is there _any_ way to notify the high-level API for external changes? 

It looks like we need `fuse_lowlevel_notify_*` functions, but can we use then in _any_ way with the high-level API? 
Any approach will be highly appreciated - could even be a short-term solution (or a hack) until we switch to the low-level API (if necessary).

Thank you in advance!

Best Regards, 
Kiril

**Comment by mixtly87** [comment]
Workaround I practice: if I want to notify VFS new file/folder is created/deleted/renamed/updated... I always go through loop where SyncEngine invokes file-system operation on VFS as 3rd party client. Example of remotely uploaded file:
1. remote change is detected in SyncEngine via pulling (ie every 5 seconds)
2. SyncEngine informs the VFS about a change (invokes `NSFileManager.createFileAtPath(...)` and before that it flags the file in database as 'timelineCreated=true'
3. On fuse callback `createFileAtPath`, if a file for given path exists in DB and is flagged as 'timelineCreated=true', a dummy file descriptor is created and set to *userData and YES is returned as a result from createFileAtPath. Also timelineCreated=true is set to false since case has been resolved.
After that finder will assert file has been created by invoking `attributesForItem` and file will happily appear in Finder with animation.

Other option would be to use `NSWorkspace.noteFileSystemChanged` but that is discouraged by Apple and sometimes results in weird behavior (broken animations and 3rd party apps which rely on FSEvents don't detect a change as with previous approach).

Instead of flagging 'timelineCreated=true' for every change, you can also query in FUSE callback if a process which is trying to update your VFS is your app (by checking the PID in `GMUserFileSystem.currentContext`, and if that turns out to be the case, you know it's a remote update and you can handle it accordingly.

I'm not sure if this is the right way to go at all, but it seems to work ok for my SyncEngine so far.

**Comment by bfleischer** [comment]
Has been addressed a long time ago, so I'm closing the issue. `fuse_invalidate_path()` is the function to use.
