### ISSUE TITLE
Failed to parse version of Xcode at path '/Developer'

### ISSUE THREAD

**Issue by webgast** [osxfuse/osxfuse#461]
Hi, I updated to OSX 10.13 today and noticed my Mac Fuse was no longer working. Tried this version, but when building, I get this error:

```
Failed to parse version of Xcode at path '/Developer'
T:distribution       | Clean target
T:distribution       | Build target for macOS 10.13
T:fsbundle           | Clean target
T:fsbundle           | Build target for macOS 10.13
T:kext               | Clean target
T:kext               | Build target for macOS 10.13
T:kext               | Install target
T:fsbundle           | Install target
T:library            | Clean target
T:library            | Build target for macOS 10.13
T:library            | Failed to make configuration
Terminated: 15
```

Please help!

**Comment by webgast** [comment]
I have tried reindexing spotlight, to no avail:

https://github.com/osxfuse/osxfuse/issues/310

`sudo mdutil -i on /`

**Comment by webgast** [comment]
After reindexing, I tried the ./build.sh -t distribution as sudo, which seemed to do a bit more:

```
Failed to parse version of Xcode at path '/Developer'
T:distribution       | Clean target
T:distribution       | Build target for macOS 10.13
T:fsbundle           | Clean target
T:fsbundle           | Build target for macOS 10.13
T:kext               | Clean target
T:kext               | Build target for macOS 10.13
T:kext               | Install target
T:fsbundle           | Install target
T:library            | Clean target
T:library            | Build target for macOS 10.13
T:library            | Install target
T:framework          | Clean target
T:framework          | Build target for macOS 10.13
T:framework          | Failed to build target
Terminated: 15
```

note, there IS a directory /tmp/osxfuse/distribution

**Comment by webgast** [comment]
Hm, just installing the .dmg 3.7.1 solved everything for me:

https://github.com/osxfuse/osxfuse/releases

**Comment by webgast** [comment]
Hi @bfleischer why did you close this? I am still intrigued why this build did not work for me, do you have any idea?

**Comment by bfleischer** [comment]
I don't recommend building FUSE yourself because you would need a Developer ID certificate for signing kernel extensions to do so. This is not the standard Developer ID certificate every registered Apple developer gets. For singing kernel extension you need to apply for a special special certificate. If you don't have such a certificate you would need to disable macOS's System Integrity Protection to load the kernel extension. This would be a security risk. The binary releases, on the other hand, are properly signed and don't require security features to be disabled.

If you still want to build FUSE yourself, please follow the instructions in the README.md file. It looks like you did not install the required tools autoconf, automake, libtool, and gettext.

If you run the build script with `-v 5` you get a more verbose log that might help you track down the issue. However, you don't need to run the build script with sudo. In fact the build script was specifically designed so that it does not need elevated privileges.

**Comment by webgast** [comment]
Hi,

Thanks! I now have the problem that I can see the files in the command line
and in an editor but not in Finder. Do you know what could be wrong?

I need it for work :/

Cheers,

Johan
