### ISSUE TITLE
macOS 10.13 - T:framework | Failed to build target

### ISSUE THREAD

**Issue by shelbyKiraM** [osxfuse/osxfuse#462]
```
~/github/osxfuse support/osxfuse-3 $./build.sh -t distribution
T:distribution       | Clean target
T:distribution       | Build target for macOS 10.13
T:fsbundle           | Clean target
T:fsbundle           | Build target for macOS 10.13
T:kext               | Clean target
T:kext               | Build target for macOS 10.13
T:kext               | Install target
T:fsbundle           | Install target
T:library            | Clean target
T:library            | Build target for macOS 10.13
T:library            | Install target
T:framework          | Clean target
T:framework          | Build target for macOS 10.13
T:framework          | Failed to build target
Terminated: 15
```

Where to go from here?

**Comment by bfleischer** [comment]
You can increase the verbosity by running the build script with `-v 5`. 
    
    ./build.sh -v 5 -t distribution

macOS 10.13 contains a broken version of the `gen_bridge_metadata` tool needed to build BridgeSupport for the FUSE framework. For details see #416. You can fix this by running the following command in Temrinal:

    ln -s XcodeDefault.xctoolchain /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.13.xctoolchain

However, I recommend using the latest binary release from https://github.com/osxfuse/osxfuse/releases instead of building FUSE yourself.

**Comment by shelbyKiraM** [comment]
Trying to build cuz of these errors from TransmitDisk using FUSE 3.7.1:

- https://www.dropbox.com/s/olnuxvt57u82vzx/Screenshot%202017-12-12%2015.16.45.png?dl=0
- https://www.dropbox.com/s/xawppip11j6dm5c/Screenshot%202017-12-12%2015.16.56.png?dl=0

**Comment by bfleischer** [comment]
As far as I know TransmitDisk uses a custom version of FUSE. It might be best to get in touch with Panic to resolve this issue. You might need to upgrade TransmitDisk.

**Comment by shelbyKiraM** [comment]
Ah. Closing, and going to them. Thanks.
