### ISSUE TITLE
FUSE Stopped Working After Upgrade to 10.13.2

### ISSUE THREAD

**Issue by SPFPDX** [osxfuse/osxfuse#469]
I've been using FUSE for almost a year to access network drives at work, which use NTFS. Since updating from MacOS 10.13.1 to 10.13.2, I have encountered difficulties. While I can mount the drives, copy to them, copy out of them, and open files from them, I am unable to manipulate files on the drives. Attempting to move a file or folder into another folder, or renaming a folder or file results in a hard crash. I have to hold down the power button to shut down.

I've read that 10.13.2 attempts to address the Meltdown security risk and I wonder if this as caused FUSE to malfunction.

**Comment by gprakash1** [comment]
Even I am facing the same issues after updating to 10.13.2, SD cards not readable now. Will there be a fix released soon?

**Comment by gudstrand** [comment]
I am also seeing issues.  I am trying to mount disk and am getting an error that the MacFUSE does not support the version of Sierra (10.13.2) that I am using.  This is a real pain, any ETA on when this may be addressed?   Is this being worked on?

**Comment by SPFPDX** [comment]
I ended up starting an Apple ticket which escalated to senior advisor and then engineers. They suggested upgrading to 10.13.3, which was released in the meantime. This fixed my problem. I'm no expert, but I've been told that the native MacOS should be able to access _network_ drives that are using NTFS. Accessing drives physically connected to the Mac is different. Whatever, try upgrading to 10.13.3.

**Comment by bfleischer** [comment]
Let me start by saying that FUSE for macOS is compatible with macOS 10.13 and has been since macOS 10.13's release last year. FUSE is a building block, that is used by third-party developers to build actual file systems. NTFS-3G is such a file system. 

While FUSE is compatible with macOS 10.13 the particular third-party file systems you are using might not be. 

@gudstrand Please make sure to use the latest version of FUSE. FUSE for macOS 3.6.0 and later are compatible with macOS 10.13. Which file system are you using?

@gprakash1 Wich file system are you using? I'm assuming that your SD card is NTFS formatted. Is this correct? If so you need to get in touch with the actual developer of the file system you are using. In case of NTFS-3G, this would be Tuxera. Please note that NTFS-3G and FUSE are actually two separate projects.

@SPFPDX It sounds like you are using some sort of network file system. Which file system are you using? The issue you are describing needs to be investigated by the actual developer of the file system you are using. I doubt Meltdown has anything to do with this.

**Comment by SPFPDX** [comment]
Thanks to bfleischer for responding. I am rather naïve about all this. But my understanding is that my office network is a Windows server and the developer of NTFS is Microsoft. I'm not sure the FUSE was involved at all (even though that was what the high-level Apple consultant thought at first. Apparently MacOS can access network NTFS servers natively. Clearly, in retrospect, MacOS 10.13.2 caused problems with such access and 10.13.3 fixed it. No one at work knows why my work Mac has FUSE or what it does. On my home Mac I find that I have both MacFUSE and FUSE. I must have acquired them at some point for some reason. Bottom line is my problem is solved without any change in FUSE.

**Comment by bfleischer** [comment]
@SPFPDX Thanks for clearing things up. You are right, you only need FUSE and NTFS-3G to access NTFS disks that are attached to your Mac via USB or Thunderbolt.

**Comment by bfleischer** [comment]
Since there has not been any further feedback in months I'm going to close the issue.
