### ISSUE TITLE
Internal FUSE error (rc=1)

### ISSUE THREAD

**Issue by raycasanova43** [osxfuse/osxfuse#493]
Unable to mount Egnyte Connect due to the following error:

"Mount Failed
Internal FUSE error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error message using Console."

I've uninstalled/re-installed macOS X FUSE and re-installed the latest version of Egnyte Connect and I'm still getting the same error message.

![image001](https://user-images.githubusercontent.com/38015477/38210894-c1ab9bd2-3686-11e8-8be3-b2bc15a153d4.png)

**Comment by doomchild** [comment]
I have this same problem using Transmit Disk.

**Comment by bfleischer** [comment]
Are you using the latest versions of Egnyte Connect and Transmit Disk?

**Comment by doomchild** [comment]
Yes, I'm using the latest version of Transmit Disk.  The problem seems intermittent; it doesn't happen all the time, and when it does, I have to reboot to fix it.

**Comment by opt9** [comment]
So do I. I'm using Transmit Disk.

**Comment by RicardoAnjos** [comment]
@raycasanova43  This can be triggered by different reasons. the most common by far is that the user recently made a clean install in a macOS 10.13 High Sierra and since High Sierra, kernel extensions need to be accepted by the user. Please check the following link to check/solve this scenario: https://helpdesk.egnyte.com/hc/en-us/articles/115002904012-How-to-Approve-Egnyte-s-Kernel-Extension-in-macOS-High-Sierra

If the previous fix didn't work, I would suggest (in case of Egnyte) to contact support team and send them the install.log from your machine. They will be able to look into them, run some commands in your machine and check what is stopping the kernel extension from working properly.

**Comment by bfleischer** [comment]
Is this still an issue with the latest version of FUSE?
