### ISSUE TITLE
Google Drive File Stream conflicts with FUSE for macOS

### ISSUE THREAD

**Issue by danielbair** [osxfuse/osxfuse#503]
I have found that com.github.osxfuse.filesystems.osxfuse and com.google.dfsfuse.filesystems.dfsfuse conflict.

To get FUSE for macOS to work I have to run:
`sudo kextunload -b com.google.dfsfuse.filesystems.dfsfuse`
If I don't do this then I get this error:
`mount_osxfuse: the file system is not available (255)`

I am reporting this in case any others might encounter this issue.

**Comment by dictvm** [comment]
This is indeed quite a problem since we switched from Google Drive to File Stream. Sometimes it works after dancing around a fire while installing, uninstalling and rebooting a bit.

**Comment by armarti** [comment]
Same issue here when trying to install Google Drive File Stream. To get it to work I needed to unload osxfuse with `sudo kextunload -b com.box.filesystems.osxfuse` (not sure `sudo` is necessary, but that's what I did). I'm sure something else is broken somewhere but I don't know what yet.

**Comment by taiyodayo** [comment]
I have the same problem and it is quite a big problem for me since our office switched entirely to Google drive file stream.
Has anyone found a workaround yet?

**Comment by beaulac** [comment]
Issue still occurs with osxfuse 3.9.2

Incompatibility works both ways – Google Drive File Stream is not able to start if the osxfuse kext is loaded:
```
... stderr: (kernel) Kext com.google.drivefs.filesystems.dfsfuse start failed (result 0x5).
... stderr: (kernel) Kext com.google.drivefs.filesystems.dfsfuse failed to load (0xdc008017).
... stderr: (kernel) Failed to load kext com.google.drivefs.filesystems.dfsfuse (error 0xdc008017).
... stderr: Failed to load /Library/StagedExtensions/Applications/Google Drive File Stream.app/Contents/MacOS/dfsfuse.kext - (libkern/kext) kext (kmod) start/stop routine failed.
... stderr: Unhandled kextutil status: 6
... stderr: mount_dfsfuse: the file system is not available (113)
... mount.cc:108:Mount Mount status flags: 0x5c4
... stderr: fuse: failed to mount file system: Unknown error: 113
```

Workaround:
`sudo kextunload -b com.github.osxfuse.filesystems.osxfuse` to use file stream

**Comment by bfleischer** [comment]
This is what happens if a developer tries to rebrand osxfuse to put their own name on it (dfsfuse) and does a poor job. Say thanks to Google. There is nothing I can do from this end.

**Comment by csjx** [comment]
I use keybase.io and it too has a FUSE implementation (`kbfs`).  It seems to not load at times, and I at some point found a post that ` com.intel.kext.intelhaxm` conflicts with it.  I had the same Google Drive File Stream issue with the `dfsfuse` kext not loading, so I tried `sudo kextunload -b com.intel.kext.intelhaxm`. It worked - the Sign In screen appears now after hours of troubleshooting. I probably need the `intelhaxm` extension with Android Studio or the like, so I may have to manually load and unload the extensions. 😐

**Comment by bfleischer** [comment]
@csjx The issue you are seeing is most likely caused by macOS running out of free device slots. The number of device slots is limited. Intel HAXM and kbfs each need a free device slot. A lot of other software does, too. VirtualBox for example needs multiple device slots. Some virus scanners take up device slots, too. This can result in macOS running out of device slots and this prevents kbfs from loading.

**Comment by pedrosanta** [comment]
Yes, this is royal annoying on Google part. 😔 (Going through the same conflict, wanted to have Google Drive File Stream and osxfuse/sshfs running at the same time.)

**Comment by CodeBotFly** [comment]
I was going through some of the new documentation for Apple and I think I found the new API's you might be looking for concerning Kext free options. https://developer.apple.com/documentation/endpointsecurity. I was on a call with our Mac Solutions Engineer at work and brought up the Kextless options. He also pointed me at the EndpointSecurity methods. He said everything is getting new names and function calls, so hopefully that helps? In relations specifically for Google, he said Apple was in talks with them directly about moving in that direction since BigSur wont allow Kexts without disabling machine level security.

**Comment by bfleischer** [comment]
@CodeBotFly The new EndpointSecurity framework does not allow you to develop file systems. It is not a replacement for in-kernel file systems. The EndpointSecurity framework is intended for security software like virus scanners.
