### ISSUE TITLE
sshfs folder/directory disppeared after mounting

### ISSUE THREAD

**Issue by astro313** [osxfuse/osxfuse#518]
Hi,

I am using mac OSX 10.9.5, SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0), OSXFUSE 3.8.1, FUSE library version: 2.9.7. Every time I found remote folder to my local folder, the local folder just disappears. I have tried using the different flags e.g., -o allow_other,defer_permissions but none of that solved the issues. Any ideas? 

Thanks.

**Comment by shrimpwagon** [comment]
Same here.

Seems to work the first time then maybe some timeout makes it disappear.

The mount point seems to stay in tact if you check it via terminal but the folder is gone from Finder.

**Comment by kiril-kirov** [comment]
I have a similar situation. An application, that works totally fine with MacOS Sierra (10.12.6), behaves strangely in MacOS High Sierra (10.13.6). Both Macs have the same OsxFuse installed: 3.7.1.

The situation in High Sierra: the mounted Fuse FS works perfectly fine in the terminal, but in the Finder, the files just disappear. They are shown for a few seconds, then they disappear. After restarting the Finder, the files show again for a few seconds and then disappear. 

After a lot of troubleshooting, I think it's somehow related to the extended attributes support. For example, if I disable the Fuse callbacks for Set/Get/List/Delete xattr, everything works just fine. Once I enable them, the files start disappearing again.

Any ideas how to troubleshoot the Finder to see what happens there?

I know this is not related to sshfs at all, but sounds very similar.

**Comment by kiril-kirov** [comment]
O, it's definitely related to the extended attributes.

I just tried with `noapplexattr` and it started working normally.

@astro313 @shrimpwagon can you, please, try to mount the SSHFS with `-o noapplexattr`? Thanks!

**Comment by kiril-kirov** [comment]
Hmm, I also wonder if it can be somehow related to https://github.com/osxfuse/osxfuse/issues/513 (and I was also wondering about this xattr in the root folder)

**Comment by kiril-kirov** [comment]
Oh, we figured it out and it's totally unrelated. I'll share what we found out, just in case this is useful, but I can also delete my comments, if they are totally useless. Sorry for the spam. 

The problem was in our software, which uses OSXFuse (and has nothing to do with sshfs): 
When the OS asks for an attribute (tries to get it), we return ENODATA, instead of ENOATTR. The reason for this is Linux: in Linux, they are supposed to be the same, but it appears that ENOATTR is not actually defined, so we always return ENODATA. And this works perfectly fine for MacOS Sierra!   
So, afterwards, we found out, that ENODATA is used for other purposes (no idea what) in OSX. And these purposes seem different in Sierra and in High Sierra.  
Returning ENOATTR instead of ENODATA fixes the issue in our software. 

Note: it has nothing to do with sshfs, if it's totally useless information, please let me know and I'll delete my comments.

**Comment by astro313** [comment]
@kiril-kirov I tried mounting with `-o noapplexattr`, but didn't solve the problem. I am not sure if I understand your latest comment. sshfs updated correspondingly? Should I update sshfs to solve this? Thanks.

**Comment by kiril-kirov** [comment]
@astro313 I updated my comment. No, it has nothing to do with sshfs, it was a bug in our code, that uses OSXFuse. 

Thanks for testing with `noapplexattr`. It's now even more obvious, that this is totally different issue and has nothing to do with the one, I was trying to troubleshoot.

**Comment by yanyue** [comment]
1) I umount files using -f option. 
2) I remove the local dir for sshfs.
3) recreate local dir for sshfs
4) exec sshfs again. 

finallly, I found dir from my Finder

**Comment by jasonxxd** [comment]
This issue still exists on my side. I'm wondering if this issue is being solved?

**Comment by Jimbow500** [comment]
Try adding `-o allow_other`

**Comment by viraths** [comment]
`sshfs user@example.net:/home/user/ ~/RemoteHome -o volname=RemoteHome`

Above worked for me. You need to use `-o volname=WhatEverNameYouWantToUse` option and should be all good.

**Comment by bfleischer** [comment]
This ticket has been inactive for a long time, so I'm going to close it. Please open a new ticket in case you are still running into issues.
