### ISSUE TITLE
Using noappledouble causes `cp -r` failures (and also fails copy-paste via Finder)

### ISSUE THREAD

**Issue by kiril-kirov** [osxfuse/osxfuse#519]
Hi, 

I'm trying to use `noappledouble` to avoid polluting the mounted FS with `.DS_Store` files, but this causes some issues.

For example, `cp` fails with error code `1`:

```
$ pwd
<mounted fuse fs>

$ ls -la ~/tmp/
total 48
drwxr-xr-x   4 k  staff    136 Jul 25 13:51 .
drwxr-xr-x+ 41 k  staff   1394 Jul 25 13:50 ..
-rw-r--r--@  1 k  staff  22532 Jul 25 13:50 .DS_Store
-rw-r--r--   1 k  staff      0 Jul 25 13:51 file

$ cp -r ~/tmp ./test
cp: ./test/.DS_Store: No such file or directory

$ echo $?
1

$ ll ./test
total 0
drwxrwxrwx  1 k  staff     0B Jul 25 15:11 .
drwxrwxrwx  1 k  staff     0B Jul 23 10:54 ..
-rwxrwxrwx  1 k  staff     0B Jul 25 15:11 file
```

Similar thing happens in the Finder, too (no matter if the hidden files are shown or not): trying to copy-paste a folder containing .DS_Store from the local FS into a fuse mounted FS results in the following error: 
```
The Finder can’t complete the operation because some data in “tmp” can’t be read or written.
(Error code -36)
```

Is that expected? If so, can this be avoided, as it would lead to bad user experience?

Thanks!
Kiril

**Comment by kousu** [comment]
I'm seeing this too.

I just discovered [`noappledouble`](https://github.com/osxfuse/osxfuse/wiki/Mount-options#noappledouble) and [`noapplexattr`](https://github.com/osxfuse/osxfuse/wiki/Mount-options#noapplexattr) yesterday and added them to my mount command. I really like that you exposed these options because these "dot underbar" files (which is what `dot_clean(1)` calls them) are messy, but worse my server is kind of slow and I think their existence is the cause of the hard lag my fancy Mac GUI hits --- TextEdit locks up for minutes at a time sometimes!

So now I'm mounting with:

```
sshfs -o uid=501 -o gid=20 -o transform_symlinks -o noappledouble -o noapplexattr example.org:Notebook/ ~/Notebook
```

But now trying to copy files from my APFS homedir can give **EPERM**. The file will still copy, what's failing is the metadata resource fork, because of `noappledouble`/`noapplexattr`:

```
$ cp Downloads/sushi_day2.jpg Notebook/
cp: Downloads/sushi_day2.jpg: could not copy extended attributes to Notebook/sushi_day2.jpg: Operation not permitted
$ ls Notebook/sushi_day2.jpg 
Notebook/sushi_day2.jpg
```

Trying to copy these files with Finder shows "The operation can’t be completed because you don’t have permission to access some of the items." (or in French: « Impossible d'effectuer l'opération car vous ne disposez pas des autorisations requises pour accéder à certains éléments. »)

Worse, **sometimes** (but I haven't figured out quite when), Finder decides that this error means the entire copy failed, and will delete the remote file to rollback the change, so _I cannot use Finder to move files on my sshfs drive_. I can live with a bunch of nuisance error messages; I can't deal with file operations getting blocked.

Does anyone know if there is a way to convince OS X to not try to use resource forks on this drive??

---

This doesn't happen with files made on the command line:

```
$ touch test
$ cp test Notebook/
$ ls Notebook/test
Notebook/test
```

**However**, trying to copy such a file with finder does trigger "The operation can’t be completed because you don’t have permission to access some of the items.", even though, after trying that, I can still copy it without error with `cp`; it's like Finder is trying to add xattrs *at copy time* where none existed before.

And opening such a file with a GUI app will taint it with xattrs:

```
$ touch test.txt
$ open test.txt
$# edit the file in TextEdit.app and save
$ cp test.txt Notebook/
cp: test.txt: could not copy extended attributes to Notebook/test.txt: Operation not permitted
$ ls Notebook/test.txt 
Notebook/test.txt
```

---

Mounting without `noappledouble`/`noapplexattr` works fine, of course, because it pollutes my sshfs fileshare with macOS cruft:

```
$ sshfs -o uid=501 -o gid=20 -o transform_symlinks example.org:Notebook/ ~/Notebook
$ cp test.txt Notebook/
$ ls Notebook/test.txt 
Notebook/test.txt
$ ls Notebook/._*
Notebook/._test.txt
$ umount Notebook/
```

---

To demonstrate that the error is triggered by _either_ option:

```
$ sshfs -o uid=501 -o gid=20 -o transform_symlinks -o noappledouble example.org:Notebook/ ~/Notebook
$ cp test.txt Notebook/
cp: test.txt: could not copy extended attributes to Notebook/test.txt: Operation not permitted
$ umount Notebook/
```

```
$ sshfs -o uid=501 -o gid=20 -o transform_symlinks -o noapplexattr example.org:Notebook/ ~/Notebook
$ cp test.txt Notebook/
cp: test.txt: could not copy extended attributes to Notebook/test.txt: Operation not permitted
$ umount Notebook/
```

---

I don't get this problem with smb mounts. If I connect to my local file share:

```
$ mount
/dev/disk1s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
kousu@comms.kousu.ca:sync/Notes/ on /Users/kousu/Notebook (osxfuse, nodev, nosuid, synchronous, mounted by kousu)
//GUEST:@Shared._smb._tcp.example.net/shared on /Volumes/shared (smbfs, nodev, nosuid, noowners, mounted by kousu)
```

Then the same file that annoys sshfs is fine:

```
$ cp ~/test.txt ~/Notebook/
cp: /Users/kousu/test.txt: could not copy extended attributes to /Users/kousu/Notebook/test.txt: Operation not permitted
$ cp ~/test.txt /Volumes/shared/ # no problemo
```


## Version Info

I'm on macOS 10.14.4 (18E226) with sshfs installed via brew:

```
$ brew info sshfs
sshfs: stable 2.10 (bottled)
File system client based on SSH File Transfer Protocol
https://osxfuse.github.io/
/usr/local/Cellar/sshfs/2.10 (6 files, 94.5KB) *
  Poured from bottle on 2019-01-03 at 17:04:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sshfs.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✔, pkg-config ✔
Required: glib ✔
==> Requirements
Required: osxfuse ✔
==> Analytics
install: 4,105 (30 days), 11,785 (90 days), 44,379 (365 days)
install_on_request: 3,466 (30 days), 9,983 (90 days), 37,830 (365 days)
build_error: 0 (30 days)
```

**Comment by bolemo** [comment]
Any progress on that?

I have the exact same problem, and I cannot copy or move any file to the mounted sshfs volume using the Finder, as it cancels the whole process if the hidden files can't be written. I have to use the terminal with cp and ignore the error.

**Comment by gzz2000** [comment]
Exact same here. Hope to be fixed..

**Comment by paulwrightwork** [comment]
+1
When copying and pasting in Finder, I get "The operation can’t be completed because you don’t have permission to access some of the items."
When using `cp` in the terminal, I get "could not copy extended attributes to <file>: Operation not permitted".
I'm mounting an sshfs volume with the following options:
```text
  -o follow_symlinks \
  -o auto_cache \
  -o reconnect \
  -o allow_other \
  -o defer_permissions \
  -o negative_vncache \
  -o noappledouble \
  -o noapplexattr
```

**Comment by bfleischer** [comment]
Recent versions of macOS rely more and more on extended attributes. `noappledpuble` essentially blocks macOS from using its fallback mechanism in case extended attributes are not supported natively by the file system. I don't think there is a way to address this on the macFUSE end.
