### ISSUE TITLE
allow_other not working with sshfs

### ISSUE THREAD

**Issue by lstalbow** [osxfuse/osxfuse#524]
We tried to mount a remote file system with `sshfs -o allow_other ...` and it gave us the error `mount_osxfuse: failed to mount /hpc@/dev/osxfuse0: Operation not permitted`.  The macbook pro is using High Sierra version 10.13.5  and the latest versions of OSXfuse and sshfs.

**Comment by BEFH** [comment]
This is a major issue that we're having on multiple laptops. Can someone please take a look?

**Comment by bfleischer** [comment]
You need to provide more information. With the information given I could only guess and that's not very productive. Try to provide step-by-step instructions so that I can reproduce the issue.

**Comment by ipatch** [comment]
@lstalbow @BEFH 

When y'all run 👇, what is the output of the below command?

```shell
sysctl vfs.generic.osxfuse.tunables.allow_other
```

I had to manually set mine on my box to `1` then I am allowed to mount fuse file systems without required super user privileges.  Keep in mind if you're working on a shared computer this poses possible security issues, but if you're the only person who uses and attaches file systems on your computer then I'd I set the above mentioned flag to `1` to prevent having to use `sudo` to mount file systems.  Keep in mind that a task will need to set in order to persist the setting through reboots.

**Comment by BEFH** [comment]
Sorry I missed this. I haven't been able to reproduce this recently. It may be fixed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bfleischer** [comment]
> Sorry I missed this. I haven't been able to reproduce this recently. It may be fixed.

I'm closing the ticket. Feel free to re-open it is you can reproduce the issue.

**Comment by yuliswe** [comment]
I'm sorry, is this documented anywhere?
```
sysctl vfs.generic.osxfuse.tunables.allow_other
```
I spent 5 hours looking for a solution until I found this issue.
