### ISSUE TITLE
raise OSXFUSE_NDEVICES > 64

### ISSUE THREAD

**Issue by jeffreydlong** [osxfuse/osxfuse#533]
Hi, I have roughly 120 file systems I'd like to mount but am hitting the current 64 limit.  I understand the memory implications with doing this but think my 16 GB system can handle it.  Thus I would like to see if the device limit could be raised?  Thanks

**Comment by bfleischer** [comment]
I'm not a big fan of raising the default device limit, as I don't think many users will mount more than 64 file systems at the same time. However, it might be possible to add an option to specify the number of devices you need. Could elaborate what you need that many devices for?

**Comment by jeffreydlong** [comment]
A configurable run-time option would/should totally work for me. I'm a sys admin basically and currently have about ~120 systems I take care of so it is easier to just have them all mounted rather than having to deal with them individually as needed (plus I can then search for files across all of them in one shot).  sshfs has been a life-saver for not having to deal with NFS, etc.

**Comment by z3thon** [comment]
I have the same need. Is this number set somewhere in the config files? How can I increase the number of mounts I can have? Is there some code I could just modify myself? Or is there a lot of math that goes on that would have to be updated to run more than 64 mounts?

**Comment by z3thon** [comment]
I have found the setting buried within fuse_param.h

If I were to update this myself and push the update to you would you accept it? Or is this still a change you feel uncomfortable making? I would like to set the limit to 512 or even 1024.

**Comment by z3thon** [comment]
Ok, I have tinkered a bit and it's clear that you can't just change the # 64 to whatever number you want it to be. Been compiling my own versions of the code to get what I need and the program isn't having it.

Where in the code are there other dependencies related to the max number of possible mounts?

**Comment by z3thon** [comment]
So I'm testing a 128 connection version but I don't know what all dependencies are. There are some in fuse_param.h and fuse_preprocessor.h, are there any other dependencies any where else?

After I find them all and make the changes can I make a push to git?

**Comment by z3thon** [comment]
helper.c line 154

64 -> 128

How much of the code relies on the exactness of all the parameters listed out in the preprocessor file?

I'm not talented enough to write new code if it's not just based off these numbers. Is there any way we could pay you to make the number of mountable objects unlimited or at least make the roof something like 4096 instead of 64?

@bfleischer

**Comment by jeffreydlong** [comment]
My testing indicated that changing OSXFUSE_NDEVICES in fuse_param.h was all that was needed.  But I also don't have a file named helper.c

**Comment by jperkin** [comment]
I'm now running into this. Since Ventura finally put an end to my NFS-based chroots for building pkgsrc that I've been using for many years (https://pkgsrc.smartos.org/install-on-macos/), I've had to switch over to osxfuse/bindfs, but I can only create a maximum of 4 chroots until I hit the limit.

Each of my chroots mount all of the usual system directories (/System, /Library, /usr, etc...), as well as a few ancillary directories that contain our build files etc.

When building around 24,000 packages it's significantly more efficient on a 10-core system like the ones we build on to create around 8 chroots and build each package with `-j1` concurrently, rather than fewer chroots and higher make jobs.

It's not really possible for me to reduce the number of directories we need to mount for each chroot, and I'd prefer not to have to build my own osxfuse.

**Comment by bfleischer** [comment]
@jperkin You could use bindfs or preferably the loopback macFUSE reference file system to build a custom file system that maps the usual system directories. This way you would not run into the 64 device limit, you would only need 8 devices for 8 chroots. I might be missing something, but this seems cleaner than using multiple bindfs mounts per chroot.

**Comment by jperkin** [comment]
@bfleischer sorry to resurrect this, but would you mind expanding on what you mean here, as it's not entirely clear to me.

Do you mean there's a way to construct a disk image or mount point that contains all of the read-only mounts that I need, and then I just mount that single image/directory into each chroot?

Nested mounts make me a little nervous, but if you're confident this works reliably then I'm happy to give it a go. I'm starting to hit some NFS reliability issues (e.g. https://gist.github.com/jperkin/674099f72da0e77f647affbfe741d33c) so I'd love to migrate some of my NFS mounts back to bindfs but am still currently bound by the 64 mount limit.
