### ISSUE TITLE
Respect Dark theme in Mojave

### ISSUE THREAD

**Issue by diversys** [osxfuse/osxfuse#550]
Mojave sports a new dark theme which is not respected in pref panel.

**Comment by singularitti** [comment]
More details, this is what we see on the upper level panel:
<img width="780" alt="dark" src="https://user-images.githubusercontent.com/25192197/49680700-9a2bc200-fa65-11e8-8d4a-8ed44962ae54.png">
But when we click FUSE icon, we see a light mode panel:
<img width="780" alt="light" src="https://user-images.githubusercontent.com/25192197/49680710-b2034600-fa65-11e8-9784-89adff65ab5d.png">
We wish FUSE supports the Dark Mode (https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/).

**Comment by bfleischer** [comment]
Getting this to work might not be trivial because FUSE still needs to support old versions of macOS. I will look into it but this has a low priority.

**Comment by bfleischer** [comment]
The only way to enable the dark mode for the preference pane, I have found so far, is building the preference pane with the macOS 10.14 SDK, but that will not be possible since we need to support older versions of macOS as well. Any suggestions?

**Comment by singularitti** [comment]
Is there a way for dynamically switching themes between operation systems?

**Comment by andreiborisov** [comment]
> Any suggestions?

Separate build for macOS 10.14+?

**Comment by superbogie** [comment]
Granted this is only a minor cosmetic issue but if it's ever addressable - and in addition to where singularitti pointed to, maybe also look here?:
https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface

**Comment by kainjow** [comment]
Linking to 10.14 doesn’t mean you can’t support older versions. For example the nib could stay the same but at runtime could update the control colors via the @available condition.

**Comment by nrdev88** [comment]
> Linking to 10.14 doesn’t mean you can’t support older versions. For example the nib could stay the same but at runtime could update the control colors via the @available condition.

This is true. Has nothing to do with support. You can easily build a preference pane with 10.15 SDK for almost all older versions.

**Comment by bfleischer** [comment]
@kainjow @nrdev88 This is not the whole story and you are oversimplifying things. 

On 10.6 64 bit preference panes need to support garbage collection. However, garbage collection feature has since been dropped from the macOS SDK. To make things even more complicated, newer versions of macOS will not load preference panes, that are built using garbage collection. The 32 bit image of the preference pane must use manual reference counting, otherwise it will not load on legacy versions of macOS. Newer versions of macOS do not even support 32 bit preference panes.

Starting with the macOS 10.12 SDK Xcode does not longer contain OpenSSL, but OpenSSL is still required by the preference pane (autoinstaller) on legacy versions of macOS. For newer versions CommonCrypto is used. Building the preference pane with an up to date version Xcode would imply bundling OpenSSL or another crypto library with the preference pane (autoinstaller).

Using the macOS 10.14 or 10.15 SDK to build the preference pane might be feasible, but it will require a lot of work and testing to get everything right. Simply setting the deployment target to 10.5 and adding a few @available conditions will not be enough to get it working.

**Comment by kainjow** [comment]
It’s almost 2020, it’s odd to me that 10.6, garbage collection, and 32-bit  are concerns. Seems like osxfuse’s support for archaic macOS versions is overcomplicating the story ;)

**Comment by bfleischer** [comment]
@kainjow The master branch (Version 4 of FUSE for macOS) drops support for 10.5 to 10.8, but I did not have time to update the preference pane or finish work on the master branch. Sadly. supporting at least the last 5 major versions of macOS seems to be required by many companies.

**Comment by bfleischer** [comment]
The feature is implemented in the upcoming version 4.0.0.

**Comment by bfleischer** [comment]
macFUSE 4.0.0 supports dark mode on macOS 11. The new 4.0.1 release also supports dark mode on macOS 10.14 and 10.15.

**Comment by j-rahman** [comment]
@bfleischer Do you have a tentative date for when version 4.0.0. would be released?
