### ISSUE TITLE
The name length of file  is confused on mac

### ISSUE THREAD

**Issue by KobeLuo** [osxfuse/osxfuse#551]
Hi @bfleischer ，**we found the name length of file  is confused when oxsfuse work on different language on mac system.** 

For example:
- Under the Korean system, the maximum name characters is about 35.
- Under the English system, the maximum name characters is about 250.
- Under the Chinese or Japan system, the maximum name characters is about 83.

the screenshot is as following:
![5ddac7a7-fe52-4055-9716-942ccbd0664b](https://user-images.githubusercontent.com/26185543/47489177-93137080-d878-11e8-96df-68253c527233.png)
 

The finder system is not limit of the file length. so we guess that osxfuse has limited the length of file name, but we didn't know the rule of limit.

so could you tell me **how to calculate the file name length if osxfuse limit the length of file name?**

**Comment by bfleischer** [comment]
Let's take the Korean character 폴 as an example. There are two UTF-8 representations of this character: 

- The NFC representation: 0xED 0x8F 0xB4
- The NFD representation: 0xE1 0x84 0x91 0xE1 0x85 0xA9 0xE1 0x86 0xAF 

Using the NFC representation the character 폴 requires 3 bytes. Using the NFD representation the character requires 9 bytes. 

On macOS the maximum number of bytes per file name is 255. So this means that depending on the representation you use the maximum number of characters that you can fit into the 255 bytes might vary greatly. You need to encode the file names using the NFC form in order to support longer names.
