### ISSUE TITLE
Mounting in a brand-new way

### ISSUE THREAD

**Issue by plashenkov** [osxfuse/osxfuse#557]
It looks like new macOS allows to mount 3rd-party file systems without low-level mechanisms, using other techniques. Mountain Duck built in this way: no installation required, no admin privileges required. Just run the app and you are able to mount.

Is there any chance FUSE for macOS will implement this mechanism?

Some links:
Mountain Duck info about this: https://mountainduck.io/comparison/
Note from Panic (Transmit Disk): https://library.panic.com/transmit/transmit5/transmit-disk/#technical-details-and-the-future-of-transmit-disk

**Comment by ksherlock** [comment]
Mountain duck seems to run an [NFS server in userspace](https://github.com/iterate-ch/kfs/tree/feature/mountainduck).  The OS X NFS fs connects to the userspace NFS server which converts NFS requests into other protocols (and back).  It's an impressive hack, to say the least.

**Comment by bfleischer** [comment]
Implementing an user space NFS server is not a new technology. What Mountain Duck is doing has been possible for ages. In fact, Apple's FTP implementation uses the exact same approach. The downsides of using an NFS server instead of FUSE are worse performance and the lack of low level system integration. There are some features (local mounts, Spotlight support, Trash folder, ...) that will not work via NFS. In some cases, e.g. simple network file systems, NFS might be a good solution, but for local, high performance file systems like NTFS-3G it would be way too slow. The biggest advantage of NFS over FUSE is App Store compatibility.

**Comment by plashenkov** [comment]
Okay, I see now, thank you @ksherlock and @bfleischer. Do you see any meaning in implementing NFS in osxfuse? Or there is no point?
