### ISSUE TITLE
Kernel panic with 3.8.2 on OS 10.12.6

### ISSUE THREAD

**Issue by rainforest1155** [osxfuse/osxfuse#567]
I just updated (2 days ago) from 10.11.6 to 10.12.6 and using an external drive with a Veracrpt container, after about 20 min, my Mac crashed.

This is the panic log:
```
Fri Jan 11 11:56:35 2019

*** Panic Report ***
panic(cpu 2 caller 0xffffff801a39bafc): "wire_count == 0, m = 0xffffff8029fbd628, obj = 0xffffff804cf87000\n"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.70.16/osfmk/vm/vm_pageout.c:7516
Backtrace (CPU 2), Frame : Return Address
0xffffff922f7ab9c0 : 0xffffff801a2e953c 
0xffffff922f7aba40 : 0xffffff801a39bafc 
0xffffff922f7abd80 : 0xffffff801a8cc8c9 
0xffffff922f7abde0 : 0xffffff7f9b955291 
0xffffff922f7abe00 : 0xffffff7f9b955306 
0xffffff922f7abe20 : 0xffffff801a8bd76a 
0xffffff922f7abe90 : 0xffffff801a8c13d0 
0xffffff922f7abf00 : 0xffffff801a32219a 
0xffffff922f7abfb0 : 0xffffff801a2978f7 
      Kernel Extensions in backtrace:
         com.apple.driver.DiskImages(444.50.16)[7A04C2E6-40FF-36A9-84D4-FDF685F3B0A9]@0xffffff7f9b953000->0xffffff7f9b96bfff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[F908D7F5-4F54-3B89-8657-57F06350F4DB]@0xffffff7f9aacc000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
16G29

Kernel version:
Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
Kernel UUID: D3314D98-5D40-3CD8-98A4-F1DD46C20E03
Kernel slide:     0x000000001a000000
Kernel text base: 0xffffff801a200000
__HIB  text base: 0xffffff801a100000
System model name: MacBookPro12,1 (Mac xx)

System uptime in nanoseconds: 16887007674156
last loaded kext at 16342406014199: com.github.osxfuse.filesystems.osxfuse	3.8.2 (addr 0xffffff7f9d4ed000, size 106496)
last unloaded kext at 16413118853293: com.apple.driver.usb.cdc	5.0.0 (addr 0xffffff7f9d4a7000, size 28672)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.8.2
org.virtualbox.kext.VBoxNetAdp	5.2.18
org.virtualbox.kext.VBoxNetFlt	5.2.18
org.virtualbox.kext.VBoxUSB	5.2.18
org.virtualbox.kext.VBoxDrv	5.2.18
com.paragon-software.filesystems.ntfs	44.4.15
com.shapeservices.msm.driver.MSMFramebuffer	3.5.0
com.shapeservices.msm.driver.MSMVideoDevice	3.5.0
com.paragon-software.filesystems.extfs	16.2.11
com.apple.filesystems.msdosfs	1.10
com.apple.filesystems.smbfs	3.1.2
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AGPM	110.23.17
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	5.0.5f1
com.apple.driver.AppleGraphicsDevicePolicy	3.14.49
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDA	279.48
com.apple.driver.AppleIntelBDWGraphics	10.2.5
com.apple.driver.AppleLPC	3.1
com.apple.iokit.BroadcomBluetooth20703USBTransport	5.0.5f1
com.apple.driver.AppleIntelBDWGraphicsFramebuffer	10.2.5
com.apple.driver.AppleBacklight	170.9.20
com.apple.driver.AppleMCCSControl	1.3.4
com.apple.driver.AppleCameraInterface	5.60.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.AppleSMCLMU	208
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleUSBCardReader	404.50.6
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.70.1
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AppleAHCIPort	326.60.1
com.apple.driver.AppleTopCaseHIDEventDriver	114
com.apple.driver.AirPort.Brcm4360	1150.12.1a1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	279.48
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOSurface	159.9
com.apple.driver.AppleGraphicsControl	3.14.49
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.5f1
com.apple.iokit.IOBluetoothFamily	5.0.5f1
com.apple.AppleGraphicsDeviceControl	3.14.49
com.apple.iokit.IOAcceleratorFamily2	311.14
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	516.1
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleHDAController	279.48
com.apple.iokit.IOHDAFamily	279.48
com.apple.iokit.IOAudioFamily	205.15
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOGraphicsFamily	515.3
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.iokit.IOSCSIBlockCommandsDevice	394.50.1
com.apple.iokit.IOUSBMassStorageDriver	131.60.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394.50.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.CoreStorage	540.30.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleHIDKeyboard	199
com.apple.driver.AppleMultitouchDriver	368.16
com.apple.driver.AppleInputDeviceSupport	76.7
com.apple.driver.AppleHSSPIHIDDriver	49
com.apple.driver.AppleThunderboltNHI	4.5.4
com.apple.iokit.IOThunderboltFamily	6.5.7
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleHSSPISupport	49
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.50.16
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
```

Note that the external drive and Veracrypt container are formatted with NTFS (I'm using Paragon NTFS for Mac), but it doesn't seem to be part of the backtrace from what I can tell.

Are you able to tell anything from the log? I'll try updating to the latest OSXFuse to see if that helps.

**Comment by M0pbucket** [comment]
I have been getting kernel panics sporadically since October 2018. The can happen multiple times a day or every few days. There appears to be no regularity to it except that it continues to happen.

I am using Fuse 3.8.3, the same issue was happening on a previous version.

I am mainly using AFPS Mac filesystem but also use Box Drive (Dropbox alternative). Occasionally the kernel panic reports that Box is involved, but vast majority of the time OSXFuse is reported.

Wed Jan  2 11:54:25 2019

*** Panic Report ***
panic(cpu 0 caller 0xffffff8015cbb4fd): "Invalid queue element linkage for 0xffffff8030719780: next 0xffffff8030719790 next->prev 0xffffff8041ea03f0 prev 0xffffff8030719780 prev->next 0xffffff8030719790"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.231.4/osfmk/kern/queue.h:244
Backtrace (CPU 0), Frame : Return Address
0xffffff92277a37f0 : 0xffffff8015baeafd 
0xffffff92277a3840 : 0xffffff8015ce85a3 
0xffffff92277a3880 : 0xffffff8015cd9fca 
0xffffff92277a38f0 : 0xffffff8015b5bca0 
0xffffff92277a3910 : 0xffffff8015bae517 
0xffffff92277a3a30 : 0xffffff8015bae363 
0xffffff92277a3aa0 : 0xffffff8015cbb4fd 
0xffffff92277a3bc0 : 0xffffff8015c380d1 
0xffffff92277a3d30 : 0xffffff8015c39f08 
0xffffff92277a3f10 : 0xffffff8015cda5c5 
0xffffff92277a3fa0 : 0xffffff8015b5bbaf 

BSD process name corresponding to current thread: garcon

Mac OS version:
18C54

Kernel version:
Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Kernel UUID: 56B30885-F9BA-30E8-AD1C-5D59EC243BA9
Kernel slide:     0x0000000015800000
Kernel text base: 0xffffff8015a00000
__HIB  text base: 0xffffff8015900000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 3947398210635
last loaded kext at 3536270854268: com.apple.driver.AppleUSBAudio	315.6 (addr 0xffffff7f9917f000, size 413696)
last unloaded kext at 3777108283677: com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2 (addr 0xffffff7f99166000, size 28672)
loaded kexts:
com.box.filesystems.osxfuse	203.6.4
com.apple.fileutil	18.306.12
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AGPM	110.23.46
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleGraphicsDevicePolicy	3.28.4
com.apple.driver.AppleHDA	282.10
com.apple.AGDCPluginDisplayMetrics	3.28.4
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.9f2
com.apple.driver.pmtelemetry	1
com.apple.driver.AppleIntelBDWGraphics	12.0.4
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.eficheck	1
com.apple.driver.AppleSMCLMU	212
com.apple.driver.AppleThunderboltIP	3.1.2
com.apple.iokit.BroadcomBluetooth20703USBTransport	6.0.9f2
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleCameraInterface	6.8.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMCCSControl	1.5.6
com.apple.driver.AppleIntelBDWGraphicsFramebuffer	12.0.4
com.apple.driver.AppleUSBCardReader	456.230.1
com.apple.driver.AppleVirtIO	2.1.2
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.filesystems.apfs	945.230.6
com.apple.driver.AppleAHCIPort	329.200.2
com.apple.driver.AppleTopCaseHIDEventDriver	138.2
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.private.KextAudit	1.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	190
com.apple.security.TMSafetyNet	8
com.apple.kext.triggers	1.0
com.apple.driver.AppleGraphicsControl	3.28.4
com.apple.driver.DspFuncLib	282.10
com.apple.kext.OSvKernDSPLib	527
com.apple.iokit.IOAVBFamily	710.1
com.apple.plugin.IOgPTPPlugin	700.7
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.AppleGPUWrangler	3.28.4
com.apple.iokit.IONDRVSupport	530
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.9f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.9f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.9f2
com.apple.driver.AppleHDAController	282.10
com.apple.iokit.IOHDAFamily	282.10
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.AppleGraphicsDeviceControl	3.28.4
com.apple.iokit.IOAcceleratorFamily2	404.2.2
com.apple.iokit.IOGraphicsFamily	530.14
com.apple.iokit.IOSurface	255.1
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.networking	5.0.0
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOAHCIBlockStorage	301.200.2
com.apple.driver.AppleThunderboltDPInAdapter	5.5.8
com.apple.driver.AppleThunderboltDPAdapterFamily	5.5.8
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.4
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleActuatorDriver	2410.5
com.apple.driver.AppleHIDKeyboard	208
com.apple.driver.AppleHSBluetoothDriver	138.2
com.apple.driver.IOBluetoothHIDDriver	6.0.9f2
com.apple.iokit.IOBluetoothFamily	6.0.9f2
com.apple.driver.AppleMultitouchDriver	2410.5
com.apple.driver.AppleInputDeviceSupport	2410.2
com.apple.driver.AppleHSSPIHIDDriver	55
com.apple.driver.AppleThunderboltNHI	4.7.6
com.apple.iokit.IOThunderboltFamily	6.8.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleHSSPISupport	55
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.230.1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.200.1
com.apple.iokit.IOSCSIArchitectureModelFamily	408.200.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	700.7
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1

EOF
Model: MacBookPro12,1, BootROM 180.0.0.0.0, 2 processors, Intel Core i7, 3.1 GHz, 16 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.9f2, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by M0pbucket** [comment]
These kernel panics happen very regularly- I have had 4 today. Is there any fixes for this?

**Comment by bfleischer** [comment]
@rainforest1155 please report the panics to Apple. The panic you posted here is not caused by FUSE for macOS. As you can see both kernel extensions in the backtrace (com.apple.driver.DiskImages and com.apple.iokit.IOStorageFamily) are part of macOS. There is no indication that FUSE might be to blame for the panic.

@M0pbucket The panic log does not point to Box or FUSE. The backtrace does not contain any Box nor FUSE functions. Box's custom version of FUSE is loaded at the time of the crash but from what I can tell the panic is completely unrelated. Please report the issue to Apple.

From what I can tell the `garcon` process that triggered the panic is part of the Dropbox client. It might be worth reporting the issue to the Dropbox team.

**Comment by M0pbucket** [comment]
Thank you for your help.

**Comment by wmertens** [comment]
I just had this same panic (the one in vm_pageout) in a 2017 MBP that got an SSD replacement under the program, on 10.14.4 with nothing installed. The only difference is the line number.

I never had this crash before the replacement. 

So I'm guessing this is a hardware issue I'll have to return the MBP again and be without it for another week, in a possibly endless loop :(

**Comment by AlexanderLill** [comment]
I've been having the same problem and sometimes it took hours to panic, and sometimes it happened right away. I had a suspicion that the power management of the external USB drive is responsible for this and double-checked my energy management settings to never turn off hard drives and never sleep. Until now there were no further panics!
