### ISSUE TITLE
Sign with custom Kernel Extension certificate

### ISSUE THREAD

**Issue by Longhanks** [osxfuse/osxfuse#583]
Hi,

in case that I've got certificates for Developer ID Application, Developer ID Installer and one for signing Kernel Extensions (pending), what's the preferred way of signing the frameworks, libraries and the kext with those certificates? When providing the argument `--code-sign-identity` the `build.sh` script errors out with `Illegal option 'code-sign-identity'`.

Thanks for any help!

**Comment by bfleischer** [comment]
Andreas, please use the official releases instead of building FUSE yourself.

If you absolutely need to build FUSE yourself because your life depends on it, you need to make sure to completely rebrand it, otherwise it will interfere with official releases. This is a lot of work, complicated, and error prone. It also means you will need to maintain your FUSE fork in the future, resulting in even more work. Are you planning on shipping FUSE with a commercial product? In this case I ask you to contact me via email. You can find my email on my GitHub page.
