### ISSUE TITLE
Allow osxfuse to function on macOS 10.13+ without reboot

### ISSUE THREAD

**Issue by cafarm** [osxfuse/osxfuse#588]
This may not be possible with Apple’s new restrictions in 10.13+ on third party extensions, but there are use cases where a machine cannot be rebooted but would still like to utilize osxfuse. 

One use case that’s of interest to me is on cloud CI providers like Travis CI where dependent software needs to be installed on-the-fly during each build. osxfuse previously worked for this use case (pre 10.13) but no longer works because it cannot be authorized to run (that I’m aware of). 

You can see some discussion of this issue here: https://github.com/travis-ci/travis-ci/issues/10017

**Comment by bfleischer** [comment]
FUSE does not require you to reboot your Mac on a fresh install. The Travis CI issue you are referring to is caused by Apple requiring users to consent before new kernel extensions can be loaded for the first time. Apple will not change this policy, so you will need to talk to the Travis CI guys. There is nothing that could be done from the FUSE end to address this issue. Travis needs to disable the Kext part of SIP or provide a special image with FUSE pre-installed or pre-allowed.
