### ISSUE TITLE
If folder name start with "[", in some Mac, children excel file , will save fail

### ISSUE THREAD

**Issue by wenboma** [osxfuse/osxfuse#596]
for example:
path is : /[Team/A/B/c.xlsx
in some Mac, edit c.xlsx,  will save fail

**Comment by IainCollins262** [comment]
On macOS 10.15 at least folders are allowed to start with a '[' character. Assuming folders are allow to start with a '[' character for the version of macOS which you are currently running then this sounds like an issue with the tool which you are using to edit the excel file with rather than a FUSE issue.

**Comment by wulaitianc** [comment]
I met the same problem here. 
If the path contains both "[" & " ]"(e.g. /[folder]A/test.xlsx, /folderA/t[e]st.xlsx), save excel always fail.

<img width="422" alt="Screen Shot" src="https://user-images.githubusercontent.com/17898549/105819915-cfa01a80-5ff3-11eb-9286-89a9d7e2f29c.png">
I believe it's a fuse bug, because I can save excel with such path on ~/Desktop.

**Comment by bfleischer** [comment]
Try the same thing on an FAT formatted volume

**Comment by wulaitianc** [comment]
Tested on FAT32 with LoopbackFS demo, still couldn't save excel with "[]" in the path.

**Comment by bfleischer** [comment]
What I meant was, try testing this on a FAT formatted volume without LoopbackFS and macFUSE. Last time I tested this, it failed, too, without macFUSE being the mix.

The macFUSE code does not contain any checks or conditions that would explain the "[" issue. macFUSE does not care about the characters in the file name. It is unclear what triggers the error, but it affects other file systems as well.
