### ISSUE TITLE
osxfuse's new non-free license

### ISSUE THREAD

**Issue by cadmartin** [osxfuse/osxfuse#616]
New releases have the following message in their description:

> The license has changed. Starting with the 3.10.0 release, redistributions bundled with commercial software are not allowed without specific prior written permission. Please contact Benjamin Fleischer.

However the `LICENSE` file does not reflect the new licensing terms.

For those of us considering contributing this project or using it as a dependency, can we get a clarification on the project's new non-free license from @bfleischer?

Thanks

**Comment by d235j** [comment]
@cadmartin the project is no longer open source either.

The latest at https://github.com/osxfuse/osxfuse/tree/support/osxfuse-3 is v3.8.3.
https://github.com/osxfuse/osxfuse/tree/releases contains no code.

Silently making a project closed-source like this, is at the very least, poor form. The updater should at least notify end users that this is happening, as well.

This post on the Google group seems to indicate what's going on: https://groups.google.com/d/msg/osxfuse-group/_5PBFQ_BQB8/z1mu2H0rFAAJ

Also https://github.com/osxfuse/osxfuse/issues/590

**Comment by bfleischer** [comment]
@d235j How would you have handled the situation? You have read #590, so you know that FUSE on macOS would most likely have died without external funding. Trust me, I tried to convince companies to fund the project for years but nothing much came of it.

@cadmartin FUSE releases up until version 3.8.3 are open source. For now, newer releases are closed source, with libosxfuse being the exemption. FUSE is and always will be free for non-commercial use. Bundling FUSE with commercial software however requires a license starting with version 3.10. If you are interested in obtaining such a license write me an email.

**Comment by d235j** [comment]
@bfleischer while I dislike that it’s closed source, that is a separate issue. I’m only advocating for transparency here.

Informing people means updating the main repo README to state that versions starting with 3.9.0 are no longer open source, and that versions starting with 3.10.0 are under a new license, with a link to the license, and

Informing people updating from 3.8.0 or 3.9.0 to 3.10.0 using the updater, as well as informing anyone who has updated via updater without being informed, of the source code availability change and the license change.

When I find out that some software package has changed license only because I’ve gone to the website and poked around, I tend to become very disillusioned due to the lack of transparency — it feels like a bait and switch. Go ahead and change the license — but let me know about it *before* I install the new version.

(Also separately — note that the APSL which might still cover some components of the package outside of libfuse has a weak copyleft. libosxfuse is derived from LGPL code and cannot be closed.)

**Comment by Lusitaniae** [comment]
I agree, it should be more transparent, and the readme and license files should be updated.

Otherwise, fully understand you make it close source and ask for commercial license.

**Comment by freeplant** [comment]
Hi @bfleischer,

We are using OSXFuse in our product. We are recently noticed the license issue. We have funded Dokany project for two years.  So we'd like to know the details on how to fund OSXFuse. The email is already sent to you.

**Comment by exedore6** [comment]
The empty zip and tarball for the source is pretty shifty. Some of us are using it for personal use because the code is available. I understand the need to monetize it, especially with it being a kernel extension as apple tightens the screws.

But if you're gonna lock it up. I really think you need to be crystal clear that not only is the program non-free (with an undisclosed cost for a commercial license), but also closed source.

**Comment by ipatch** [comment]
i do agree there should have been some notice about the licensing changes, but in the author's defense a PR could be sent to update the README in this project to reflect the new licensing.

and yes, I'm very well aware that i could send such PR, but i'm not fully aware of all the different versions fuse or licenses, as I just came here because FWR fuse is no longer working on my box 🤷‍♂️ with ntfs-3g or ext

**Comment by flaw600** [comment]
It's not really our responsibility to update the License or the Readme: it's the maintainer's - especially if the maintainer is explicitly changing the type of project this is.

**Comment by dgordoncal** [comment]
@bfleischer We would like to hire you & contribute to keep this project going.  How can we best reach you?  We tried Gmail but never heard back.

**Comment by mascguy** [comment]
@bfleischer I'm interested in providing voluntary contributions to the project, if that's an option.

**Comment by bfleischer** [comment]
@mascguy Thanks for your offer. You can find my email address on my GitHub profile. How would you like to contribute?

**Comment by mascguy** [comment]
> @mascguy Thanks for your offer. You can find my email address on my GitHub profile. How would you like to contribute?

I'd like to volunteer my time, in whatever way I can. Whether it's testing, documentation, sample filesystems, social media... anything to reduce the burden of maintaining the project.

I'll reach out privately via e-mail.

**Comment by fjarlq** [comment]
These [Homebrew](https://brew.sh/) packages will no longer be supported by Homebrew due to their dependence on FUSE, which Homebrew can no longer afford to support as an external dependency (as a "cask", in Homebrew parlance):

afuse, archivemount, avfs, bindfs, btfs, cryfs, curlftpfs, dislocker, encfs, ext2fuse, ext4fuse, fuse-zip, gcsfuse, gitfs, gocryptfs, goofys, ifuse, mp3fs, ntfs-3g, rofs-filtered, s3-backer, s3fs, s3ql, securefs, simple-mtpfs, squashfuse, sshfs, tup, wdfs, xmount

> "FUSE for macOS cannot be replaced by a formula [-- a recipe that Homebrew can use to build and install directly from source --] as it no longer has public source releases and does not have a license that is compatible with Homebrew. In addition, versions of FUSE for macOS prior to the licensing change in 3.10 will soon no longer work on our supported versions of macOS."
>
> "While you can still `brew install` these formulae today, Homebrew maintainers will no longer be updating or supporting FUSE formulae, and our continuous integration will not test them going forwards. These formulae will eventually be removed in the indeterminate future."

-- https://github.com/Homebrew/homebrew-core/pull/64491

**Comment by darelover** [comment]
> These Homebrew packages will no longer be supported by Homebrew due to their dependence on FUSE, which Homebrew can no longer afford to support as an external dependency (as a "cask", in Homebrew parlance):
> 
> afuse, archivemount, avfs, bindfs, btfs, cryfs, curlftpfs, dislocker, encfs, ext2fuse, ext4fuse, fuse-zip, gcsfuse, gitfs, gocryptfs, goofys, ifuse, mp3fs, ntfs-3g, rofs-filtered, s3-backer, s3fs, s3ql, securefs, simple-mtpfs, squashfuse, sshfs, tup, wdfs, xmount

For this same reason, I am thinking of maintaining [this tap](https://github.com/darelover/homebrew-ntfs-3g) for people who still want to get `ntfs-3g` using homebrew

**Comment by joernhees** [comment]
hmmpf... i stumbled into this issue as a user of ext4fuse after brew now says:
```
$ brew install ext4fuse
Error: ext4fuse has been disabled because it requires closed-source macFUSE!
```

From what i read, this seems like an unfortunate and pretty stuck situation in which both parties blame the other.
The license / closed-source issues and powerplay now however seems to result in macfuse to be defacto unusable for standard / noob users (e.g., those who just want to mount an ext2/ext4 SD card).

Is that really your intention?

Also, how come so many other OSS projects (that you have no doubt benefited from) find other ways to deal with similar (albeit difficult) situations? How come there isn't even a donation button or the like easily findable?

If you're on a highway and many others seem to be going the wrong way... maybe stop and consider you're going the wrong way yourself?

**Comment by ipatch** [comment]
@joernhees 

i leave this here, for you, and _for future me_ 👴🏼

https://github.com/gromgit/homebrew-fuse

just tap that repo, and should be able to mount your sd card with an ext* filesystem.

**Comment by bfleischer** [comment]
> Also, how come so many other OSS projects (that you have no doubt benefited from) find other ways to deal with similar (albeit difficult) situations? How come there isn't even a donation button or the like easily findable?

macFUSE is not an end user product. It's a software component that is used primarily by software developers who integrate it into their product and ship it as part of their (commercial) software to end users. Many end users don't even know that the product they are using is based on macFUSE. And you can't expect them to donate to a project that is used by the software they already paid for. Very few companies will donate money to an open source project. Quite frankly I was contacted by just one company that offered to donate to the project during the past ten years.

I'm sure that relying on donations is not sustainable, in this particular case at least. You can find the stories of a few open source developers online who tried to make the donation model work. Many failed or are barely scraping by and need to take on additional work to fund their work on open source.

To give just one example, here is the Patreon page of Max Howell, the creator of Homebrew and other very popular projects that are widely used and loved: https://www.patreon.com/mxcl. Currently he is making less than a fourth of the US minimum wage.

> If you're on a highway and many others seem to be going the wrong way... maybe stop and consider you're going the wrong way yourself?

I am going my way. You don't have to agree with it. I'm sure you heard this saying before: If everyone jumped off a cliff, would you jump, too?

**Comment by d235j** [comment]
@bfleischer It would have been nice if you informed users who clicked "Update" of the license change when it happened.

I brought this up above at https://github.com/osxfuse/osxfuse/issues/616#issuecomment-532422690 and the response was a deafening silence. The README for this repository was only updated in October 2020, nearly a year and a half after the license change.

Ultimately I am hoping that Apple provides a built-in userspace filesystem mechanism in macOS 13 so that we no longer have to deal with loading kexts, as third-party filesystem support is probably the main remaining large-scale use of kexts.

**Comment by bfleischer** [comment]
@d235j The update mechanism is very old and does not support displaying messages. However, the release notes of all releases between 3.10.0 and 4.1.2 (roughly one year) contain a note about the license change. This means that all users who cared about the changes from one release to the next were (and still are) able to find this information. It's not like I have been hiding the license change. In my opinion the release notes are the perfect place to put this kind of information. 

> I brought this up above at #616 (comment) and the response was a deafening silence. The README for this repository was only updated in October 2020, nearly a year and a half after the license change.

Quite frankly, bringing this up again is no use. Neither of us can change the past.

**Comment by Lusitaniae** [comment]
I guess at this point just make a final statement and close the issue / block new messages.

And make any additional updates to README to clarify the current situation if you think worthwhile.

**Comment by muaaz0412** [comment]
> @d235j How would you have handled the situation? You have read #590, so you know that FUSE on macOS would most likely have died without external funding. Trust me, I tried to convince companies to fund the project for years but nothing much came of it.
> 
> @cadmartin FUSE releases up until version 3.8.3 are open source. For now, newer releases are closed source, with libosxfuse being the exemption. FUSE is and always will be free for non-commercial use. Bundling FUSE with commercial software however requires a license starting with version 3.10. If you are interested in obtaining such a license write me an email.

I emailed you asking about the purchasing of the license can you please tell me about it.
