### ISSUE TITLE
Force eject for no response from user space using EncFS based Firefox profile

### ISSUE THREAD

**Issue by droe** [osxfuse/osxfuse#62]
I have my Firefox profile directory on an EncFS mount on OSXFUSE. It generally works fine, but after a few minutes or hours of use, OSXFUSE force ejects the filesystem:

    17.11.12 20:02:59.000 kernel: OSXFUSE: force ejecting (no response from user space 5)
    17.11.12 20:02:59.000 kernel: OSXFUSE: filehandle_get: failed for places.sqlite-shm (type=2, err=57, caller=0xffffff7f80798c59)
    17.11.12 20:02:59.116 KernelEventAgent: tid 00000000 received event(s) VQ_DEAD (32)

It tends to happen when visiting complex websites such as Facebook, when the file cache, URL history etc. in the EncFS-backed profile directory are under heavy use. I also have a lot of other data on other EncFS mounts which never crash, so I assume it has to do with the types of filesystem operations Firefox is doing (maybe locking?), some race condition maybe.

I had this problem with OSXFUSE 2.3.9 through 2.5.4 (I used Fuse4X before switching to OSXFUSE 2.3.9). Currently I run the following versions:
- OSXFUSE 2.5.4
- EncFS 1.7.4
- Firefox 16.0.2
- MacOS 10.7.5

**Comment by rockuw** [comment]
Hi, I got this problem with s3fs today and tried out a solution(at least for me):

It seems the curl in mac os cannot handle the HTTP 100-Continue response correctly. 

I find in s3fs's log some CURLE_GOT_NOTHING errors and tcpdump the traffic. It's a 100-Continue response. So I make a guess and change s3fs to disable the header when making requests. The problem is gone.
