### ISSUE TITLE
In Catalina Beta 9, cannot open image files with "direct_io" mount option.

### ISSUE THREAD

**Issue by hctest155** [osxfuse/osxfuse#628]
Hello, bfleischer.

In Catalina Beta 9 (19A573a), Image files not opening through Finder and not showing thumbnail.
I think that it is similar to #615 issue.

You said that it was caused by a bug in Catalina and already fixed by Apple, 
but Preview application still cannot open the image files with “direct_io” mount option.
On the other hand, QuickTime Player works fine with audio or video files.

LoopbackFS example added “direct_io” mount option also has same issue.

Please check this issue.
Thanks!

**Comment by colatkinson** [comment]
@hctest155 @bfleischer I can confirm that I am also experiencing this on Catalina's stable release.

Are there any clues as to the underlying issue, or if there are any workarounds? This is borderline breaking the FS from a typical user's PoV due to how many file types are affected.

**Comment by andreeacazacusin** [comment]
Are there any updates on this issue? 
We are currently experiencing problems with Fuse 3.10.3 on Catalina, while trying to open images and pdfs. 
Also, when opening a zip file we receive a 512 error, from Archive Utility

**Comment by bfleischer** [comment]
From what I can see Preview tries to `mmap(2)` the image file. However, `mmap()` is not supported when mounting a volume with the `direct_io` option. `direct_io` is a hack that bypasses the normal I/O flow in the kernel. As a result some common file system features like memory mapping files are not available. Is there any particular reason you are using the `direct_io` mode?

**Comment by bfleischer** [comment]
On macOS 10.14 Preview.app supports reading the file without using `mmap(2)`.

**Comment by colatkinson** [comment]
Interesting--good to know what the source of the changed behavior was.

We currently use `direct_io` because our FUSE is a "middle layer," depending on some underlying FS for information. This can become complicated especially with Samba/NFS backends.

In order to move away from it, we're currently experimenting with using `attr_timeout=0` instead. Does using this option allow osxfuse to take a more normal path from macOS's perspective?

**Comment by rca** [comment]
The Dropox-like [cloud storage service, Tresorit](https://tresorit.com/) has a "drive" feature that's built on top of FUSE.  It appears this bug is affecting its ability to open PDFs and images through the Drive.

Any idea if this issue is being addressed or is it on the back burner?

Thank you!

**Comment by bfleischer** [comment]
@rca Please contact Tresorit regarding the issue. Tresorit does not contribute to the FUSE for macOS project.

**Comment by rca** [comment]
Thanks, I have contacted them.

Also, fwiw, I tried sshfs and it does not exhibit the same issue.  PDFs and images display just fine.

**Comment by jkowalski** [comment]
FWIW I'm seeing similar behavior on macOS 11.1 + MacFuse 4.0.5.

I accidentally used DIRECT_IO flag in my code and it appears that this was causing `Preview` to **issue a read of 1 byte** instead of 4096 only (at least that's how it appeared at the FUSE layer). The read succeeded but Preview said the file is corrupted. 

Without DIRECT_IO flag the read was 4096 bytes as expected.

Side-by-side logs of DIRECT_IO vs default are available in https://github.com/hanwen/go-fuse/issues/390
