### ISSUE TITLE
sshfs not working on mac mojave version 10.14.5 (18F132)

### ISSUE THREAD

**Issue by Angha** [osxfuse/osxfuse#630]
No error while installing or mounting, but  it actually not getting mounted. ls to the mountpoint is blank.

$ sshfs -V
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.10.3
FUSE library version: 2.9.7
fuse: no mount point

**Comment by nedex** [comment]
Try with defer_permissions and allow_other options

**Comment by bfleischer** [comment]
@Angha Is this still an issue?

**Comment by cbertelli** [comment]
Getting the same problem, I tried with these options:
`sshfs user@host.doma.in:/home/user ~/mnt/server -o idmap=user -o follow_symlinks -o defer_permissions -o allow_other`
getting the same behaviour: `Device not configured`.
when debugging the connection I got a Floating point exception: 8 (division by zero) which seems to be usual for ssh connections. Maybe it's a security issue caused by recent minor upgrade of MacOS, I upgraded Fuse and sshfs because of this error so maybe it's not their fault.

**Comment by fingon** [comment]
This is happening for me too, and still on 10.14.6. It started sometime this autumn, so 10.14.something.

If I have the motivation I will either debug this, or upgrade to Catalina, as I like using sshfs.

**Comment by cbertelli** [comment]
Sorry! I verified versions and the issue is different.
I installed osxfuse via macbrew
`brew cask install osxfuse`
and I got version 3.10.4.
Then I installed sshfs with it, and this is not a cask, so:
`brew install sshfs`
and I got version 2.10.
So it's not the same bug. "Downgrading" to 2.05, the version which is downloadable here, I got it working, even if with a different behaviour. When unmounting local nodes, the local directories were deleted. Funny. Maybe is a feature of version 3...

**Comment by phretor** [comment]
Same issue on macOS 10.14.6 and osxfuse 3.10.4. After a while it gives a `Device not configured`.

**Comment by xerc** [comment]
after upgrade from 10.13 to 10.14.6 (18G6032) sshfs fails with 
```
kext load failed: -603946989
mount_osxfuse: the file system is not available (255)
```
tried most (?) combinations; brew (as before) than Stable Releases 3.11.2 + SSHFS and Beta 4.0.2
=> kext will not show up in kextstat, not in folder nor @ Settings > Security > General .. any ideas?

**Comment by xerc** [comment]
the first folder was fix'd via RecoveryMode (looks like the upgrade/SIP missed to change this)
`chflags restricted /private/var/db/KernelExtensionManagement`
```
$ ls -ldO /private/var/db/KernelExtensionManagement
drwxr-xr-x@ 3 root  wheel  restricted [..] /private/var/db/KernelExtensionManagement
$ ls -ldO /private/var/db/KernelExtensionManagement/Staging
drwxr-xr-x  2 root  wheel  restricted [..] /private/var/db/KernelExtensionManagement/Staging
```

**Comment by prantlf** [comment]
@xerc, you could run `sudo dmesg` right after `sshfs` failed. If you see this, there are no free virtual device slots on your machine:

    fuse: Failed to register major device number 

I [was able](https://github.com/osxfuse/osxfuse/issues/358#issuecomment-745572140) to free one slot when reading #358.

**Comment by xerc** [comment]
i saw it; go into Recv.Mode and execute the `chflags` command above - should fix this issue LT

**Comment by bfleischer** [comment]
This issue has been inactive for a long time, so I'm closing it. Feel free to open a new issue.
