### ISSUE TITLE
Missing 'Allow' pane in Security & Privacy after installing OSXFuse 3.10.3 on macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by calenz** [osxfuse/osxfuse#654]
After installing osxfuse-3.10.3.dmg on macOS Catalina 10.15.1, I am stuck at the last step of the installer, as the system extension required for mounting FUSE volumes could not be loaded. Opening Security & Privacy system preferences will take me to the General tab but there is no Allow button.

**Comment by tomisavolainen** [comment]
I encountered this as well today. No Allow button and developer name.

**Comment by bfleischer** [comment]
You are probably using a third-party tool that is able to generate input events. macOS will not display the "Allow" button in case a tool that is able to virtually press the button is running.

Some popular tools and hardware that might cause this are:

* BetterTouchTool 
* MagicPrefs
* Wacom Pro tablet
* Karabiner
* Chrome
* VLC
* Microsoft wireless mouse
* SONOS controller app

**Comment by tomisavolainen** [comment]
Actually we were able to fix this by restarting the OS :D

ke 4. jouluk. 2019 klo 17.10 Benjamin Fleischer <notifications@github.com>
kirjoitti:

**Comment by calenz** [comment]
I do have Chrome (but it's the most commonly used browser) but none of those apps that generate input events. I had temporarily deleted Chrome and restarted my MacBook but that still didn't work. I thought I had seen the Allow button before for some other apps on my system.

**Comment by bfleischer** [comment]
@calenz The above list of tools is not exhaustive. Screen sharing might cause the issue, too. You could try checking the log in Console app. See https://github.com/osxfuse/osxfuse/issues/437 for details.

**Comment by wawork** [comment]
I had the same issue just now. It appears that is due to the fact that I had 'System Preferences' open when installing the package. 
All I had to do was: closing 'System Preferences' while having the installer still open and than press the button for "Opening Security & Privacy" and there was the button to create an exception. 
Hope that helps, Walter

**Comment by jarrocha** [comment]
I have seen this issue before on Catalina. If you try installing a different program that triggers this it will show up. After that, you can try with the original program. I don't think this is an issue with osxfuse.

**Comment by Dodelo** [comment]
I would like to add that I encountered this issue on macOS Mojave 10.14.6, and that it was probably triggered by incorrect flags set on the folder /private/var/db/KernelExtensionManagement/Staging, some details are in this thread:
https://github.com/pqrs-org/Karabiner-Elements/issues/2373#issuecomment-745646992 
What fixed it for me was moving that folder to the Trash; since the user can't empty the trash I then had to boot into recovery and delete the trash from the terminal (this is also described in the linked thread, read it until the end).
