### ISSUE TITLE
Kernel Panic and autorestart in Catalina 10.15.1

### ISSUE THREAD

**Issue by pkhoueiry** [osxfuse/osxfuse#655]
I am experiencing kernel panics with autorestart following ssh or mount after upgrade to Catalina 10.15.1. I am suspecting fuse since filesystems.afpfs and filesystems.msdosfs and fileutile are among the top kext affected. 

Any hint?

**Comment by bfleischer** [comment]
Please post the actual panic log that is displayed after your Mac reboots. You should be able to find the previous panic logs in the Console app.

However, filesystems.afpfs and filesystems.msdosfs have nothing to do with FUSE.

**Comment by ar0ra1** [comment]
I updated OSXFuse to 3.10.4 and then updated Mac OS to 10.15.2

During the update process, I got Kernel Panic.

Also, since updating to Catalina, OSXFuse has been unreliable. 
Yesterday itself, I mounted my cloud and started using VScode over it. 
2 times, the connection was disconnected, all of the work done was lost, and it hung VSCode as well.

**Comment by bfleischer** [comment]
@ar0ra1 

Please post the panic log. Without the log there is nothing I can do.

Which file system are you using? Did you report the issue to the actual developer of the (third party) file system?

**Comment by bfleischer** [comment]
I'm going to close the issue due to the lack of feedback. Without panic logs or detailed repro steps there is nothing I can do.
