### ISSUE TITLE
Finder stop responding (everything stop responding) safe mode not even working

### ISSUE THREAD

**Issue by vincbeaulieu** [osxfuse/osxfuse#657]
After restarting my computer, my finder stop booting, it get stuck at loading. So I've uninstalled FuseOSX using safe mode and restarted the computer, and I had the same issues. So, I came back to safe mode but now, even in safe mode the finder does respond.

**Comment by bfleischer** [comment]
It is very unlikely FUSE for macOS is to blame for this. FUSE is a completely passive component. The FUSE kernel extension is not even loaded automatically on system starts. This means that, unless you are using an application, that mounts a FUSE volume on system starts, FUSE can in no way interfere with macOS starts.

The fact that the issue persists even after uninstalling FUSE suggests that the issue was not caused by FUSE in the first place. Maybe booting in recovery mode and running First Aid on your startup volume helps.

**Comment by vincbeaulieu** [comment]
Couldn't solve the issue on my session so I created another admin session and deleted my old session. On the new session, I am running the Beta version and it is running flawlessly. On my old session, I didn't run the uninstaller of the stable release prior to the installation of the Beta. I don't know if this is the cause of my issue, so I am mentioning it but, it can also be just a matter of circumstance. None the less, everything is working now. Thanks for replying!
