### ISSUE TITLE
osxfuse panic crash "osxfuse: What kind of a flag is this (4)?"

### ISSUE THREAD

**Issue by overflood** [osxfuse/osxfuse#669]
Running often into this attack. osxfuse seems to get used by seadrive / visual studio sometimes with (wrong?) commands.

```
panic(cpu 0 caller 0xffffff7fa17348c0): "osxfuse: What kind of a flag is this (4)?"@/Users/benjamin/Arbeit/FUSE/Repositories/osxfuse/kext/osxfuse/fuse_file.h:80
Backtrace (CPU 0), Frame : Return Address
0xffffffa407d13690 : 0xffffff801cd3bb1b 
0xffffffa407d136e0 : 0xffffff801ce733e5 
0xffffffa407d13720 : 0xffffff801ce64e5e 
0xffffffa407d13770 : 0xffffff801cce2a40 
0xffffffa407d13790 : 0xffffff801cd3b207 
0xffffffa407d13890 : 0xffffff801cd3b5eb 
0xffffffa407d138e0 : 0xffffff801d4d24f9 
0xffffffa407d13950 : 0xffffff7fa17348c0 
0xffffffa407d139f0 : 0xffffff7fa173187c 
0xffffffa407d13a20 : 0xffffff801cfcae30 
0xffffffa407d13aa0 : 0xffffff801cfb5479 
0xffffffa407d13d60 : 0xffffff801cfb4c70 
0xffffffa407d13f40 : 0xffffff801d39acba 
0xffffffa407d13fa0 : 0xffffff801cce3206 
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfuse(3.8.2)[7AA38E46-2C0C-39C5-B790-6451370874DA]@0xffffff7fa172a000->0xffffff7fa1743fff

BSD process name corresponding to current thread: mds_stores

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide:     0x000000001ca00000
Kernel text base: 0xffffff801cc00000
__HIB  text base: 0xffffff801cb00000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file available: YES (0x0)
```

**Comment by bfleischer** [comment]
You are using a very outdated version of FUSE. FUSE for macOS 3.8.2 does not support macOS Catalina. The kernel extension won't even load on Catalina unless someone messed with the install. This is causing the panic. Upgrade to the latest version of FUSE and the panic is gone.

**Comment by overflood** [comment]
Thanks @bfleischer , I've guessed it, but I've uninstalled FUSE everywhere where I can and its still on the system. How can I really uninstall it, when kext etc. were removed? Where is FUSE located in this case?

**Comment by creativeprojects** [comment]
I've had the issue today (again) even though I've installed the new version. It turns out that the old version was still loaded for some reason. I think Seadrive is packaging its own version of osxfuse like you can see:

% find /Applications/SeaDrive.app -name "*.kext"
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.8/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.6/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.7/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.9/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.10/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.5/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.14/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.13/osxfuse.kext
/Applications/SeaDrive.app/Contents/Resources/osxfuse.fs/Contents/Extensions/10.12/osxfuse.kext
%

You can check which version is currently loaded:

% kextstat | grep fuse
  183    0 0xffffff7f8490f000 0x19000    0x19000    com.github.osxfuse.filesystems.osxfuse (3.10.4) 184072A6-C133-38A8-84A5-E8A3BC937ADD <8 6 5 3 1>
%

Mine was 3.8.2 or something like that.

So I'm not sure which one fixed it, but here's how I did it:

- Quit the Seadrive app
- Quit VirtualBox which uses osxfuse as well
- Unload the existing kext: `sudo kextunload -b com.github.osxfuse.filesystems.osxfuse`
- Install the new version of Seadrive
- Install the new version of osxfuse
- Reboot

Then kextstat should display the latest version (3.10.4)

Good luck :p

**Comment by overflood** [comment]
Thank you @creativeprojects for this helpful tutorial! That was what I need. The clean unloading of the kext-file made it.
