### ISSUE TITLE
duplication of Macintosh HD during mount of SSHFS Volumes

### ISSUE THREAD

**Issue by vincbeaulieu** [osxfuse/osxfuse#687]
![Screen Shot 2020-03-22 at 4 29 29 AM](https://user-images.githubusercontent.com/37360448/77245559-c127ec00-6bf5-11ea-81a7-679c71c79a53.png)

The image speak by it self.

I'm using the latest version of FUSE and SSHFS on mojave.

I relaunched Finder but it did not solve the issue.

**Comment by bfleischer** [comment]
I highly doubt this is caused by FUSE.

**Comment by vincbeaulieu** [comment]
Well it only happened when I mounted Fuse and it was every time. Then when I restarted the computer, the admin session I was using was now corrupted. I had to go create a new admin account from the guest account. Every single time that I used SSHFS. I have uninstalled it, and reinstalled it, and I was still having the same issues. The only way I manage to stop getting those issue is by stopping using it. Which I found it sad because I really liked your software.

**Comment by bfleischer** [comment]
FUSE does not create items in the Finder's sidebar. FUSE does not contain any code to do so. You the only one who reported this issue. This makes me believe it is caused by something on your Mac or the way you are using SSHFS.

Unless you overlay any system folders in your user account or the Volumes folder with your mount point I don't see how using FUSE could corrupt your user account. You did not provide any information besides the screenshot. The specific SSHFS command might have held some clues.

**Comment by vincbeaulieu** [comment]
You are probably right. If I ever come back to the app I'll be more specific went encountering such an issue. But I really appreciate that you have given feedback.
