### ISSUE TITLE
The operation can't be completed because an unexpected error occurred (error code 100096).

### ISSUE THREAD

**Issue by EverlyScott** [osxfuse/osxfuse#704]
(This might be an issue with NTFS-3G... I would post it to their forums but I cannot figure out how to make an account on their forum software from 2001)

I just installed OSXFuse and ntfs-3g on my Hackintosh running Catalina 10.15.4 so I can read and write to my Windows drives on macOS, but I'm getting this error when trying to copy any file to an NTFS drive:
```
The operation can't be completed because an unexpected error occurred (error code 100096).
```
If I click OK, the dialogue box goes away, but there is an empty file left in the place I was copying it to that is only visible to terminal (even with hidden files enabled in Finder)

It seems like I can create and edit files with Terminal, so this might be an issue with how the FInder interacts with an NTFS drive

**Comment by bfleischer** [comment]
I'm sorry, but I cannot help you with that. Please report NTFS-3G issues to the NTFS-3G team.

**Comment by ghost** [comment]
Can reproduce. This seems to be POSIXErrorENODATA, aka the "No message available on STREAM" stuff. So similar to osxfuse/osxfuse#703.

Mounting with NTFS-3G's native xattr turned off but using `auto_xattr` makes it work, so the issue is likely in the xattr handling of ntfs-3g itself. Using the `-o debug` option shows finder and spotlight requesting a bunch of non-existing attributes.

Comparing the Linux and macOS manpages for getxattr(2), the issue seems to be that macOS does not define `ENOATTR` (93) as the same as `ENODATA` (96), but using a separate error code instead. NTFS-3G only uses ENODATA, and that confuses macOS.

I popped a message onto their [mailing list](https://sourceforge.net/p/ntfs-3g/mailman/message/37088187/).

(Oops this is not my account.)

**Comment by rickygm** [comment]
I have the same problem with Catalina 10.15.7, when it is copying a file to a drive it gives me that error 100096.

any news?

**Comment by Diaz1999** [comment]
> I have the same problem with Catalina 10.15.7, when it is copying a file to a drive it gives me that error 100096.
> 
> any news?

not that I know of. the notice at the bottom of the NTFS-3G wiki here is still in place, so I guess no.
> Note 2: NTFS-3G had a bug that prevents macOS from understanding when an attribute is missing. A fix is available, but it is yet to be included in a release.
