### ISSUE TITLE
Installation using MacPorts and on Automount on Big Sur

### ISSUE THREAD

**Issue by knightjp** [osxfuse/osxfuse#759]
I am trying to edit the NTFS-3g after installing it. Following the instructions from the site below.

https://trac.macports.org/wiki/howto/Ntfs3gFinder

But even though I try the following like I did for Catalina, "`sudo mount -uw /`"

But I get this error...

```
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
```
I tried disabling SIP, but that does not work either. After disabling SIP, when I do this command,

`sudo mv /sbin/mount_ntfs /sbin/mount_ntfs.orig`
I get this error,

`mv: rename /sbin/mount_ntfs to /sbin/mount_ntfs.orig: Read-only file system`

Can anyone help? I really want to be able to automount NTFS with read-write.

**Comment by Artoria2e5** [comment]
I added a section on https://github.com/osxfuse/osxfuse/wiki/NTFS-3G#big-sur-and-the-ssv to talk about how effed up SSV makes things now. I think the way forward is to write a `/Library/Filesystems/ntfs_3g.fs/Contents/Info.plist` instead of doing file replacement, but in typical Apple fashion none of that is documented.

(To be really fair, file replacement has always been a big hack...)

**Comment by zhylmzr** [comment]
I write a script for automount only need to disable SIP
https://gist.github.com/zhylmzr/8d83b7171ea9ec2936c0f14c69e56208
