### ISSUE TITLE
Unable to install ntfs-3g using MacPorts

### ISSUE THREAD

**Issue by knightjp** [osxfuse/osxfuse#762]
When I try to install ntsf-3g on MacPorts, I get this. 
```
Error: Failed to build osxfuse: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port ntfs-3g failed
```

**Comment by Coeur** [comment]
Returning to macFUSE 3.x seems to solve the compatibility issue for now.
NTFS-3G doesn't seem to work with macFUSE 4.x (yet?), which might not be so surprising since its last release was apparently [nearly 4 years ago](https://www.tuxera.com/community/ntfs-3g-release-history/). There is still activity on the repository (from 2 months ago), so maybe one of the devs will do something about it? https://www.tuxera.com/company/open-source/

**Comment by bfleischer** [comment]
@knightjp MacPorts does not ship the latest version of macFUSE. I recommend downloading the installer from https://osxfuse.github.io. Please raise the issue with MacPorts.
