### ISSUE TITLE
Closed source is harming other open source projects

### ISSUE THREAD

**Issue by DeadlySurgeon** [osxfuse/osxfuse#771]
First off, I acknowledge that I'm very late to the party on this, but I only really started needing fuze for one of my new projects recently.

I fully understand the struggle of having to support a project, unpaid, but there is something that I don't understand. Why closed source? You said that it's because companies keep using your software without any upstream compensation, but you don't need the software closed source to enforce this. MongoDB is a good example where they keep the project open yet are able to charge for the software. Plus, your license doesn't prevent commercial software to keep taking advantage of your efforts, rather it just will have commercial software point their users to point to your download page, so in the end you're just hurting other open source efforts.

Mac Support Fully Killed
https://github.com/bazil/fuse/issues/224

Support for OSXFuse slowed/made harder
https://github.com/hanwen/go-fuse/issues/379#issuecomment-743747044

Also in another note, just out of my own curiosity, since you've made this project closed source, have you achieved your goals? Have companies using your software stepped forward and contributed back or helped fund you?

**Comment by DeadlySurgeon** [comment]
I unfortunately don't have much time to deal with this further, and it's put my personal project on hold probably indefinately, but if I have time I plan on going around to other open source projects that have either died or dropped Mac support and posting them here.

**Comment by bfleischer** [comment]
> I fully understand the struggle of having to support a project, unpaid, but there is something that I don't understand. Why closed source?

macFUSE has been open source for many years and was covered under a BSD license. As a result the project was forked numerous times. Several companies maintained their own rebranded forks of FUSE. With every new macFUSE release they would merge the upstream changes into their private repositories and "put their name" on it without contributing to the effort. 

I doubt changing the license, without going closed source, would have the same impact. Continuing macFUSE as an "open source" project with a less permissive license would have given everyone the required information to update their respective private forks of macFUSE and it would have been impossible for me to prevent this from happening.

The situation is different for "open source" projects using a license that prevents commercial use from the start. In this scenario it is clear that everyone forking their repository for commercial use is in breach of the license.

> Plus, your license doesn't prevent commercial software to keep taking advantage of your efforts, rather it just will have commercial software point their users to point to your download page, so in the end you're just hurting other open source efforts.

Disallowing commercial use altogether is not an option, because it would mean that nobody would be allowed to use (free) tools that are based on macFUSE for work purposes. One popular example is sshfs. This is definitely not what I am aiming for.

I want companies, that are distributing commercial software, that is based on macFUSE, to invest some of the profits in the continued development of FUSE on macOS. I do not want to prevent individuals from using FUSE, no matter if the use is for-profit or not.

When researching this, I did not find any suitable pre-existing licenses. That's why I modified the current license and I wanted to keep things simple. As a result the macFUSE license errors on the side of being a bit more permissive. I am aware of this loophole.

> Mac Support Fully Killed
> bazil/fuse#224
>
> Support for OSXFuse slowed/made harder
> hanwen/go-fuse#379 (comment)

One component of the macFUSE package is libfuse. libfuse originates on Linux and is covered under the LGPL license. The macFUSE version of libfuse is open source and can be found on https://github.com/osxfuse/fuse. 

Every piece of information needed by the above two projects can be found there. Furthermore I would like to add that the "new mount" process on macOS works the same way as it does on Linux. The old one was non-standard and required special handling. I implemented the new mechanism back in 2016 in version 3.3.0 (https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.3.0) and the relevant code is open source. In version 4.0.0, almost 4 years later, I simply removed the deprecated code for the old non-standard mechanism. Third party projects had plenty of time to add support for the "new" mechanism, which should even allow them to remove macOS-specific code.

I would like to add, that I have not been contacted by any of the maintainers of the respective projects. I would be happy to help get things working and I fully support (non-commercial) open source efforts whenever I can.

That being said, it is true that there are some differences between FUSE on macOS and FUSE on Linux. However, these differences are a result of the VFS layer of the macOS kernel being very different from the Linux implementation in some regards. macFUSE contains a lot of code to bridge this gap, but in some cases FUSE has to behave a bit differently on macOS than on Linux. But these minor deviations are all within the wiggle room allowed by libfuse, the FUSE user-space reference implementation.

> Also in another note, just out of my own curiosity, since you've made this project closed source, have you achieved your goals? Have companies using your software stepped forward and contributed back or helped fund you?

Several companies have stepped forward. Without this support, I would not have been able to keep the project alive or add support for macOS 11 and Apple Silicon. In this regard it has been a great success.

**Comment by krim404** [comment]
Changing to closed source has a major impact on the way other open source projects will handle osxfuse. They will see it as non trustworthy and this way it will not be supported anymore. And tbh - as an end user i also have a bad feeling to install this software, knowing that noone can evaluate the trustworthyness.

Sadly, companies who bundled osxfuse in the past will not change their behaviour. Fuse is a compatibility feature for OSX, not a mandatory element. If i would use osxfuse as a dependency in my commercial software, i would simply reimplement the official OSX APIs instead using a closed, external and pricey compatibility layer. 

So overall, this is a loose loose situation, which - in best case - will result in a short income till the transition to the native apis is finished.

I think this discussion is now far too late, as the trust of the overall OSS-Community in @bfleischer is now massively disturbed.

**Comment by bfleischer** [comment]
> Sadly, companies who bundled osxfuse in the past will not change their behaviour. Fuse is a compatibility feature for OSX, not a mandatory element. If i would use osxfuse as a dependency in my commercial software, i would simply reimplement the official OSX APIs instead using a closed, external and pricey compatibility layer.

The are no "official OSX APIs" that would allow you to implement a full-featured file system in user-space. But this is not really the point here.

> I think this discussion is now far too late, as the trust of the overall OSS-Community in @bfleischer is now massively disturbed.

Going closed source was not a rash decision. I've been asking for any form of support for years before that, but nothing much came of it. There were only two options, abandon the project or find a way to get the required funding, so that I can keep working on it.

What would you have done in this situation?

**Comment by DeadlySurgeon** [comment]
First, thank you for the well written out response. I found it very informative and I appreciate you taking out the time for me.

> Disallowing commercial use altogether is not an option, because it would mean that nobody would be allowed to use (free) tools that are based on macFUSE for work purposes. One popular example is sshfs. This is definitely not what I am aiming for.

I suppose that's rather fair, I didn't think about that.

> I would like to add, that I have not been contacted by any of the maintainers of the respective projects. I would be happy to help get things working and I fully support (non-commercial) open source efforts whenever I can.

This very much bothers me if [bazil/fuse](https://github.com/bazil/fuse) didn't even put in any effort into working with you.

> Several companies have stepped forward. Without this support, I would not have been able to keep the project alive or add support for macOS 11 and Apple Silicon. In this regard it has been a great success.

Then I'm glad you took the path that you did. Thank you for your contributions, even if your code isn't open source. Sometimes sacrifices have to be made and it sucks that they had to be made here.

> noone can evaluate the trustworthyness.

Ask for an Audit to be performed, if you care that much tbh.

> So overall, this is a loose loose situation, which - in best case - will result in a short income till the transition to the native apis is finished.

There aren't "native apis" for this functionality which is why it is such a big deal and why there aren't any other replacements for osxfuse, at least none that I can really see.

**Comment by DeadlySurgeon** [comment]
Closing this question as I got the answers to my question. Thanks!

**Comment by WGroleau** [comment]
Here you are saying it's closed source, yet the installer asked me to agree to a license that allowed me to use, modify, or distribute the code if I don't change the copyright.

**Comment by Pysis868** [comment]
This one? https://github.com/osxfuse/osxfuse/blob/releases/LICENSE.txt

Must be a comprehensive one where only some cases may apply, but could  apply in the future and is easy to use in whole without harm.

**Comment by WGroleau** [comment]
I'm not going to download another installer just to compare.  But I do recall that the license it showed to me was NOT closed source.

**Comment by bfleischer** [comment]
@Pysis868 That's the license that is displayed by the installer

@WGroleau Only parts of the macFUSE code base are closed source. The license does not make a statement regarding the availability of the complete code base. It's a standard BSD license with an additional clause that disallows some cases of commercial use without specific prior written permission.

**Comment by GwynethLlewelyn** [comment]
Piping in a bit late but...

.. now, it should be possible to use @anacrolix's own fork of bazil/fuse, which is a drop-in replacement (no code changes necessary) which provides the exact same functionality — plus working macFUSE 4+ support.

You can get it from here: https://github.com/anacrolix/fuse
