### ISSUE TITLE
Fuse produces error 'something went wrong while installing FUSE for MacOS'

### ISSUE THREAD

**Issue by deravade** [osxfuse/osxfuse#780]
I installed Fuse 3.11.2 (and later also 4.0.5) on MacOs 11.0.1 (Big Sur). Installation seems to go fine, but later it produces an error. 

![Something went wrong while installing FUSE for macos](https://user-images.githubusercontent.com/75120259/106394194-a02a4d00-63fb-11eb-8957-e7acf718fe71.jpg)

Restarting computer as suggested in the error message (attached) and also un & reinstalling doesn't help at all.

This error is triggered after trying to enable the 'direct file open' option in Tresorit.

**Comment by bfleischer** [comment]
The error message is displayed by Tresorit, not macFUSE. Please raise the issue with the Tresorit team.

Please know that Tresorit is not contributing to the continued development of the macFUSE software. I asked the Tresorit team for financial support, in order to be able to continue maintaining macFUSE in the future, but they declined. I'm sorry, but I cannot provide support for Tresorit issues.

**Comment by deravade** [comment]
Although it’s displayed by Tresorit that doesn’t necessarily mean it’s a bug in Tresorit. That’s why i logged the issue on Github.

I’m sorry to hear Tresorit declined your request. I’ve passed your response to Tresorit. Let’s see what they come back with.
