### ISSUE TITLE
Benjamin Fleischer Extension Won't show "allowed" button on Mac Pro running mojave 10.14.6

### ISSUE THREAD

**Issue by antoniobcii** [osxfuse/osxfuse#783]
I am running Yoyotta V 3.0 LTO back up on a MacPro 13 running mojave 10.14.6. I installed macfuse version 4.0.5 and when I try to run a back up it gives me an error message (pic attached) saying that the system extension is blocked and that I need to approve it in the preference panel. 

When I go there there's no "allow" button. I tried uninstalling and rebooting, then installing again and rebooting again but same results. Any suggestions? Thank you

![Screen Shot 2021-02-04 at 10 31 52 AM](https://user-images.githubusercontent.com/78565548/106952644-3a351280-66e6-11eb-887e-06dc241298a6.png)

**Comment by lipo2lipo** [comment]
Same problem here. MacOS 10.14.6 incl. all updates, lates MacFUSE. With SIP disabled, extension allowance request does not appear, Veracrypt works fine. With SIP enabled, extension notice appears, when I click the "Show Preferences ...", Preferences -> Security-> General window appears, but nowhere is mentioned Benjamin Fleischer extension, therefore no Allow button.
In High Sierra it worked fine, did update to Mojave yesterday and from that time Veracrypt stopper working saying "No filesystem ..."

**Comment by bfleischer** [comment]
macOS might not display the allow button in case you are using third-party tools, that are capable of generating input events (mouse clicks or keyboard events). This is a security feature to make sure that the user clicks the allow button and not an app. See the following tickets:

https://github.com/osxfuse/osxfuse/issues/654
https://github.com/osxfuse/osxfuse/issues/437

**Comment by lipo2lipo** [comment]
Solution found - the one mentioned in #741 (https://github.com/osxfuse/osxfuse/issues/741#issuecomment-752318425)
helped - I did delete  directory "/private/var/db/KernelExtensionManagement" and it was recreated by system again. Once mounting a container in Veracrypt - button Allow appeared in System preferences/Security/General and was able to click it. Now Veracrypt works again with SIP enabled.

**Comment by bfleischer** [comment]
Thanks for posting the solution.

**Comment by gmuth** [comment]
"Allow" does not appear because the system finds a "true" already in the KextPolicy db.
It first looked like a bug of Apple's kext security management when still not loading the kext but at the same time not showing the option to enable the kext.

In my case the kext has been enabled when running macOS HighSierra. After upgrading to Mojave (and macfuse) I was unable to use sshfs and no "Allow" appeared. Deleting /private/var/db/KernelExtensionManagement helped!

I had saved the security settings before and was able to compare the new settings after the "Allow" appeared and was accepted:

before:
```
'3T5GSNBU6W','com.github.osxfuse.filesystems.osxfuse',1,'Benjamin Fleischer',8
```
after:
```
'3T5GSNBU6W','com.github.osxfuse.filesystems.osxfuse',1,'Benjamin Fleischer',12
'3T5GSNBU6W','io.macfuse.filesystems.macfuse',1,'Benjamin Fleischer',1
```

I can see other flags (what are the meanings of bits 8 and 4?) and an extra bundle_id.
So the reason might be using an old id which relates to  an old security setting. .. just guessing.

An alternative solution could be to (manually) change the flag from 8 to 12 via update:

```
update kext_policy set flags=12 where bundle_id='com.github.osxfuse.filesystems.osxfuse'
```
