### ISSUE TITLE
Feature request: "device type" mount option

### ISSUE THREAD

**Issue by NSExceptional** [osxfuse/osxfuse#784]
I see there is a `volicon` mount option for specifying a (static) icon, which is nice, but there is no way to get a dynamic icon that tints itself properly in light-mode or dark-mode like the sidebar icons do in Finder. These are the icons I'm referring to:

<img width="186" alt="Screenshot 2021-02-04 at 1 41 49 PM" src="https://user-images.githubusercontent.com/8371943/106967552-fbff1980-670c-11eb-8a19-00e507e4d25c.png">

If I find the "iphone" icon and set it myself with `volicon`, it ends up looking like this:

<img width="187" alt="Screenshot 2021-02-04 at 5 18 47 PM" src="https://user-images.githubusercontent.com/8371943/106967587-0caf8f80-670d-11eb-8ba1-16318ce87643.png">

The drive icon itself also looks like a blown-up version of that very tiny icon, which is not ideal.

Ideally, I want to be able to specify a device model or device type (iPhone, other mac, printer, removable disk, etc) and have Finder show the appropriate icon in the sidebar, while allowing me to still specify the "desktop" icon via `volicon`. I assume there is not a way to do this already, as I didn't see anything like it in the wiki

**Comment by bfleischer** [comment]
I'm not aware of any way to pass a device type to macOS so that Finder picks the device icon that would like it to display. 

The `volicon` option uses a file system "overlay" and places the volume icon on the FUSE volume under `/.VolumeIcon.icns`. Finder checks this path when it is looking for the volume's icon. From what I've read it is possible to package light and dark variants of an icon in the same `.icns` file. Apple certainly does this. I have not tested it myself, but it might be possible doing this by passing an  asset catalog (`.car` file) and the name of the icon to `iconutil`.
