### ISSUE TITLE
Clarify naming & versions

### ISSUE THREAD

**Issue by Timmmm** [osxfuse/osxfuse#796]
So as I understand it originally there was [macFUSE](https://code.google.com/archive/p/macfuse/), which was followed by *osxfuse*, which is possibly also known as [*FUSE for MacOS*](https://github.com/osxfuse/osxfuse/tree/master#fuse-for-macos)? If you follow the [FUSE for macOS Project](http://osxfuse.github.io/) link in that Readme it takes you to `osxfuse.github.io` and the page is all about *macFUSE*! What?!

Ok next if we go to [this project's Github page](https://github.com/osxfuse/osxfuse) it defaults to the `release` branch which is a little confusing. It also calls the project *macFUSE* and [the latest release](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.1.0) is from 26 days ago, but if you check the `master` branch it hasn't been updated in 4 years? What?!

I also need [sshfs](https://github.com/osxfuse/sshfs) but that copy seems to be 4 years old. Do I have to use that old version or can I use the much newer [upstream version](https://github.com/libfuse/sshfs)? I would have guessed the upstream version doesn't work on Mac but as mentioned in [this issue](https://github.com/osxfuse/sshfs/issues/64) one of the recent upstream sshfs releases says it improves performance on OSX!

Very confusing!

**Comment by bfleischer** [comment]
> So as I understand it originally there was macFUSE, which was followed by osxfuse, which is possibly also known as FUSE for MacOS? If you follow the FUSE for macOS Project link in that Readme it takes you to osxfuse.github.io and the page is all about macFUSE! What?!

There was Google MacFUSE, which died more than a decade ago. I forked the project and continued working on it under the name "FUSE for OS X/macOS" and used osxfuse as the identifier for the GitHub organization. The original Google MacFUSE maintainer asked me to use a different name than MacFUSE, because it was highly associated with Google.

When I started working on the project, Apple used the term OS X. Some time ago Apple rebranded OS X as macOS and with Google MacFUSE beening dead for more than a decade, we are back to the catchier name macFUSE (since version 4.0).

> Ok next if we go to this project's Github page it defaults to the release branch which is a little confusing. It also calls the project macFUSE and the latest release is from 26 days ago, but if you check the master branch it hasn't been updated in 4 years? What?!

Since version 3.9.0 some components of macFUSE are no longer open source. The FUSE user space library (libfuse) is open source and can be found on https://github.com/osxfuse/fuse. The README file in the release branch states:

_The source code of the last full open source release can be found in the support/osxfuse-3 branch of this repository._

> I also need sshfs but that copy seems to be 4 years old. Do I have to use that old version or can I use the much newer upstream version?

macFUSE ships with libfuse 2. This means you cannot use any version of sshfs that requires libfuse 3, i.e. sshfs 3.x.

>  I would have guessed the upstream version doesn't work on Mac but as mentioned in this issue one of the recent upstream sshfs releases says it improves performance on OSX!

Feel free to raise this question upstream.

**Comment by Timmmm** [comment]
Ah very clear, thanks! Maybe worth adding to the readme/website.
