### ISSUE TITLE
OS X 10.14.6 "Allow" security button never appears

### ISSUE THREAD

**Issue by GeigerPost** [osxfuse/osxfuse#798]
I cannot, for the life of me, get FUSE approved on this one machine. 
MacPro2013 running 10.14.6.
The SysPrefs "Allow" button never appears.

Steps attempted:

1. Close SysPrefs, reopen

2. Switch to other tabs, return to the General tab

3. Reboot

4. Uninstall using the Extras/uninstaller app; reboot, reinstall

5. Uninstall using the SysPrefs pane; reboot, reinstall

6. Check System Information > Disabled Software. No entries there.

7. sudo touch /Library/Extensions
 sudo touch /Library/Frameworks
 sudo touch /Library/Filesystems
Wait; check; Reboot

8. spctl kext-consent add 3T5GSNBU6W
          [spctl: failed to store new configuration.]

— No change.

Querying /var/db/SystemPolicyConfiguration/KextPolicy . kext_load_history_v3 with sqlite3 does show an entry:

/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext|com.github.osxfuse.filesystems.osxfuse|3T5GSNBU6W|ACB......E10|2020-08-16 21:38:52|2021-04-12 20:40:00|21

**Comment by E-Baler** [comment]
Hello same problem here same Mac OS version mbp 15 late 2015!

**Comment by TraceyC77** [comment]
I've also got this problem on a new MacBook after transferring my account from another one via Migration Assistant.
MacFUSE (an older version) was installed successfully on the old machine and I was able to use it normally
The first time I tried to mount an sshfs volume, I got the prompt to allow the extension in the Security & Privacy System Preferences pane. There is no "Allow" button there.

I don't have access to recovery mode, since this laptop is owned by my employer and they have locked that down.

I have tried running the uninstaller via System Preferences - MacFUSE. That allows me to remove the software, but after reinstalling, the problem is the same.

Currently  installed MacFUSE version 4.1.2
MacOS Catalina 10.15.7

**Comment by bfleischer** [comment]
Assuming file permissions are not damaged, this issue in most likely caused by a third-party tool that is able to generate mouse or keyboard input events. If such a tool is loaded macOS does not display the Allow button as a security measure to make sure that the button click is not automated. So your best option is disabling all such tools, restarting your Mac and then trying to load macFUSE again.

**Comment by TraceyC77** [comment]
I tried what you suggested, but the problem persists. The only software I know of on this laptop that would qualify as generating mouse & keyboard input events are aText (text expander) and PresButan (allow delete in Finder with Delete key).

I'm not sure what you meant by "disabling", or how any of the problematic software would be completely disabled for this purpose. I uninstalled PresButan and aText. I also went into Accessibility options and disabled aText as well as the Logitech software to be on the safe side. After rebooting, there is still no Allow button in the security preference dialog.

**Comment by rvazquezglez** [comment]
I'm having the same issue on 10.15.7 (Catalina).

I tried disabling all apps on Accessibility and Input Monitoring (and restarting) but got the same result.
![image](https://user-images.githubusercontent.com/373814/119574345-37d0f400-bd7b-11eb-924b-71df5eb3c222.png)

**Comment by sainadfensi** [comment]
same problem here after upgrading the system. Has anyone solved it ?

**Comment by FGasper** [comment]
Same issue here on 10.14.6 with 4.1.2 and 4.2.0 both.

**Comment by bgruberg** [comment]
I had a similar issue when updating my system from macOS Catalina to Big Sur. I have gone through the steps listed above without success. Has anyone had success with solving this issue?

**Comment by bfleischer** [comment]
Similar issues: https://github.com/osxfuse/osxfuse/issues/654, https://github.com/osxfuse/osxfuse/issues/437, https://github.com/osxfuse/osxfuse/issues/667, https://github.com/osxfuse/osxfuse/issues/783

**Comment by bfleischer** [comment]
This issue has bee inactive for a long time, so I'm closing it. For future reference, see https://github.com/macfuse/macfuse/wiki/Getting-Started for instructions on enabling the macFUSE kernel extension.
