### ISSUE TITLE
Operation not supported on socket

### ISSUE THREAD

**Issue by pratapaprasanna** [osxfuse/osxfuse#812]
Hi all, 

I have been trying to mount a directory onto my mac book 
version: MacOs Catalina 10.15.7
 
```
sshfs kb@s-kb:/test3 temp_write
```
I see that the directory is mounted and things are fine.

However, post that I can only create a directory if I copy a directory only directory structure gets created but the files won't go in and I cannot create/copy a file

<img width="659" alt="Screenshot 2021-05-13 at 2 06 36 AM" src="https://user-images.githubusercontent.com/15846947/118040954-da5aa180-b38f-11eb-878e-470ca2123d1b.png">

Should I be adding any options to the sshfs command am I missing anything?
Any help would be of great use

Thanks in advance

**Comment by pratapaprasanna** [comment]
attaching sshfs logs for your convenience 

```
touch three.txt
```

```
unique: 3, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 855
getattr /
   unique: 3, success, outsize: 136
unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 10975
LOOKUP /three.txt
getattr /three.txt
   unique: 4, error: -2 (No such file or directory), outsize: 16
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 796
getxattr / com.apple.FinderInfo 32 0
   unique: 2, success, outsize: 48
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 10975
LOOKUP /three.txt
getattr /three.txt
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 4, opcode: CREATE (35), nodeid: 1, insize: 66, pid: 10975
create flags: 0xa02 /three.txt 0100644 umask=0000
   unique: 4, error: -102 (Operation not supported on socket), outsize: 16
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 796
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 2, error: -45 (Operation not supported), outsize: 16
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 796
LOOKUP /._.
getattr /._.
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 10977
getattr /
   unique: 4, success, outsize: 136
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 136
LOOKUP /three.txt
getattr /three.txt
   unique: 2, error: -2 (No such file or directory), outsize: 16
unique: 3, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 10977
opendir flags: 0x0 /
   opendir[0] flags: 0x0 /
   unique: 3, success, outsize: 32
unique: 4, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 10977
releasedir[0] flags: 0x0
   unique: 4, success, outsize: 16
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 796
getattr /
   unique: 2, success, outsize: 136
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 796
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 3, error: -45 (Operation not supported), outsize: 16
unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 796
LOOKUP /._.
getattr /._.
   unique: 4, error: -2 (No such file or directory), outsize: 16
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 10977
LOOKUP /.git
getattr /.git
   unique: 2, error: -2 (No such file or directory), outsize: 16
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 796
statfs /
unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 10977
LOOKUP /.git
getattr /.git
   unique: 3, success, outsize: 96
   unique: 4, error: -2 (No such file or directory), outsize: 16
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 10977
LOOKUP /HEAD
getattr /HEAD
   unique: 2, error: -2 (No such file or directory), outsize: 16
```

**Comment by k4r1** [comment]
It might be worth raising this with https://github.com/osxfuse/sshfs/ first - although since this issue is only present on Mac OS it may well point to the underlying issue being with `osxfuse`.

FWIW this is the behaviour I'm seeing:
```bash
$ sshfs $SFTP_USERNAME@$SFTP_SERVER:/ test-mount
$ mkdir test-mount/test-dir    # Works fine
$ touch test-mount/test-file   # Fails
touch: test-mount/test-file: Operation not supported on socket
```

Other things of note:
- The SFTP server @pratapaprasanna is talking about is a managed AWS Transfer Server, as such we are [not able to configure](https://unix.stackexchange.com/questions/513935/aws-transfer-for-sftp-increase-sftp-session-timeout-from-server) sshd/sftp on the server side.
- Editing an existing file within an sshfs mount **does** work, but creating a new file does not
- Connecting directly to the server using `sftp` and issuing a `put` does work, as does uploading via CyberDuck, as does creating the file via an sshfs mount on Linux.

Versions:
- `sshfs`: 2.5.0
- `osxfuse`: 4.1.0
- `mac os`: 11.2.3

**Comment by bfleischer** [comment]
> unique: 4, opcode: CREATE (35), nodeid: 1, insize: 66, pid: 10975
> create flags: 0xa02 /three.txt 0100644 umask=0000
>    unique: 4, error: -102 (Operation not supported on socket), outsize: 16

According to the logged request above,  sshfs returned `EOPNOTSUPP` to the `FUSE_CREATE` request. This looks like an sshfs issues rather than a macFUSE issue, or at the very least an issue that should to be investigated on the sshfs end. I'm not sure which SFTP command `FUSE_CREATE` is translated to. Maybe the SFTP command is not supported by the server.

This ticket has been inactive for a long time, so I'm closing it. Feel free to re-open the ticket in case this is still an issue and you think macFUSE is to blame.
