### ISSUE TITLE
Update to support macOS 12

### ISSUE THREAD

**Issue by Scvairy** [osxfuse/osxfuse#821]
Looks like it has software restriction for major macOS updates. When will it updated? =)
<img width="372" alt="Screen Shot 2021-06-08 at 11 18 51" src="https://user-images.githubusercontent.com/8327460/121133048-4fb07980-c84b-11eb-92d3-904d5176effa.png">

**Comment by dohe0342** [comment]
please 😭

**Comment by macos120** [comment]
please please please please please

**Comment by bfleischer** [comment]
Working on it. Be patient.

**Comment by misku** [comment]
@macos120 

> please please please please please

Did you actually join github 20 minutes ago just to write this comment? 🤣

**Comment by macos120** [comment]
Hi

I certainly did

Cannot upgade and test without fuse

________________________________

**Comment by sciencegirl100** [comment]
Lol, I want to use VSCode to work on stuff, but that needs my SSH keys....
My SSH keys are stored in KeyBase... which can't install filesystem support on M1 Monterey...
So I need to install the latest Fuse... 

Yeah, I'm eagerly waiting for this.

**Comment by GPopZach** [comment]
> Working on it. Be patient.

Is there an ETA on this? If not, would you consider releasing the source for 4.1.2 so I can make the necessary changes myself? I'd like KBFS to work on my development machine, and I'm more than happy to save you the work as I'm off the next couple weeks myself.

**Comment by GPopZach** [comment]
> > Working on it. Be patient.
> 
> Is there an ETA on this? If not, would you consider releasing the source for 4.1.2 so I can make the necessary changes myself? I'd like KBFS to work on my development machine, and I'm more than happy to save you the work as I'm off the next couple weeks myself.

@bfleischer 
Soooo, I'm guessing the whole "oh if another developer experienced in kext development would help I'd be glad but nobody will" is a load of crap? I've been writing kernelspace code for 15 years, and I'm happy to help you with the laundry list of modernization work you listed a while back, and I expect zero monetary compensation. All I ask in return is that you let me fix mah damn Keybase integration without needlessly shitting out code you already wrote 5 years ago. I value my time more than that, and you could definitely benefit from doing the same.

**Comment by bfleischer** [comment]
The new macFUSE 4.2.0 release adds experimental support for macOS 12. In case you run into any issues on macOS 12, please open a new ticket.

**Comment by bfleischer** [comment]
@Zachpocalypse

Thanks for offering to help.

> Soooo, I'm guessing the whole "oh if another developer experienced in kext development would help I'd be glad but nobody will" is a load of crap?

You are taking my two-year-old comment out of context. Back when macFUSE was still open source, I was looking for help, but there were no regular contributors besides me. Long story short, the only remaining option was going closed source to improve the project's funding so that I could spend more time working on it. I accepted that this would prevent others from contributing code to the closed source components. 

> I'm off the next couple weeks myself.

What happens after your off time ends, when you have less time to spare?

I will not release the source code of the kernel extension and risk the project's funding in hope that it might turn out differently this time. However, there are areas you could help with, e.g. the open source components of macFUSE, if you are interested.

**Comment by GPopZach** [comment]
> @Zachpocalypse
> 
> Thanks for offering to help.
> 
> > Soooo, I'm guessing the whole "oh if another developer experienced in kext development would help I'd be glad but nobody will" is a load of crap?
> 
> You are taking my two-year-old comment out of context. Back when macFUSE was still open source, I was looking for help, but there were no regular contributors besides me. Long story short, the only remaining option was going closed source to improve the project's funding so that I could spend more time working on it. I accepted that this would prevent others from contributing code to the closed source components.
> 
> > I'm off the next couple weeks myself.
> 
> What happens after your off time ends, when you have less time to spare?
> 
> I will not release the source code of the kernel extension and risk the project's funding in hope that it might turn out differently this time. However, there are areas you could help with, e.g. the open source components of macFUSE, if you are interested.

I'm sorry, I believe you misunderstood me, I was only offering help as far as updating osxfuse to run on macOS Monterey, not making a commitment to help out long-term. As you've moved to a for-profit model, I'd think it goes without saying I'm not going to be taking on any financial strain the project maintainer was not willing to.

I don't disagree with you looking to make a living off your work, I'm just asking you to let me fix it myself if you can't do so in a timely fashion, but you've done so, so it's a moot point. Also: I was offering to turn those code contributions back to you, closed-source, not release them myself.

**Comment by cdevers-es** [comment]
> The new macFUSE 4.2.0 release adds experimental support for macOS 12. In case you run into any issues on macOS 12, please open a new ticket.

Can you please comment on the status of macFUSE’s use of kernel extensions (kexts) in macOS 12 Monterey?

I’m looking at Apple’s [Deprecated Kernel Extensions and System Extension Alternatives](https://developer.apple.com/support/kernel-extensions/) article, as well as 
[ZDNet | Apple deprecating macOS kernel extensions (KEXTs) is a great win for security](https://www.zdnet.com/article/apple-deprecating-macos-kernel-extensions-kexts-is-a-great-win-for-security/), and it sounds like the message is that Apple wants to phase out support for kernel extensions, and have developers migrate to [System extensions](https://developer.apple.com/system-extensions/) instead. 

Is this going to impact macFUSE? Is there a risk that macFUSE 4.2.0 will cease to function if a (near) future macOS version drops kext support?

[I haven’t opened a new ticket because at the moment this is just an abstract question, and if the answer is something to the effect of “macFUSE 4.2.0 is expected to work as-is on the public release macOS Monterey”, then there’s no need for another ticket for this question.]

**Comment by bfleischer** [comment]
@cdevers-es 

Apple has not deprecated file system kernel extensions. There is no system extension API for developing full-featured file systems. When trying to load a kernel extension that uses deprecated kernel API, macOS displays a warning informing the user that the kernel extension needs to be upgrade. There is no such warning when trying to load the macFUSE kernel extension.

Support for kernel extensions will not be dropped in macOS 12, since there is no alternative API for developing file systems.  Apple would need to announce such an API and then give developers enough time (at least one year) to transition to this new API before dropping support for file system kernel extensions.

When Apple announces a new system extension API for developing full-featured file systems, I will update macFUSE to use this new API instead of a the old kernel API.

**Comment by cdevers-es** [comment]
> @cdevers-es
> Apple has not deprecated file system kernel extensions. […]

Thank you for clarifying!

**Comment by torarnv** [comment]
Will macFUSE be affected by the upcoming changes/restrictions on kernel extensions in macOS 12.3?

**Comment by bfleischer** [comment]
@torarnv Please see https://github.com/osxfuse/osxfuse/issues/873

**Comment by MrSuaz** [comment]
Hi, 

How do we approve this at an MDM level? Seems the installation of macFUSE requires admin approval and a rebuild/restart before loading.
