### ISSUE TITLE
Frustration +100

### ISSUE THREAD

**Issue by Mertonoia** [osxfuse/osxfuse#83]
I am not a coder. My system has been acting up for weeks and today I got the incompatibility error. I'd done everything recommended to transition from MacFuse to OXfuse but here it is, along with daily kernel panics and much lost time, not to mention increasing frustration that's not helped by your obtuse instructions for uninstalling. I ran both terminal commands this morning and was told that no such file or directory exists. I pray there is someone there decent enough to respond with meaningful instructions for getting this crap off my system. If not, I will make it my life's calling to get the word out via every Mac forum that will listen why users might be having odd issues. This will be after I post very negative and cautionary reviews to all the Mac software repositories. I warn all this because anyone who supports such, I don't even know what to call it unless you KNOW you're making malware, must be ethically challenged.

**Comment by 3finity** [comment]
This is hands-down the most ridiculous and entertaining waste of time I've come across in a long time. What confounds me more than anything else is how this thread got this long. This should be archived as a very time-expensive tasteless and disrespectful example of how not to log an issue.

@Mertonoia - you exist in a world now where you are dependent on the charity of strangers that have no obligation to you and can tune you out without lifting a finger. Learn the culture or find the Internet a very inhospitable place where your disrespectful attitude will be out here for all to laugh at. The Internet does not forget, and this post will most likely outlive you. Be careful how you speak to people.

**Comment by Nemesarial** [comment]
This is hands-down the most ridiculous and entertaining waste of time I've come across in a long time. What confounds me more than anything else is how this thread got this long. This should be archived as a very time-expensive tasteless and disrespectful example of how not to log an issue.

@Mertonoia - you exist in a world now where you are dependent on the charity of strangers that have no obligation to you and can tune you out without lifting a finger. Learn the culture or find the Internet a very inhospitable place where your disrespectful attitude will be out here for all to laugh at. The Internet does not forget, and this post will most likely outlive you. Be careful how you speak to people.

**Comment by SlapstickMarmalade** [comment]
I do not understand the people condoning the behaviour of @Mertonoia. No matter what the perceived damage caused by the software, it is provided free and with absolutely no warranty of any kind. And yet, @bfleischer seems committed to sorting peoples' issues out.

@Tesselator 
> Besides the use of the word "shit" several times I didn't see any indications of Mertonoia displaying anger.

Yeah right:

> I pray there is someone there decent enough to respond with meaningful instructions for getting this crap off my system. If not, I will make it my life's calling to get the word out via every Mac forum that will listen why users might be having odd issues. This will be after I post very negative and cautionary reviews to all the Mac software repositories. I warn all this because anyone who supports such, I don't even know what to call it unless you KNOW you're making malware, must be ethically challenged.

She basically threatened and then questioned the morals of someone who's making a _very_ useful piece of software for free. I don't even own any Apple products and even I found it useful when I found myself stuck with my friend's Macbook, with no access to my usual devices. Oh and by the way, MacFuse is seriously awful, which I assume, is why @Mertonoia even tried OsXFuse in the first place. Funny how all her furious and righteous anger didn't work with Apple, despite her being a paying customer.
She even went on to accuse him of sexism, but I cannot be arsed to find and quote any more of this woman's bile.
Behaviour like hers is simply unacceptable, especially since she herself is a developer and knows the pain and tedium of maintaining FOSS. She seems like the kind of person with little patience and a lot of willingness to blame the entire world for everything.

What I will do is link to her repository here: https://github.com/Mertonoia/uif2iso4mac
As you can see, there is no issues tab, which tells us everything we need to know about her.
She'll '_make it my life's calling to get the word out via every Mac forum that will listen why users might be having odd issues. This will be after I post very negative and cautionary reviews to all the Mac software repositories_', but she won't put in the effort to have an issue tracker for something she built. smh.

I know this is an ancient thread but I could not help but commenting; her posts made me quite livid.
