### ISSUE TITLE
License and trust

### ISSUE THREAD

**Issue by hackerb9** [osxfuse/osxfuse#841]
Hello! Thank you for having created FUSE for MacOS. I've recommended it in the past to people who need sshfs on their Macs. Today, I discovered that one cannot compile the source code using brew because, apparently, the source code is no longer available. 

I have a couple questions that I do not see answered in the long threads I read here:

1. How are we supposed to trust macFUSE if the source code is closed? (More about that below).
2. Are there legal reasons why someone could not create a fork of macFUSE based on the last available source code?

### More details about Q1
The manner in which the license was made proprietary, which many people found sudden and secretive, could possibly be explained as the developers being hasty and making a rash decision. But, the rationale for why the source code had to be closed seems implausible, especially after two years. I do not want to be suspicious, but there needs to be a clearer explanation before I can trust macFUSE.

Specifically, it was stated in #616 that:

> macFUSE is not an end user product. It is a software component that is used primarily by software developers who integrate it into their product and ship it as part of their (commercial) software [...] Very few companies will donate money to an open source project. 

If the intention of changing the license was simply to force the proprietary software that relies on macFUSE to fund future development, then one would expect the developers to have simply switched to a copyleft license, like the GNU General Public License, not closed the source. With the GPL, the source code would still be open and usable by hobbyists and homebrew. But, any companies that wish to continue integrating macFUSE would need to either release their own program's source code or pay the macFUSE developers a fee to license the code under different terms.

Why did the macFUSE developers switch to a proprietary license and close the source when it was not necessary? What is stopping the developers from dual-licensing macFUSE under a copyleft license now? Without an explanation, how can we trust macFUSE?

### About Q2. 

I am not proposing that anyone fork macFUSE. I certainly am not going to. But if someone did, would there be legal objections? I'm mostly asking because I'm surprised that homebrew is refusing to install sshfs at all instead of simply using the last source code that was available. 

### Thank you

I appreciate all the work that has been done to create macFUSE and hope that development will be able to continue in the future.

**Comment by bfleischer** [comment]
> If the intention of changing the license was simply to force the proprietary software that relies on macFUSE to fund future development, then one would expect the developers to have simply switched to a copyleft license, like the GNU General Public License, not closed the source.

Simply using a copyleft license like the GPL won't work. macFUSE is not statically linked, so this means that companies would only need to open-source the modified macFUSE source code, not the source code of their product in its entirety. But most importantly, the GPL allows commercial use at a large scale.

I learned a few things while maintaining macFUSE:

* The great majority of developers of commercial macFUSE-based products is not interested in implementing new proprietary macFUSE features that might give them a competitive edge.
* Commercial developers are mostly interested in rebranding macFUSE and signing it with their own Developer ID certificates, so that the macOS dialog asking the user for permission to load the kernel extension shows their company name instead of my name. 
* The remaining developers simply want to bundle macFUSE and ship it alongside their commercial product to their customers.

Given the above, the GPL does not provide an incentive to pay for macFUSE. For commercial developers there is no loss in releasing the source code of a rebranded version of macFUSE. Or in other words, there is nothing to gain by licensing macFUSE to keep the rebranded source code closed.

Releasing the source code under a "permissive" license and thereby making it easy for third parties to rebrand macFUSE has a significant drawback. Over the years I had to deal with countless cases where developers did a poor job rebranding macFUSE and then shipping their version on a large scale. This resulted in conflicts and the "partially" rebranded versions interfered with official macFUSE releases. This usually resulted time-consuming support cases, time I would rather spend on fixing actual issues.

> With the GPL, the source code would still be open and usable by hobbyists and homebrew. 

When installing macFUSE using Homebrew, Homebrew used to extract the macFUSE kernel extension binaries from the official macFUSE installer package (compiled by me) instead of compiling the code locally. This was done because Homebrew has no way of signing kernel extensions so that they would load on users' Macs.

If trust is an issue, then you cannot trust any kernel extension you install using Homebrew as they are compiled by the original developers, not Homebrew. You have no way of knowing if the kernel extensions contain additional malicious code that is not present in the released source code.

Most of the remaining macFUSE components (libfuse, macFUSE.framework) are still open source. 

> But, any companies that wish to continue integrating macFUSE would need to either release their own program's source code or pay the macFUSE developers a fee to license the code under different terms.

No, they would not. See above.

> Why did the macFUSE developers switch to a proprietary license and close the source when it was not necessary?

I do not agree with your conclusion, that closing the source code was not necessary. 

> What is stopping the developers from dual-licensing macFUSE under a copyleft license now?

A classic copyleft license does not solve the "raising funds" problem. Copyleft does not prevent developers from distributing rebranded versions of macFUSE for commercial use and the GPL would allow developers of commercial macFUSE-based products to ship the macFUSE binaries alongside their respective commercial products.

> Without an explanation, how can we trust macFUSE?

I try to be open about the license change and explain my reasons. But ultimately it is up to you to decide if you trust closed source software or not. Please keep in mind that many components of macOS or iOS are not open source either.

**Comment by bfleischer** [comment]
> I am not proposing that anyone fork macFUSE. I certainly am not going to. But if someone did, would there be legal objections?

I don't think there would be any legal objections.

>  I'm mostly asking because I'm surprised that homebrew is refusing to install sshfs at all instead of simply using the last source code that was available.

The last open-source version of macFUSE does not support newer versions of macOS and it is missing features and bugfixes that have been implemented in the meantime.

**Comment by hackerb9** [comment]
> Simply using a copyleft license like the GPL won't work. macFUSE is not statically linked, so this means that companies would only need to open-source the modified macFUSE source code, not the source code of their product in its entirety. But most importantly, the GPL allows commercial use at a large scale.

Not being statically linked does not affected the GPL as long as it is a "combined work". (See http://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic). How do these commercial developers "integrate" macFUSE in their programs? What matters is whether the product they sell is a combined work or a mere aggregation.  

Yes, the GPL does allow commercial use at a large scale as long as it is non-proprietary, but I don't quite follow what the problem with that is. Are you thinking that if you had a dual proprietary / GPL license then anyone who licensed it from you under the proprietary license could then use it at a large scale at no extra charge?  The GPL only applies for programs that are themselves covered by the GPL.  Or, are you concerned about something like "Tivoization" where a company may release source code that is useless to anyone but them? 


>     * Commercial developers are mostly interested in rebranding macFUSE and signing it with their own Developer ID certificates, so that the macOS dialog asking the user for permission to load the kernel extension shows their company name instead of my name. 

> Given the above, the GPL does not provide an incentive to pay for macFUSE. For commercial developers there is no loss in releasing the source code of a rebranded version of macFUSE. Or in other words, there is nothing to gain by licensing macFUSE to keep the rebranded source code closed.

Interesting! Is MacOS doing a hardware check for a cryptographic signature before allowing the software to run? 

I suspect macFUSE is a combined work and not merely adjacent to the commercial software you mentioned. But even if that were not the case, the GPL v3 may well apply if they are modifying the binary by resigning it with their own certificate. The GPL v3 requires anyone who distributes a signed binary of GPL'd code that will not run without that signature to provide not only the source code but also the signing key. Of course, that restriction wouldn't apply to the macFUSE developers or anyone they choose to grant special license to.  I do not know how Apple's Developer ID certificates work, but I would suspect that companies would rather pay macFUSE developers for a special licensing agreement instead of publishing their cryptographic keys.

But, as I said, that's probably not even relevant since the GPL applies to any "combined work".

> Releasing the source code under a "permissive" license and thereby making it easy for third parties to rebrand macFUSE has a significant drawback. Over the years I had to deal with countless cases where developers did a poor job rebranding macFUSE. This resulted in conflicts and the "partially" rebranded versions interfered with official macFUSE releases. This usually resulted time-consuming support cases, time I would rather spend on fixing actual issues.

That makes sense, but the GPL is not as permissive as the previous license. While not eliminating the possibility of poorly rebranded versions, it would at least ensure that any proprietary software that causes support headaches will have already paid the macFUSE developers for the privilege.

> > With the GPL, the source code would still be open and usable by hobbyists and homebrew.
> 
> When installing macFUSE using Homebrew, Homebrew used to extract the macFUSE kernel extension binaries from the official macFUSE installer package (compiled by me) instead of compiling the code locally. This was done because Homebrew has no way of signing kernel extensions so that they would load on users' Macs.

> If trust is an issue, then you cannot trust any kernel extension you install using Homebrew as they are compiled by the original developers, not Homebrew. You have no way of knowing if the kernel extensions contain additional malicious code that is not present in the released source code.

That's disappointing. MacOS needs a trustworthy packaging system and it sounds like you are saying that it is impossible. Did homebrew have to do that because Apple charges for a signing certificate or because they thought the macFUSE license would compel them to publish the key? Also, how did Apple manage to mess up signatures so badly that it precludes checking the rest of the binary to see if it matches one compiled from source? Are you sure it is impossible to verify?


> Most of the remaining macFUSE components (libfuse, macFUSE.framework) are still open source.

Nice. But the critical component needed to use them is the kernel extension which is now proprietary, right? While user space binary blobs are bad enough, you'd have to have a darn good reason for tainting the kernel with a proprietary extension. And, given that GPL v3 should ensure your revenue stream as much as a proprietary license, there doesn't seem to be a compelling case.


By the way, in #616, you mentioned that the person behind homebrew wasn't even making annual minimum wage on Patreon (presuming it is a full time job). I'm curious: has the license change to macFUSE produced more than minimum wage revenue when averaged over two years? If not, maybe it doesn't matter if you believe me that you can prevent other developers from integrating macFUSE in their products without going all the way to closed source. Perhaps, the license could switch back to open source simply because the revenue has not been as high as initially hoped.

**Comment by bfleischer** [comment]
> Not being statically linked does not affected the GPL as long as it is a "combined work". (See http://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic). How do these commercial developers "integrate" macFUSE in their programs? What matters is whether the product they sell is a combined work or a mere aggregation.

It's more complicated than that. I'm not a lawyer, but I'm not convinced that a commercial product incorporating the macFUSE kernel extension would classify as combined work. The kernel extension is not "linked" with the commercial product. At the very least this is a grey area and I'm not willing to bet my funding on this.

> Yes, the GPL does allow commercial use at a large scale as long as it is non-proprietary, but I don't quite follow what the problem with that is. Are you thinking that if you had a dual proprietary / GPL license then anyone who licensed it from you under the proprietary license could then use it at a large scale at no extra charge?

Your argument is based on the "combined work" assumption. Without this assumption there is really no (or very little) incentive for developers of commercial products to license macFUSE.

> [...] Is MacOS doing a hardware check for a cryptographic signature before allowing the software to run?

By default, kernel extensions on macOS need to be signed by a special code signing certificate that developers enrolled in Apple's Developer Program need to apply for separately. This is not the standard code signing certificate that every enrolled member receives. In addition to that every kernel extension needs to go through Apple's notarization process. This ensures that Apple can disable malicious or dangerous kernel extensions remotely even after they have been shipped to end users. By default, macOS will not load any kernel extensions that Apple has not approved beforehand. 

Technically it is possible to load unsigned and unnotarized kernel extensions on macOS, but you would need to disable System Integrity Protection on your Mac to do this. I can't stress enough that this is really a bad idea in terms of security. So no, it's not a hardware check.

This is one of the reasons why building kernel extensions locally using Homebrew or other package managers makes no sense. The resulting binary would really not be more trustworthy than the official release and there would be no kill switch in case it contains malicious code.

> I suspect macFUSE is a combined work and not merely adjacent to the commercial software you mentioned. But even if that were not the case, the GPL v3 may well apply if they are modifying the binary by resigning it with their own certificate. The GPL v3 requires anyone who distributes a signed binary of GPL'd code that will not run without that signature to provide not only the source code but also the signing key.

Please see https://www.gnu.org/licenses/gpl-faq.html#GiveUpKeys. In this particular case the GPLv3 would not require developers to publish their private keys.

> > Releasing the source code under a "permissive" license and thereby making it easy for third parties to rebrand macFUSE has a significant drawback. Over the years I had to deal with countless cases where developers did a poor job rebranding macFUSE. This resulted in conflicts and the "partially" rebranded versions interfered with official macFUSE releases. This usually resulted time-consuming support cases, time I would rather spend on fixing actual issues.
> 
> That makes sense, but the GPL is not as permissive as the previous license. While not eliminating the possibility of poorly rebranded versions, it would at least ensure that any proprietary software that causes support headaches will have already paid the macFUSE developers for the privilege.

Same as above, your argument is based on the "combined work" assumption. If that does not hold up, the GPL does not force developers of commercial software to pay for macFUSE.

> > > With the GPL, the source code would still be open and usable by hobbyists and homebrew.
> >  
> > [...]
> 
> That's disappointing. MacOS needs a trustworthy packaging system and it sounds like you are saying that it is impossible. Did homebrew have to do that because Apple charges for a signing certificate or because they thought the macFUSE license would compel them to publish the key?

Apple charges a yearly fee for being enrolled in the Apple Developer Program.

No, it's not about macFUSE compelling Homebrew to release their private key. Homebrew cannot release their private key because that would make their signature worthless (and it would most likely be a violation of the Apple Developer Program Agreement). Everyone could compile code and pretend it is from Homebrew. This means that even if Homebrew had a certificate for singing kernel extensions they could not build the kernel extensions locally when you install the port. So they would need to ship pre-built binaries, too. There is really no difference from a user's perspective whether Homebrew installs a binary compiled by them vs. the original developer of the software. Homebrew using their certificate to sign third-party code would make them liable for potentially malicious third-party code.

> Also, how did Apple manage to mess up signatures so badly that it precludes checking the rest of the binary to see if it matches one compiled from source? Are you sure it is impossible to verify?

I'm no expert on the topic. I doubt that running the the same build job on a different Mac (possibly even a different architecture) using maybe a different version of Xcode results in an identical binary. But like I said, I'm not an expert on the topic.

System Integrity Protection and Gatekeeper ensure that binaries you run on your Mac are signed by a registered developer and notarized by Apple.

> By the way, in #616, you mentioned that the person behind homebrew wasn't even making annual minimum wage on Patreon (presuming it is a full time job).

Max created Homebrew, but he is no longer involved in the day-to-day operations, as far as I know. Homebrew is just one of his open source projects. 

> I'm curious: has the license change to macFUSE produced more than minimum wage revenue when averaged over two years? 

Short answer, yes.

**Comment by hackerb9** [comment]
It sounds like I read too much into this comment:

> macFUSE is not an end user product. It is a software component that is used primarily by software developers who integrate it into their product and ship it as part of their (commercial) software

You are, of course, correct that if macFUSE is merely bundled as an adjacent program, then the GNU GPL would not apply. I had hoped that would be an easy solution for regaining trust, but it sounds like the situation is rather messy on MacOS, especially with the Apple Developer Certificates. 

I wish you luck.

**Comment by WGroleau** [comment]
Does any of this mean that those selling derivatives **in the app store** are violating your copyright?
