### ISSUE TITLE
SSHFS automatically unmounts when MacBook goes to sleep.

### ISSUE THREAD

**Issue by psihonavt** [osxfuse/osxfuse#842]
Hello,

First of all, thank you for developing macFUSE. 

I have the following situation. I have several VirtualBox Linux guests on my host system (OS X Big Sur). I use macFUSE + sshfs to mount certain folders from these virtual machines on the host FS. Everything works fine; however, when MacBook goes to sleep, the mounted folders get unmounted (and I need to do `umount <local endpoint> && sshfs ..` to mount folders back). This is strange because I have many open ssh sessions to these guest machines - they remain active, and they never cut off. 

Any ideas why it happens and if there is a way to mitigate it?

Thanks.

**Comment by porg** [comment]
Maybe related to #45 ?

**Comment by porg** [comment]
It is called "SSHFS" and not "SSFS".

You may change the typo in your issue title, so that it has better chances for being found.

**Comment by bfleischer** [comment]
I don't think this issue can be fixed in macFUSE. macFUSE requires the file system daemon to be responsive. In case the daemon does not respond to relayed file system operations within `daemon_timeout` (60 seconds, by default) the volume is marked as dead. That's the only sane way (I'm aware of) to avoid blocking processes accessing the volume indefinitely when the file system daemon dies or hangs.

SSHFS might use different ssh options when mounting the volumes than your Terminal SSH sessions. There seems to be a `reconnect` option for SSHFS that might help. In any case, I think this issue needs to be investigated from the SSHFS end rather than the macFUSE end.

Feel free to re-open the ticket, if you think macFUSE is to blame for the issue.
