### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by 3cooper** [osxfuse/osxfuse#847]
We have an Electron app, and were using a package called fuse-native to work with osxfuse.  fuse-native has not been updated and is not compatible with recent versions.  Is there documentation for the osxfuse API for us to use to troubleshoot the issues this other library is having?

**Comment by bfleischer** [comment]
I've never used Electron or fuse-native, so my knowledge in this regard is very limited. The FUSE API is documented in the public libfuse headers. There is no separate macFUSE specific API documentation. The public macFUSE API has not changed is a long time. However, due to the rebranding a few paths have changed. 

Can you tell me more about the specific issues you are running into? Maybe I can provide some pointers.

**Comment by bfleischer** [comment]
For lack of a response, I'm closing the issue.
