### ISSUE TITLE
MacOS 12.0.1 (M1) Incompatible architecture (fuse 4.2.0-4.2.1)

### ISSUE THREAD

**Issue by Gregory-Skurko** [osxfuse/osxfuse#848]
To use fuse, we copy `*.fs` into our app package at `*.app/Contents/Resources/*.fs`. If I try to run the app from `/Applications`, the macOS cannot load the fuse kext, `Console` shows that `kernelmanagerd` is trying to check extensions for all versions of macOS and displays errors `Incompatible architecture: Binary is for x86_64, but needed arch arm64e` (even if trying to load 12 `*.kext` version directly from terminal). But from anywhere else the kext loads fine(e.g. `/Users/%User%/Downloads/`), in this case I see that `kernelmanagerd` is checking the kext for macOS 12 only.
If I removed from extensions all directories that containing binaries with only x86_64 versions that kext loads fine and from `/Applications` (now 10.9-10.15 builded for x86_64 only, 10.16-12 are universal binaries). What we can do with it? Maybe it's possible to build a universal kext for all macOS versions?

**Comment by wesdunn** [comment]
I work with a custom branded version of osxfuse and have experienced the same issue with 12.0.1. I have not dug into console logs, but saw this earlier and ended up deciding to try removing the 10.9-10.15/x86_64-only binaries as @luciys mentioned here... 

I deleted them all from my app bundle, re-signed everything, and then re-tried getting the kext installed via my app's normal means... I **FINALLY** was prompted to do the whole reboot-recovery-reboot-approval-reboot process and **FINALLY** the kext loaded and I was able to mount drives as expected. 

I was working with version 4.2.1, I have not tried the same with 4.2.0, but expect the same results as mentioned in this issue.

Curious if this is an OS bug or just Apple adding more fuel to fire that is user experience for apps with kexts.

**Comment by Gregory-Skurko** [comment]
@wesdunn 
I think I found a better solution
It might work for you too

For version 4.2.1 (maybe for 4.2.0 too, didn't check it), need to replace DTPlatformVersion value in Info.plist from 11.1 to GM in:
\*.fs/Contents/Extensions/10.9/\*.kext/Contents/Info.plist
\*.fs/Contents/Extensions/10.11/\*.kext/Contents/Info.plist
\*.fs/Contents/Extensions/10.12/\*.kext/Contents/Info.plist

Then you don't need to delete anything

**Comment by wesdunn** [comment]
@luciys oh, interesting! Thanks for letting me know, I will definitely give that a try... I know there's a 4.2.2 in pre-release right now, but I was hoping to get an update out to our customers today so that things will work for the M1/macOS 12 folks we have. If this works out, I may proceed down this path, so **THANK YOU!**

One point of clarification before I try it out... you're changing the `DTPlatformVersion` value in those plist files from  `11.1` to the string `GM`, correct?

**Comment by Gregory-Skurko** [comment]
@wesdunn Yes, I noticed that the previous version we were using contained `GM`

**Comment by bfleischer** [comment]
Version 4.2.3 contains a workaround for this issue. 

The "incompatible architecture" error is a bug in macOS. Apple seems to have introduced this bug in one of the last Monterey beta releases. In some cases loading the kexts worked fine and in other cases it did not work at all. It seems pretty random. The kexts are obviously fine because they can be loaded without any issues when placed outside of the app bundle.
