### ISSUE TITLE
Cannot uninstall OSXFUSE 2.8.3

### ISSUE THREAD

**Issue by Teivaz** [osxfuse/osxfuse#864]
I have M1 MacBook Pro with MacOS 12.0.1 Monterey. The OSXFUSE migrated along with all stuff from mu old mac but the extension seems to be completely outdated and none of the buttons work. I get "Unable to contact update server" message for both.
When pressing the "Remove OSXFUSE" button the progress indicator appears with text "Removing OSXFUSE..." but the next moment it changes to "Unable to contact update server".
<img width="780" alt="Screenshot 2021-12-11 at 23 16 16" src="https://user-images.githubusercontent.com/4460981/145693299-1026eca2-ea45-4100-9fd7-98b8ca1c3469.png">

I have tried to reboot multiple times with no luck.
How do I remove it?

**Comment by bfleischer** [comment]
Version 2.8.3 is not compatible with Monterey. The easiest way to remove it, is to download the installer disk image for an up to date version from https://osxfuse.github.io, open it and run the uninstaller in the Extras directory on the disk image. This should remove the incompatible version from your Mac.

**Comment by JDW1** [comment]
The advice given by bfleischer to download MacFuse (currently at v.4.5.0) and then launch Extras > Uninstaller does NOT work to uninstall old versions.  All that does is Uninstaller version 4.5.0, leaving version 2.6.0 installed on my MacOS Ventura 16" M1 Max MBP.  If the uninstaller could please be made to truly uninstall ALL old versions, regardless of MacOS version, that would be great.  But that would take time.  What is another method of uninstalling version 2.6.0?

**Comment by bfleischer** [comment]
The uninstaller tries to uninstall old versions of macFUSE/osxfuse. You might have to run in more than once if you installed multiple versions of macFUSE. Did you run it more than once?

How do you know version 2.6.0 is still installed?

**Comment by JDW1** [comment]
I know version 2.6.0 is installed because MacOS Ventura "System Settings" tells me so when I keyword search for "fuse"...

<img width="886" alt="image" src="https://github.com/osxfuse/osxfuse/assets/3928027/628eab6b-8fce-4f9e-b21e-cf71d4b78745">

The one below that is version 4.5.0...

<img width="880" alt="image" src="https://github.com/osxfuse/osxfuse/assets/3928027/e18d0b7b-867b-41fb-b5e9-3bdb39e2df4c">

Bear in mind that was AFTER I used MacOS Terminal with the following command line to delete the old KEXT:

sudo kextcache --clear-staging

**For even more detail, please see my post here:**
https://www.emaculation.com/forum/viewtopic.php?p=76842#p76842

But here's a Disk Utility screenshot that I didn't put in my emasculation post because I hate adding screenshots to that fiddly forum. (Github is lightyears ahead, allowing us to paste in graphics!)

<img width="858" alt="image" src="https://github.com/osxfuse/osxfuse/assets/3928027/5162d649-d6ec-4143-915d-4732c1af7f96">

**Comment by JDW1** [comment]
Having no idea what filenames I should search for, I did a shot-in-the-dark search for "osxfuse" and got these results...

![image](https://github.com/osxfuse/osxfuse/assets/3928027/825723ab-a48b-445a-954c-f06b14c541ca)

I then used the MacOS Terminal "sudo rm -r " command line to try and delete every single one of those files and folders.  I mostly was successful, but these remain...

<img width="1278" alt="image" src="https://github.com/osxfuse/osxfuse/assets/3928027/7e012ad9-39b3-4d05-bc9c-ec7dc82e9948">

All 3 are in the same "private > var > db > oah" path.  And despite having given Terminal Full Disk Access, my use of "sudo rm -r" and "sudo rm -rf" all result in an Operation Not Permitted error in the Terminal.  

I therefore have no idea how to delete those 3 files.

Also, if there are fuse related files that do NOT have "osxfuse" in the filename, those too could still be lurking on my drive.

I really wish there could be an uninstaller that could uninstall all old fuse related files on M1 Macs running the latest MacOS!

**Comment by gavineadie** [comment]
With System Integrity Protection enabled (the default since macOS 10.11?) the content of `/var` (and another directories -- see https://support.apple.com/en-us/HT204899) is inviolate.  I'm not a user of macFUSE, but I lurk on the mailing list, and this thread hasn't made any reference to SIP so it comes as  no surprise that "private > var > db .." is untouchable by Terminal regardless of Full Disk Access and/or the use of `sudo`.

SIP can be disabled and I am _guessing_ that if it was disabled, the three remaining files referred to above could be deleted.  It's a very bad idea to leave SIP disabled, so I recommend reenabling it immediately after deleting those files and not doing _anything_ else while it's turned off.  You have a valid point in being concerned that there may other fragments of that ten year old v2.6 FUSE which don't "have `osxfuse` in the filename" -- if there's a copy of that antique installer available, you might be able to pick it apart and see what files were installed.

Deleting those files with SIP disabled may not fix the problem and/or make it worse.  Beware.

**Comment by JDW1** [comment]
> SIP can be disabled...

Per your suggestion, I shutdown my M1 MBP, then pressed and held power until I got Startup Options (Recovery).  I launched the Terminal and typed "CSRUTIL DISABLE" and hit return.  After several seconds, it said it was Disabled and that I should restart.  I then chose Startup Disk so I could choose my external SSD which has Ventura on it (my internal SSD has Monterey), and I booted from that.  Sadly, when I launch Terminal and type "CSRUTIL STATUS" and hit return, it says it is Enabled!

I thought once Disabled in Recovery it would stay disabled regardless of my boot drive.  Is that not so? 

Any further advice would be greatly appreciated.

**Comment by JDW1** [comment]
I was able to boot from my internal SSD and see that SIP is Disabled, so I guess it won't disable when booted from an external drive.  Crazy.  Regardless, it still doesn't work even after deleting all files and doing a fresh install.  Read all the details here: https://www.emaculation.com/forum/viewtopic.php?p=76844#p76844

I'm throwing in the towel at this point.  Very disappointed. :-(

**Comment by bfleischer** [comment]
@JDW1 It seems there are a couple of things that are getting mixed up here.

* macFUSE is a building block for developing third-party file systems. Unless the third-party file system specifically supports mountable volumes using Disk Utility, you will have to follow the instructions provided by the file system developer for mounting a volume. For many FUSE file systems this involves using Terminal and entering a few commands. If you are running into issues mounting a volume, it would be best to raise the issue with the developer of the actual file system first.

* Installing, running or uninstalling macFUSE/osxfuse does not require SIP being disabled. I don't recommend disabling System Integrity Protection. I cannot stress this enough. In my first reply to you, I recommended running the uninstaller more than once to remove all versions of macFUSE/osxfuse. The uninstaller removes one version to a time. Did you try this?

* The uninstaller runs the following commands if it detects osxfuse 2.x being installed. Please note that the below commands will damage installations of newer versions of macFUSE. This means you will have to re-install the desired version of macFUSE after running the commands below. 
```
/bin/rm -rf "/Library/Filesystems/osxfusefs.fs"
/bin/rm -rf "/Library/Frameworks/OSXFUSE.framework"
/bin/rm -rf "/usr/local/include/osxfuse"
/bin/rm -f "/usr/local/lib/libosxfuse.2.dylib"
/bin/rm -f "/usr/local/lib/libosxfuse.dylib"
/bin/rm -f "/usr/local/lib/libosxfuse.la"
/bin/rm -f "/usr/local/lib/libosxfuse_i32.2.dylib"
/bin/rm -f "/usr/local/lib/libosxfuse_i32.dylib"
/bin/rm -f "/usr/local/lib/libosxfuse_i32.la"
/bin/rm -f "/usr/local/lib/libosxfuse_i64.2.dylib"
/bin/rm -f "/usr/local/lib/libosxfuse_i64.dylib"
/bin/rm -f "/usr/local/lib/libosxfuse_i64.la"
/bin/rm -f "/usr/local/lib/pkgconfig/fuse.pc"
/bin/rm -f "/usr/local/lib/pkgconfig/osxfuse.pc"

/usr/sbin/pkgutil --forget "com.github.osxfuse.pkg.Core"

/bin/rm -rf "/Library/PreferencePanes/OSXFUSE.prefPane"
/bin/rm -f "/Library/Preferences/com.github.osxfuse.OSXFUSE.plist"

/usr/sbin/pkgutil --forget "com.github.osxfuse.pkg.PrefPane"

/bin/rm -rf "/Library/Frameworks/MacFUSE.framework"
/bin/rm -f "/usr/local/lib/libfuse.0.dylib"
/bin/rm -f "/usr/local/lib/libfuse.2.dylib"
/bin/rm -f "/usr/local/lib/libfuse.dylib"
/bin/rm -f "/usr/local/lib/libfuse.la"
/bin/rm -f "/usr/local/lib/libfuse_ino64.2.dylib"
/bin/rm -f "/usr/local/lib/libfuse_ino64.dylib"
/bin/rm -f "/usr/local/lib/libfuse_ino64.la"
/bin/rm -f "/usr/local/lib/libmacfuse_i32.2.dylib"
/bin/rm -f "/usr/local/lib/libmacfuse_i32.dylib"
/bin/rm -f "/usr/local/lib/libmacfuse_i64.2.dylib"
/bin/rm -f "/usr/local/lib/libmacfuse_i64.dylib"

/usr/sbin/pkgutil --forget "com.google.macfuse.core"
```

* The .aot files are created and managed by macOS. I think those file are created by Rosetta due to version 2.6.0 being Intel-only.  Version 4.0.0 is the first release that runs on Apple Silicon. For macOS Ventura you need at least version 4.4.0. Since those .aot files are created by macOS automatically, they might be deleted automatically after the corresponding Intel binary is removed, but this is speculation. There are a couple of posts on Apple's support forum regarding removing .aot files. 

* You cannot use macFUSE when booting an external volume on Apple Silicon Macs. macOS does not supporting kernel extensions when run for an external volume. It's unclear if this is a bug or by design. In any case it is an issue that would need to be raised with Apple.
