### ISSUE TITLE
I installed MacFUSE on macos12 but I get a problem trying to run aa command

### ISSUE THREAD

**Issue by Jaxon10117** [osxfuse/osxfuse#871]
I installed the extensions everything but when I run in terminal "brew install ext4fuse" it returns to me "Error: ext4fuse has been disabled because it requires closed-source macFUSE!" any help?

**Comment by bfleischer** [comment]
This is a Homebrew issue. They disabled the macFUSE formula due to macFUSE not being open-source. This means all formulas depending on macFUSE have been disabled as well. Please raise this issue with the Homebrew team. There is nothing I can do about it from the macFUSE end.

It might be worth checking out https://github.com/gromgit/homebrew-fuse.

**Comment by kleajmp** [comment]
I understand its a brew issue, but I guess the only solution is to compile it with the make command? But how? Is there an exact tutorial for non experienced compilers?

**Comment by clemaredev** [comment]
Specifically for ext4 there is a solution that worked for me in this article: https://github.com/gerard/ext4fuse/issues/66
(on 14 Apr 2021, username marcuspridham https://github.com/marcuspridham)
