### ISSUE TITLE
Can't install due to SentinelOne

### ISSUE THREAD

**Issue by johalun** [osxfuse/osxfuse#884]
The SentinelOne security software adds files to /usr/local that are owned by root and can not be changed to be own by another user.

When running `brew install --cask macfuse` it tries to change owner of /usr/local recursively
```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/sbin/chown -R -- johalun:staff /usr/local/include /usr/local/lib` exited with 1. Here's the output:
chown: /usr/local/lib/sentinel.dylib: Operation not permitted
```
which first, it shouldn't have to. `/usr/local/{bin,lib}` are already owned by me. Just the one file from sentinel is not. Secondly, brew prefix is `/opt/homebrew` so I'm not sure why it's even trying to install to `/usr/local`..

macOS 12.2.1, Apple Silicon

**Comment by bfleischer** [comment]
Let me start by saying that `/usr/local/` should not be owned by you. By default the directory is owned by `root:wheel`. The macFUSE installer makes sure that `/usr/local/include` and `/usr/local/lib` are world-readable (as those directories should be) by running the following commands: 

    chmod u+rx,g+rx,o+rx "/usr/local/include"
    chmod u+rx,g+rx,o+rx "/usr/local/lib"

The failed command from your error message `/usr/bin/sudo -E -- /usr/sbin/chown -R -- johalun:staff /usr/local/include /usr/local/lib` is not run by the macFUSE installer. Maybe it's in the Homebrew formula. It might be worth raising the issue with the Homebrew team.

The default location for libfuse is `/usr/local/lib`. macFUSE is a shared component that is used by many applications. For this to work, libfuse to be in a pre-defined location so that binaries linking against it are able to find it. 

Homebrew simply downloads the macFUSE installer and runs it. That's why your Homebrew prefix has no effect on macFUSE.

**Comment by johalun** [comment]
Ok, got it. Yeah makes sense that it's in /usr/local for a shared library. I'll check with the brew formula. Thanks!

**Comment by dhanjit-groww** [comment]
How was this resolved?

**Comment by otherguy** [comment]
This isn't solved unfortunately. The related tasks and PRs in Homebrew are closed but have not resolved this issue:

https://github.com/Homebrew/homebrew-cask/pull/103393
https://github.com/Homebrew/homebrew-cask/issues/104784
https://github.com/Homebrew/homebrew-cask/pull/103393
