### ISSUE TITLE
Meta: Confusion between repos macfuse and osxfuse plus outdated info how to give feedback

### ISSUE THREAD

**Issue by porg** [osxfuse/osxfuse#888]
I reported and meanwhile closed a [Mac FUSE related issue](https://github.com/libfuse/libfuse/issues/678) at the wrong place due to misinformation in the `README.md`
at https://github.com/macfuse/library which states:
> Please report any bugs on the GitHub issue tracker at https://github.com/libfuse/main/issues

## Inquiries

1. If you are the same people, or at least connected, could you please update that info, so that Mac specific issues land where they should, so supposedly here at https://github.com/osxfuse/osxfuse

2. The other problem is one of branding/terminology:
  - Apple rebranded its OS from "Mac OS X" to "macOS" in 2016.
  - So newcomers may suspect "macfuse" to be the more current or more adequate repo than "osxfuse" which refers to a name not used by Apple anymore.
  - From that perspective ideally macfuse should be the main place of activity
  - If that is not adequate or possible then please at least make sure that the homepages/readme.md of the respective repos point out clearly to newcoming users in their README.md what is hosted/handled where, and where users should direct their feedback/efforts to. Thanks.

**Comment by bfleischer** [comment]
> I reported and meanwhile closed a [Mac FUSE related issue](https://github.com/libfuse/libfuse/issues/678) at the wrong place due to misinformation in the `README.md` at https://github.com/macfuse/library which states:
> 
> > Please report any bugs on the GitHub issue tracker at https://github.com/libfuse/main/issues

The issue you are running into is most likely related to sshfs. I think, the best starting point for investigating the issue would be the error handling in sshfs. sshfs should gracefully unmount the volume in case the connection is lost or cannot be established in the first place.

My main focus is maintaining macFUSE. This rarely leaves any time to look into sshfs-specific issues.

> ## Inquiries
> 1. If you are the same people, or at least connected, could you please update that info, so that Mac specific issues land where they should, so supposedly here at https://github.com/osxfuse/osxfuse

FUSE on Linux and FUSE on macOS are separate projects. General libfuse issues should be reported to the upstream project. macFUSE-specific issues should be reported to the macFUSE project. The README.md file in https://github.com/macfuse/library contains only Linux-specific information that (for the most part) do not apply to FUSE on macOS. The repository contains a minimally patched version of libfuse that runs on macOS. The modifications are kept to the bare minimum to make merging in upstream changes less painful.

> 2. The other problem is one of branding/terminology:
> 
> * Apple rebranded its OS from "Mac OS X" to "macOS" in 2016.

That's why osxfuse has been rebranded to macFUSE. 

> * So newcomers may suspect "macfuse" to be the more current or more adequate repo than "osxfuse" which refers to a name not used by Apple anymore.

The macFUSE GitHub organization is (in some regards) more current than the osxfuse GitHub organization. However, it's still a work in progress and it's still too early to make the transition. In the long run I intend the macFUSE organization to be the new home for FUSE on macOS. Until last year, the macfuse GitHub organization was owned by an unrelated third party. After I became the owner of the organization, I started moving the code and other content over. But it's still a work in progress.

> * From that perspective ideally macfuse should be the main place of activity

I agree, see above.

> * If that is not adequate or possible then please at least make sure that the homepages/readme.md of the respective repos point out clearly to newcoming users in their README.md what is hosted/handled where, and where users should direct their feedback/efforts to. Thanks.

See above. The README.md file applies to FUSE on Linux, not macOS. Simply adding a line "Please raise macOS-specific issues at https://github.com/osxfuse/osxfuse" would be short sighted. And quite frankly most issues would still land in the wrong place. How should a user know or decide wether an issue is macOS-specific or not. The proper (but time consuming) solution would probably be drafting a completely new README file for macOS. The easy "solution" would be deleting the README.md file.

**Comment by porg** [comment]
Thanks for the infos.

However you do it eventually: Make it clear for users who are willing to report/contribute, to find the right place.

As you are in control of both osxfuse and macfuse now, this should be do-able for you.
