### ISSUE TITLE
Closed Source Security

### ISSUE THREAD

**Issue by ghost** [osxfuse/osxfuse#893]
In issue #841, there was a discussion about having a closed source project and what that means for the security of end users.

The point you (Benjamin) got across was that you should be compensated for your work, because without compensation to you the project would be unsustainable. And this makes sense.

You and @hackerb9 talked about trust, specifically how users can trust that osxfuse is free of bugs and security issues. You responded that it is up to users to decide whether to trust you to maintain the code, and that a lot of macOS and iOS are closed source also, yet we still put up with them. And this is true.

This is true, but Apple has a security team auditing their source code and as far as we know, you are the only one managing the security of the macFUSE source code.

I wonder if there are solutions to the problem now. In issue #503, you discussed Apple-provided APIs which might allow macFUSE to become a userspace application, and said they weren't ready. Are there any updates on that issue?

**Comment by bfleischer** [comment]
There is still no user space API for developing full-featured file systems on macOS. And even if there was, it would not solve the VeraCrypt issue you are mentioning. A closed source user space file system implementation would still have full access to the encrypted data on the VeraCrypt volume. The underlying issue is not the kind of API that is used to develop file systems, it is transparency. 

However, even if the macFUSE kernel extension was open source, users would still not be able to compile it and load it without disabling major security features of macOS. Kernel extensions need to be signed using a special Developer ID certificate for singing kernel extensions and notarized by Apple. This means that the majority of uses would need to trust that the binaries I'm providing are actually built from the open source macFUSE code. This would not be very transparent. 

Granted, performing security audits would be easier if the kernel code was open source, but quite frankly I was never contacted by anyone who actually wanted to do a security audit during the eight years the kernel extension has been open source. While I agree with your reasoning, this is more of a theoretical argument. I'm not against reputable third parties performing security audits of the macFUSE code, but this does not require the macFUSE code to be open source.

It would be great if government organizations that are relying on VeraCrypt and macFUSE would actually help fund both projects. I cannot speak for VeraCrypt, but the macFUSE project is not receiving any funding from government organizations.

**Comment by nirmit** [comment]
Hey @bfleischer, apologies if this question has already been answered, but how can one donate to this project?  I couldn't find any links on the project page or repo.

**Comment by Unnameless** [comment]
>  I'm not against reputable third parties performing security audits of the macFUSE code, but this does not require the macFUSE code to be open source.

Indeed, but correct me if I'm wrong, the the third party gets to audit the closed code, that clearly means they get to see the code, meaning a some sort of NDA contract has to be signed. Otherwise the audit becomes pointless, as the auditor cannot make public the findings without revealing any or much of the source code. It could at best reveal the security issues only to the dev, in which the dev is in charge if he acts upon that info or not, making the audit, again, kinda pointless.

**Comment by bfleischer** [comment]
@Unnameless

The point of security audits is to discover vulnerabilities and making sure those vulnerabilities are addressed. This is usually achieved by publishing security issues after the developers have been given enough time to address those issues. Security researchers can reveal vulnerabilities without posting any of the audited source code. In fact, this is common practice. Revealing vulnerable source code to the public (instead of the developers) is rather pointless. 

A software being open source does not result in security researcher lining up to do audits. I was never contacted by anyone who did a security audit during the eight years macFUSE has been open source. This makes this a completely theoretical discussion.

**Comment by bfleischer** [comment]
@nirmit Currently there is no way for individuals to donate to the macFUSE project.

**Comment by nirmit** [comment]
What about corporate donations? :)

**Comment by bfleischer** [comment]
@nirmit Please drop me an email. You can find my email address on my GitHub Profile.
