### ISSUE TITLE
Finder not "refreshing" after directory changes

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#898]
MacOS 10.14.6, MacFuse 4.2.5

I've noticed this issue increasingly and I've not figured out a why. I could not see if there was any logging in Macfuse to enable to possible note issues.

Rclone (latest) mounted, initially with vfs cache full, now changed to writes (no difference).

You can have a directory, with contents within, yet when you change its directory name it does not then show the contents when the file rename is complete.  I've gone back up the directory levels in case it would force refresh. 

Finder can also be very slow, or non-existent, to update a renamed file within the directory, yet it shows on the rclone destination. 

I can confirm the data is existing with rclone ls to the directory that is renamed and see the files underneath.

Any thoughts, or ways to possible troubleshoot in a way to help the app if there was a sporadic issue. This happens between reboots too.

**Comment by bfleischer** [comment]
> Any thoughts, or ways to possible troubleshoot in a way to help the app if there was a sporadic issue. This happens between reboots too.

If you are not seeing the correct file structure after unmounting and re-mounting the volume (or rebooting in between) you are most likely dealing with an rclone caching issue. The are no caches in macFUSE that would survive an unmount and re-mount.

Please note that the file system (rclone, in your case) needs to inform macFUSE of remote changes so that Finder can be refreshed. This means, macFUSE will only know about remote renames, if clone informs macFUSE about it. There is an API for notifying macFUSE of remote changes.

**Comment by DarrenPIngram** [comment]
OK thank you for the feedback. I do not know if it is Finder not reading or
responding to "busy" messages or whether Rclone could be better making
whatever notification. That knowledge is way above my grade.

**Comment by bfleischer** [comment]
There has been no new information, so I'm closing the issue.

**Comment by DarrenPIngram** [comment]
I've not observed the issue, or got immune to it, and the very latest version has worked so far.
