### ISSUE TITLE
Macfuse hangs itself after a short time

### ISSUE THREAD

**Issue by AzlanNI** [osxfuse/osxfuse#900]
Hello Everyone! 

I am really new to mounting with MacFuse so maybe i am missing something. 

I just donwloaded macFUSE4.40 and SSHFS 2.5.0 on my Macbook Air. And tried to mount our HPC Cluster whichs bs is Linux. 

I created a mount folder on my Desktop and used:

fuser -c /mountfolder directory

After that  i use the command : 

Username@adress.de: /Directory on the HPC i want to mount /directory of mount folder

and i insert my Password 

Everything works fine till this point. After a short time like 1 min maximum the connection to the mounted directory gets disturbed. And i get the Error Device not configured. I cant ses any files and use the connected directory in any Program.  Also the Finder hangs itself for a short time. 

So maybe i am missing a Step or something. 
Just got to edit it ic cant access any files from the mounted directory with e.g. Pythong without haveing this freeze and then disconect. 
Thanks 4 ur help. 

kind regards 
Azlan

**Comment by bfleischer** [comment]
macFUSE unmounts unresponsive volumes after daemon_timout (mount option, defaults to 60 seconds). If you are dealing with a slow network connection or large files, your file system might become unresponsive or appear dead. That being said, version 4.4.0 contained a bug that could lead to a deadlock with similar effects. The bug was fixed in 4.4.1. I'm assuming this is what caused your freezes with python. 

Feel free to reopen the ticket in case the issue still persists with macFUSE 4.4.1.

**Comment by nduong-ol** [comment]
Hello @bfleischer , I'm encountering the same problem with macfuse 4.6.0. Can you clarify the daemon_timout, is it a timeout for every fuse operation implemented by the fuse module or it's only for certain operations?

**Comment by bfleischer** [comment]
The timeout applies to all operations. Please see https://github.com/macfuse/macfuse/wiki/Mount-Options#daemon_timeout.

**Comment by nduong-ol** [comment]
Thanks
