### ISSUE TITLE
M1 chip Mac can't reload extensions

### ISSUE THREAD

**Issue by SzVLsY** [osxfuse/osxfuse#904]
A brand new system on initial installation and startup I receive a notification that extensions were disabled and I can allow extensions in settings.

But at that point I restored the security settings in recovery mode and I did not uninstall macfuse.

Then when I reduce security again and allow kernel extensions I don't get any more notifications asking if I enable extensions.

I have tried all of the solutions in #[828](https://github.com/osxfuse/osxfuse/issues/828)and some of Google's solutions, unfortunately they only seem to work on Intel machines.

I guess this is because earlier system cache preferences are not updated. But unfortunately because the Mac is a super black box, I have absolutely no idea how to clear the kernel extension cache. There is mention of deleting cache files in #822, but that didn't work for me.

**Is it possible to add a feature that automatically disables extensions when macfuse is updated and installed?**

Also, Apple doesn't seem to offer a new file system API?

I honestly don't think this is due to technical issues. If Apple completely disables kernel extensions in the future does this mean macfuse and software that relies on macfuse will stop supporting Macs?(I also don't think Apple will provide a full filesystem API in the future)

**Comment by bfleischer** [comment]
> Then when I reduce security again and allow kernel extensions I don't get any more notifications asking if I enable extensions.

macFUSE will display a prompt whenever you try to mount a volume unless the security settings allow the macFUSE kernel extension to be loaded.

What file system are you trying to use? What happens when you try to mount a macFUSE-based file system?

> I have tried all of the solutions in #https://github.com/osxfuse/osxfuse/issues/828 and some of Google's solutions, unfortunately they only seem to work on Intel machines.
>
> I guess this is because earlier system cache preferences are not updated. But unfortunately because the Mac is a super black box, I have absolutely no idea how to clear the kernel extension cache. There is mention of deleting cache files in https://github.com/osxfuse/osxfuse/issues/822, but that didn't work for me.

Messing with system cache or the kernel extension cache should not be required, not on a fresh macOS installation. Clearing  the kernel extension cache is only required in very rare cases.

> Is it possible to add a feature that automatically disables extensions when macfuse is updated and installed?

Can you explain what you mean? Whenever macFUSE is updated, you will be prompted again to allow loading the macFUSE kernel extension. 

> Also, Apple doesn't seem to offer a new file system API?

Available information is pointing towards Apple working on a new API. Something like this takes time. There are already trace of such a new API in macOS 12. 

> I honestly don't think this is due to technical issues. If Apple completely disables kernel extensions in the future does this mean macfuse and software that relies on macfuse will stop supporting Macs?

Apple will not deprecate or disable file system kernel extensions until after they made a new replacement API available and gave developers enough time to transition to the new API. That's how Apple has handled the transition for all other now disabled kernel APIs.

**Comment by SzVLsY** [comment]
No, I'm sure I'm not getting any prompts whether I turn off SIP or not, and I'm sure I've lowered the security settings.

On the first mount I saw the prompt, then reduced security then allowed the kernel extensions, then I restored the security settings, but when I mounted again I saw no prompt and the VC prompts that the kernel extensions were not being read. The error code was already submitted a few months ago as a issue.

I have tried almost every solution except formatting the drive.

The problem is that I can't get any prompt about the kernel extensions on an OS that is installed in an external drive and whenever updating and installing macFUSE 

I am not prompted again to allow the macFUSE kernel extensions.

So, I guess it's about kernel extension cache

https://github.com/osxfuse/osxfuse/issues/754#issuecomment-863590001

**Comment by bfleischer** [comment]
> The problem is that I can't get any prompt about the kernel extensions on an OS that is installed in an external drive and whenever updating and installing macFUSE

Third-party kernel extensions are not supported on Apple Silicon Macs when macOS is installed on an external volume. It'S unclear if this is a macOS bug or by design.
