### ISSUE TITLE
Unable to view external drives after enabling for pCloud

### ISSUE THREAD

**Issue by klamok001** [osxfuse/osxfuse#936]
I have a 2023 MacBook Pro 16 inch (M2 Pro) running macOS 13.2 (22D49). After installing and enabling system kexts to get pCloud Drive to work, pCloud Drive works as intended, but my Mac has been unable to detect any other external drives that are connected to it. Those drives are formatted in exFAT.

These external drives can be recognised by other MacBooks, and are also recognised once system kexts are disabled.

Connected Android phones and Logitech receivers can still function.

I also have another system kext from JMicron Technology Corp. that was installed as part of Xcode. I am unfortunately not sure how to disable that extension to troubleshoot if macFUSE or that extension is the cause, but I would be happy to do so if someone can provide me instructions on how to do so.

I'm new to reporting issues here, so please let me know if I need to generate any system reports to aid in troubleshooting.

Thank you!

**Comment by bfleischer** [comment]
In macOS 13 Apple uses a new file system implementation for exFAT and FAT32 volumes. But I'm not aware of any conflicts with macFUSE.

I did a quick test, but I'm unable to reproduce the issue on macOS 13.2 (22D49). I was able to mount an exFAT volume while a pCloud volume is mounted. I assume there must be more to it than just mounting a pCloud volume. 

You said your Mac is unable to detect the external drive. Could you clarify this? Does the external drive appear in Disk Utility after plugging it in?

**Comment by klamok001** [comment]
I see, didn't know about the new file system implementation for exFAT and FAT32 volumes.

When the system kexts are enabled, apart from the virtual pCloud Drive, all other external drives are not detected by the Mac, and they do not even show up in Disk Utility. After a while of plugging them in, the drives also turn off automatically (i.e. the activity lights stop flashing).

However I can confirm it is not an issue with the external drives as they can be read & written to again once the system kernal extensions are disabled in Recovery Utility.

I guess the current issue at hand could be macFUSE, the other JMicron system kext as part of Xcode, or the M2 Pro processor.

**Comment by bfleischer** [comment]
Your external drive not showing up in Disk Utility means that the issue is most likely not related to exFAT. Your Mac should be able to detect the volume even though it might not be able to mount the file system. I tried to reproduce the issue on a MacBook Pro 2023 (M2 Max) and a Mac mini (M1), but I did not encounter any issues mounting external exFAT volumes while a FUSE volume is mounted. I don't think this is a general incompatibility, otherwise there should have been more bug reports by now.

Did you look for errors in Console app around the time you are plugging in your external drive? It might be best to report the issue to Apple. I don't see how macFUSE could interfere with your Mac detecting external drives.

**Comment by klamok001** [comment]
Hi Benjamin, my sincere apologies for the late response; been swamped with work and didn't get to do as you suggested. Wasn't too sure about the Console errors, but after Apple released 2 software updates in the meantime, macFUSE is finally working as intended. I am now able to enable macFUSE to load pCloud Drive, and my external drives can be read. Thanks for helping to make this possible!
