### ISSUE TITLE
Benjamin's PGP key

### ISSUE THREAD

**Issue by Bonobo55** [osxfuse/osxfuse#942]
Hi guys,

When I try to verify the signature file of the newest release of MacFUSE it tells me Ben's key is expired, info:

Signing key:
Benjamin Fleischer <fleiben@gmail.com.
135F 164B 411B AA1F 4A4B CD37 617A 3461 8026 08A1

Signed File:
macfuse-4.4.2.sha256

@bfleischer I want to be sure that the software is coming from you. What is your current public key?

Thanks for your response in advance

Bono

**Comment by ernstki** [comment]
The solution can be found by [searching closed issues for "gpg"](https://github.com/osxfuse/osxfuse/issues?q=is%3Aissue+gpg+is%3Aclosed).

For GPG, I was able to resolve this with `curl https://osxfuse.github.io/static/53C918C1A2818875.asc | gpg --import`, then retrying `gpg --verify mac.*sig`.

@bfleischer <s>If I were to add a FAQ entry for this—because I had the same question, and there are 9 closed issues about this, plus this one—which repository should I do the PR against? This one or macfuse? (_That_ could be a FAQ of its own, the difference between the two GitHub orgs, at least until the name change is complete.)</s> **Edit**: Oh, oh, oh, never mind. There's no FAQ in the macfuse wiki, just the one [here](https://github.com/osxfuse/osxfuse/wiki), and I forgot I don't need to do a PR to edit that!

**Comment by ernstki** [comment]
See [FAQ 1.3](https://github.com/osxfuse/osxfuse/wiki/FAQ#13-how-do-i-verify-the-integrity-of-the-release-assets-with-pgpgpg).

@Bonobo55, recommend closing the issue as resolved, unless you need further help or the instructions in the FAQ aren't clear.

**Comment by bfleischer** [comment]
@ernstki Thanks for updating the FAQ.
