### ISSUE TITLE
Clearing file cache on macFUSE drive on Forklift3

### ISSUE THREAD

**Issue by jonshepherd68** [osxfuse/osxfuse#951]
I use Forklift3 mini to mount an FTP drive on an FTP server that I don't own and cannot control.  A file on this drive is updated every 15 minutes but the file size does not always change and because Forklift doesn't change the auto_cache parameter, the cached file does not get updated because it doesn't check for changes in date and time.

Forklift say its a macFUSE problem but I'm not sure it is.

If I unmount an remount the drive, it refreshes the cache but I need to automate this process.  Un-mounting is easy but I can't remount it.  I've tried installing fuse-ext2 but this is failing on Ventura. Is there anyway to make MacFUSE mount drive with the auto_cache setting by default?  Or another way to flash the file cache using a crontab process?

**Comment by bfleischer** [comment]
It's definitely not a macFUSE issue. macFUSE contains an API that allows file systems developers to notify Finder (and all other processes on your system) in case a file is changed remotely.

I would like to add that the ForkLift team is not supporting the continued macFUSE development in any way. Blaming issues of their app on macFUSE is more than unfair, especially since they are using macFUSE commercially and exploit a loophole in the macFUSE license to do so.

**Comment by jonshepherd68** [comment]
FYI - I found the solution in CloudMounter - they have a specific parameter to select how often to clear the cache.  It work perfectly now using macFUSE.
