### ISSUE TITLE
Can not approve system extension

### ISSUE THREAD

**Issue by iCanHazSoftware** [osxfuse/osxfuse#963]
macOS 13.4.0. Get the pop up to approve system extension.  Even with SIP off it will not load.
Tried reboot multiple times.  Device is managed in MDM but approved team ID 3T5GSNBU6W as well.

**Comment by budachst** [comment]
Are you sure, that this is a system extension? I thought, that macFUSE still depends on a kernel extension…

**Comment by thistlillo** [comment]
Same here on a managed machine, Ventura 13.5.1 and MacFUSE 4.5. I do not know if this depends on the fact my machine is managed, because installation is disorienting:
- developer asks to approve its extension, but I cannot see how.
- If I visit System Prefs, I see this:
<img width="491" alt="Screenshot 2023-09-04 at 14 22 29" src="https://github.com/osxfuse/osxfuse/assets/6717655/48a2e9b0-5968-44d5-8c3e-d204a6b9782f">

When I click on "Enable", this dialogue appears:

<img width="318" alt="Screenshot 2023-09-04 at 14 12 12" src="https://github.com/osxfuse/osxfuse/assets/6717655/9fb00021-d386-4615-9ffc-db7a4245fb9f">

But, if I restart as they say, I see many choices but there is not a Startup Security Utility.

Is something wrong with the distributed files or the "management" prevents this?

**Comment by bfleischer** [comment]
See https://github.com/macfuse/macfuse/wiki/Getting-Started. The document contains instructions on how to enable the macFUSE kernel extension (on unmanaged Macs). Feel free to open a new ticket if you are still running into issues.
