### ISSUE TITLE
osxfuse doesn't remove folder in Volumes after unmount

### ISSUE THREAD

**Issue by kondak3** [osxfuse/osxfuse#972]
Hi Team,

We are using "https://github.com/macfuse/demo" application.
osxfuse 4.5.0
macOS 13.4.1

Please help on this.
- Folder doesn't remove from the volumes after unmount.
- Mount getting failed with the below errors 

```
    a) Gave up waiting for directory under /Volumes to be removed after cleaning up a dead file system mount
    b) Internal FUSE error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console
```

As per the demo, if mount gets a failure, we are terminating the application. shall we retry one more attempt?

**Comment by bfleischer** [comment]
> Folder doesn't remove from the volumes after unmount.

Folders in `/Volumes` are removed by macOS after a successful unmount. If the mount process of the file system fails the folder might not be removed.

> Mount getting failed with the below errors

Which of the three demo file systems did you use? Did you modify the file system in any way?

**Comment by kondak3** [comment]
> Which of the three demo file systems did you use? Did you modify the file system in any way?

Using Loopback-Swift. Currently, it hasn't changed anything.
For all fuse failures, can we try the re-mount or not? have to avoid retrying based on any errors?

**Comment by kondak3** [comment]
`Gave up waiting for directory under /Volumes to be removed after cleaning up a dead file system mount`
mount fails with this error. When the dead file system will be cleared from the volumes.

**Comment by bfleischer** [comment]
Loopback-Swift works fine for me. What happens when you use one of the other Loopback variants?

Did you check whether the macFUSE kernel extension is loaded after four mount attempt fails?

> For all fuse failures, can we try the re-mount or not? have to avoid retrying based on any errors?

This would be a bad idea. Re-mounting the volume automatically could mask serious issues and make the situation worse (data loss).

> When the dead file system will be cleared from the volumes.

macFUSE does not remove folders in `/Volumes`, macOS does. In your particular case you might want to remove the folder manually.

**Comment by kondak3** [comment]
> Did you check whether the macFUSE kernel extension is loaded after four mount attempt fails?

`after four mount attempt fails` This means we can try up to four times
After Fuse installation `Security & Privacy` accepted `allow`
How to check if `kernel extension` is loaded or not, programmatically. If it's not loaded, how do I load it?

**Comment by bfleischer** [comment]
Trying four time makes no difference. Once is sufficient. Three additional attempts are not going to change anything. 

I believe your file system failing to mount after the directory under /Volumes is created is most likely an error on your end. If you disagree, please provide detailed repro steps so that I can try to reproduce the issue.

I recommend looking into the original mount issue rather than trying to find ways to mask the issue.

> How to check if kernel extension is loaded or not, programmatically. If it's not loaded, how do I load it?

The kernel extension is loaded by macFUSE automatically when you try to mount a volume. To load it manually (only for testing purposes), run the `load_macfuse` tool in `/Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse`. You can use `kextstat` (only for testing purposes) to verify that the kernel extension was loaded.

**Comment by kondak3** [comment]
macOS 13.5.0 is also facing the same errors continuously.
```
    a) Gave up waiting for directory under /Volumes to be removed after cleaning up a dead file system mount
    b) Internal FUSE error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console
```

After a mount is created in /Volumes, if we replace the file in the source folder, it is not replaced in the volumes. There is any option to dynamically refresh the mount files.

**Comment by bfleischer** [comment]
I cannot help you without more information. The LoopbackFS demo file system works fine for me on macOS 10.9 to macOS 14. Without detailed repro steps there is nothing I can do.

> After a mount is created in /Volumes, if we replace the file in the source folder, it is not replaced in the volumes.

You need to notify macFUSE of remote changes. Have a look at `[GMUserFileSystem invalidateItemAtPath:error:]`.

Are you developing a commercial software? If so, please contact me (my email is on my GutHub page) and we can look into commercial support options and/or a license agreement for using macFUSE commercially.

**Comment by kondak3** [comment]
> You need to notify macFUSE of remote changes. Have a look at [GMUserFileSystem invalidateItemAtPath:error:].

If we are using the "local" attribute also, will it work?

> Are you developing a commercial software? If so, please contact me (my email is on my GutHub page) and we can look into commercial support options and/or a license agreement for using macFUSE commercially.

It's not commercial software.

**Comment by bfleischer** [comment]
>> You need to notify macFUSE of remote changes. Have a look at [GMUserFileSystem invalidateItemAtPath:error:].
>
> If we are using the "local" attribute also, will it work?

`local` might make the situation worse. Technically speaking, by definition, a local volume cannot (or at the very least should not) be altered "remotely". A file system that can be altered externally/remotely (while being mounted) should use the notification API to tell macFUSE about those external changes.
