### ISSUE TITLE
System Extension Error

### ISSUE THREAD

**Issue by ravenep** [osxfuse/osxfuse#988]
Hello, 

First things first: 

I am running a 2021 Mac Pro M1 chip, OS Ventura 13.6.2. I have installed MacFuse 4.5.0

The tutorial was straightforward to follow for installation, especially from the screen shots, and I did the many approvals and reoboots, and reducing security, etc as recommended. At the end of this, I have been getting the "System Extension Error"  Following many users advice and the final option on the install tutorial, I have disabled the SIP. This did not seem to make a dent. 

<img width="305" alt="error" src="https://github.com/osxfuse/osxfuse/assets/12449573/060543a0-6aa6-408a-b83c-8484e5238118">

To potentially rule some things out:

- I am always able to see: _System Software from developer "Benjamin Fleischer' has been updated_ / the 'Allow' button in Privacy and Security. I know some users had that as an issue. 
- I have uninstalled and reinstalled the software many times.
- This is on my primary machine, not an external hard drive

I did see other users discussing a cache. Perhaps this is my issue? Here are the contents of my Library. 

<img width="427" alt="cache" src="https://github.com/osxfuse/osxfuse/assets/12449573/169b01fa-af02-4626-8877-ed197b4b63e7">

Any tips would be greatly appreciated from the community. Thanks so much, 
Erika

**Comment by cessna117ab** [comment]
Same issue here. 2019 Mac Pro on 12.7.1. Tried rolling back to MacOS Fuse 4.4.2 that I have successfully installed on another system, but still stuck in this loop of death of allowing the extension, rebooting, being prompted to allow the extension again. Sadly, the system is in a remote location, so need to wait until someone can physically boot into recovery to make sure 3rd party extensions aren't being blocked, and maybe give the ol' csrutil a disable. I will report back if I manged to get it working.

**Comment by cessna117ab** [comment]
Full system shutdown and then power back on was the solution on this for me.

**Comment by ferdnyc** [comment]
@cessna117ab Glad you solved it, I suspect that was a separate issue since @ravenep 's screenshot indicates that the system wasn't prompting to _allow_ the extension, but rather reporting that they "need to be rebuilt".

@ravenep, that does sound very much like a cache issue, the kext cache being the thing that would "need to be rebuilt".

kext cache was previously managed by the `kextcache` tool. But even in macOS 10.15 (the latest release I have available to me, and on an Intel platform too), the tool was pretty much deprecated. Its man page opens:

> #### DESCRIPTION
> 

> The `kextcache` program creates kext caches, which speed up kext loading      operations.  It is invoked automatically as needed to rebuild system      caches.
> 
> Caution: Incorrect use of `kextcache` can render a volume incapable of      startup.  Installers and administrators should not use this program to      update system kext caches.  Instead they should run `touch(1)` on the      `/System/Library/Extensions/` directory of the installation target volume      after they have finished, which invalidates the existing caches and      causes the system to update all necessary kext caches. `kextcache -update-volume` can be used to wait for this process to complete.

...And that advice has likely changed even further in later macOS releases, particularly for Silicon Macs. Heck, I don't even know if `kextcache` is still included with the OS anymore.

In 10.15 and earlier, there are a whole suite of kernel-extension management tools:

```console
% man -k kext|grep -E '^kext'
kext_logging(8), kext logging(8) - verbose/logging flags for kernel extensions (kexts) in the kernel and command-line utilities
kextcache(8)             - create kext cache files
kextd(8)                 - kernel extension server
kextfind(8)              - find kernel extensions (kexts) based on a variety of criteria and print information
kextlibs(8)              - find OSBundleLibraries needed by a kext
kextload(8)              - load kernel extensions (kexts) into the kernel
kextstat(8)              - display status of loaded kernel extensions (kexts)
kextunload(8)            - terminate driver I/O Kit driver instances and unload kernel extensions (kexts)
kextutil(8)              - load, diagnose problems with, and generate symbols for kernel extensions (kexts)
```

...but with kexts being deprecated now, I wouldn't be surprised if most of those are gone. It's also possible [a tool named `kmutil`](https://developer.apple.com/forums/thread/685011) has replaced some or all of them, but I don't have access to that as it didn't exist in 10.15.

Running 10.15 on an Intel CPU, though, with macfuse installed I'm able to use `kextstat` to see that it's loaded:

```console
% kextstat -b io.macfuse.filesystems.macfuse
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  134    0 0xffffff7f83102000 0x19000    0x19000    io.macfuse.filesystems.macfuse (2128.16) 3038FEA7-BCD4-3EEE-B88E-EED43813782A <8 6 5 3 1>
```

And, using `sudo` to get root permissions, I can use `kextutil` to simulate loading and report on the results. (That's sort of silly for _me_ because it's **already** loaded, but it could be useful on a system where loading has failed or been blocked.)

```console
% sudo kextutil  -n -t -v 4 /Library/Filesystems/macfuse.fs/Contents/Extensions/10.15/macfuse.kext 
Password:
Kext library architecture set to x86_64.
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext library recording diagnostics for: validation authentication dependencies warnings.
Reading loaded kext info from kernel.
/Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext appears to be loadable (including linkage for on-disk libraries).
```

It may also be the case that whatever kext-management tools remain can now _only_ be used in recovery mode (is it possible to access a Terminal window from inside Recovery mode?), since AIUI the kernel on Apple Silicon systems is made immutable at runtime. It wouldn't accept any kext-load requests after startup -- hence the hard requirement for a system reboot in order to activate new extensions.

**Comment by ferdnyc** [comment]
> AIUI the kernel on Apple Silicon systems is made immutable at runtime

I understood [correctly](https://developer.apple.com/documentation/kernel/implementing_drivers_system_extensions_and_kexts#3616858):

> Kexts run under [Kernel Integrity Protection](https://support.apple.com/guide/security/kernel-integrity-protection-secb1caeb4bc/1/web/1) (KIP). After the system initializes the kernel and kexts, KIP locks down the kernel memory pages to prevent modifications to kernel and driver code. For more information about KIP, see Kernel Integrity Protection.

**Comment by ravenep** [comment]
Hello! Thank you @cessna117ab and @ferdnyc for your comments

Happy news for 2024.  I had almost given up, but am working now for both read / write. The work around for me was installing the dev release of 4.6.0, after that no errors 

Before that, I was able to confirm that my OS does have kextcache. I was hesitant to work with any kext management tools as a novice user however so am happy it came together with this update. 

Thanks again for the feedback. I appreciate it so much!

**Comment by ferdnyc** [comment]
@ravenep That's great news! Since this is solved for you, you can feel free to close this issue yourself if you'd like, otherwise I'm sure one of the osxfuse repo admins will take care of it.

Thank you for the updates re: `kextcache`, BTW, that's very helpful. I really need to find a way to move my Hackintosh install past 10.x someday, now that it's officially completely unsupported.
