### ISSUE TITLE
Slow USB write speeds. 2+ hours for 17gb file?

### ISSUE THREAD

**Issue by futurepr0n** [osxfuse/osxfuse#994]
Is this normal? I feel like it goes much faster. I have a USB3.0 stick going into USBC port on my MBP, Monterey 12.6.8. I mounted using the suggested commands: 

`sudo /usr/local/bin/ntfs-3g /dev/disk2 /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache`

This mounted great, and was able to view the disk proper and read and write to it, but was dreadful speeds. Im hoping I just had a configuration or setting wrong that would be helpful.

Installed version 4.6.0
<img width="668" alt="Screen Shot 2024-01-03 at 3 21 09 PM" src="https://github.com/osxfuse/osxfuse/assets/478986/46261760-7a70-43d9-9b8f-1fcedbd4d93c">

<img width="513" alt="Screen Shot 2024-01-03 at 3 21 24 PM" src="https://github.com/osxfuse/osxfuse/assets/478986/2e392c83-c7fa-4356-ba44-cda08b54a033">

**Comment by bfleischer** [comment]
The slow write speeds are most likely not caused by macFUSE. As far as I remember there is an optional caching layer for NTFS-3G that speeds up writes significantly. Please refer to the NTFS-3G documentation. 

Please note, macFUSE and NTFS-3G are separate projects and providing support for NTFS-3G goes beyond the scope of the macFUSE project. The NTFS-3G teams should be better suited to help you with this.
