### ISSUE TITLE
MacFuse 4.6.0 kernel panic MacOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by kevinatbcp** [osxfuse/osxfuse#999]
Trying to troubleshoot a kernel panic crash of MacOS. We're using MacFuse 4.6.0 with an LTO-7 tape drive (LTFS). Mac software application is Hedge Canister. Mac Mini M1 (MacOS Sonoma 14.2.1) with built in 10GBE connected to a QNAP NAS, thunderbolt 3 to a Sonnet Echo Express SEI with an ATTO ExpressSAS H680 interface card and our dual rack mount LTO-7 tape drives. Getting occasional kernel panic crashes of the computer during Hedge Canister file backups to the tape drive. Any ideas would be appreciated.

[crash logs.zip](https://github.com/osxfuse/osxfuse/files/14314322/crash.logs.zip)

**Comment by GeckoGB** [comment]
I was looking for some info about osxfuse and LTFS source code compilation on Sonoma 14.3, and found your message. So i  had a look at your crash info, and i can see this:

`Panicked task 0xfffffe24f5089908: 1189583 pages, 10 threads: pid 1262: com.rockysandstu`
and
`"procname":"com.rockysandstudio.Memory-Diag"`

Memory Diag seems to be a software from Rocky Sands Studio, which analyzes memory usage:
https://apps.apple.com/ca/app/memory-diag/id748212890?l=fr&mt=12

I can be wrong, but it seems to me that the crash has nothing to do with MacFuse/LTO backup. Or maybe indirectly, if the back up process is stressing your system and trigger a bug in Memory Diag, or something like that.

Nice setup you have. I'm currently trying to use 2 LTO 5 and 6 drives attached to a 2019 Intel Macbook Pro running Sonoma woth a Sonnet Echo Express SE I and Atto ExpressSAS H644, so relatively close to your setup, but have some trouble since the 2 drives are from different brands (Tandberg and IBM), and LTFS binaries from each manufacturer refuses to recognized drives from another brand.

**Comment by kevinatbcp** [comment]
GeckoGB, thanks so much for your help, I didn't notice that. I'll trash that app and see if that solves the issue. Appreciate your time in responding! Good luck with your setup, I wish support for LTFS was a little more robust on MacOS, both from Apple and the hardware vendors!
